### ISSUE TITLE
Representation after update,save

### ISSUE THREAD

**Issue by hajcu** [picqer/exact-php-client#102]
After save or add object exactonline api do not return info about codeid, and other data.

I fix this by changing in Connection.php headers from 

```php
$headers = array_merge($headers, [
            'Accept' => 'application/json',
            'Content-Type' => 'application/json'
]);
```
into
```php
$headers = array_merge($headers, [
            'Accept' => 'application/json',
            'Content-Type' => 'application/json',
            'Prefer' => 'return=representation'
]);
```

**Comment by stephangroen** [comment]
Do you have a link to the Exact Online docs describing this?

**Comment by stephangroen** [comment]
@silvant Do you have a link to the Exact Online docs describing this?

**Comment by thijswiersema** [comment]
See: https://developers.exactonline.com/#RestTips.htm%3FTocPath%3DTips%2520and%2520tricks%7CAPI%7C_____1
Check combine POST and GET
