### ISSUE TITLE
[RFC] Interest in Symfony bundle?

### ISSUE THREAD

**Issue by rvanlaak** [picqer/exact-php-client#106]
In short; great library, definitely the way to go for us to integrate with Exact.

Over the upcoming weeks we wil start implementing this, and the way we'd like to do this is by creating a bridge bundle to integrate this library with Symfony. The thing we're planning on:

- [ ] Make `Connection` configurable via DIC
- [ ] Double check codebase for PSR-3 compatibility, as Guzzle also require that
- [ ] Inject `logger` into `Connection` and `Guzzle` client (I'd like to propose to go for Monolog)
- [ ] Implement `OptionResolver` on the most important required fields of `Connection`
- [ ] Decorate the `Connection` to make it a `DataCollectingConnection` that adds information to the `profiler` via [a custom data collector](http://symfony.com/doc/current/profiler/data_collector.html). 
- [ ] Make profiler panel comparable to screenshots over here: https://github.com/ludofleury/GuzzleBundle#guzzle-bundle---
- [ ] Inject `stopwatch` component to benchmark requests in [the profiler performance metrics panel](https://symfony.com/blog/new-in-symfony-2-2-new-stopwatch-component).
- [ ] Replay requests directly from the profiler (?)
- [ ] ...

Would love to hear your feedback on this.

**Comment by stephangroen** [comment]
I don't have much experience with Symfony, but if you can create the bridge bundle using this project and the bundle as a separate project, I see no problems. I'd like this one to be framework agnostic.
