### ISSUE TITLE
Show picture of item return white 1x1 px image

### ISSUE THREAD

**Issue by Robertdegraaf** [picqer/exact-php-client#108]
I'm trying to show the PictureUrl from an item shown in https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=logisticsItems.
The image returns a 1x1 px white image to non loggedin users. How can I show the images to this users with your code?

**Comment by stephangroen** [comment]
You should probably download the images with a logged in user to extract them from the API and show them in your own app.
