### ISSUE TITLE
The __call method of class Model prevents calling private method isFillable

### ISSUE THREAD

**Issue by yohancreemers** [picqer/exact-php-client#110]
The `__call` method of class `Model` (added in https://github.com/picqer/exact-php-client/commit/8f4e8127a5c0e6dda705fdaa8fbefbcf2c604c76) prevents calling private method `isFillable`.

Code example:
```
$account = new Account($connection);
if ($account->isFillable('Description') )
{
	$account->Description = $sDescription;
}
```

Is there a reason why `isFillable` shouldn't be accessible on an instance?
Possible solutions to make the code example work again:
1. Change `isFillable` in a public function, so it's call isn't handled by `__call`.
2. Let `__call` test if `$name` doesn't refer to a method, before handling it as a property. 

What's your opinion?

**Comment by GewoonRoy** [comment]
When calling `$account->Description = $sDescription` it will call the `__set` method of class `Model` which will then call the `isFillable` method automatically to check if the given attribute is fillable. So it would not be necessary to call it outside of this instance.

It is possible to check the `Account` for the expected attributes after creating the instance. But in my opinion this would be overhead.

**Comment by yohancreemers** [comment]
Thanks @GewoonRoy, you're right. 
There is indeed no need to test if the attribute is fillable before setting it.
