### ISSUE TITLE
Forbidden request on specific exact environment

### ISSUE THREAD

**Issue by robinvalk** [picqer/exact-php-client#111]
We successfully integrated the package in our application for quite a while now. Each user can use their own exact environment to log invoices, products, customers etc.

This was all working fine until recently, a specific user with a clean/newly created Exact environment get's a Forbidden response when we're trying to insert an invoice into their Exact environment. The OAuth procedure was succesful, we can even insert products and retrieve journals to work with.

I think it's probably a specific setting in Exact. Did anyone ever encounter the same issue?

Small stack trace:
1. Picqer\Financials\Exact\SalesInvoice->save()
2. Picqer\Financials\Exact\SalesInvoice->insert()
3. Picqer\Financials\Exact\Connection->post('salesinvoice/Sa...', '{"Currency":"EU...')
4. Request fails and is handled: Picqer\Financials\Exact\Connection>parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException))

**Comment by yohancreemers** [comment]
Did you check if this user has the permission to save?

```
$salesinvoices = new \Picqer\Financials\Exact\SalesInvoice($oConnection);
$b = $salesinvoices->userHasRights('PUT');

```

**Comment by GewoonRoy** [comment]
What i found out earlier was that the Account needs to have it's property 'isSales' on true to create SalesInvoices. It will probably have something to do with the permissions.

**Comment by robinvalk** [comment]
Thanks for the answers, I'll come back to this tomorrow. Maybe they're willing to share their exact credentials. That willl make things a little easier.

**Comment by robinvalk** [comment]
Today I saw in the exact environment that the salesinvoice menu item wasn't there either. I contacted support and they told me that we needed to step up our subscription one tier.

That will probably resolve my issue, I'll close it for now.
