### ISSUE TITLE
Fetching webhook data from ExactOnlineEndpoint

### ISSUE THREAD

**Issue by bemeall** [picqer/exact-php-client#116]
Hi,

Library is working fine, except I can't get it together to actually fetch data from the ExactOnlineEndpoint I get back from an webhook call.

I use the example code, and am using $connection (with headers set by authorize()).
$connection->get($exactOnlineEndpoint) keeps giving back an empty response.

Maybe someone can point me in the right direction, as I think I am simply missing something small?

**Comment by GewoonRoy** [comment]
@bemeall Did you already try to use the object `WebhookSubcription`?

**Comment by versdivers** [comment]
I'm having the same issue. I also do not get the comment 'try to use the object WebhookSubscription'. Since that Object is used to subscribe to a Webhook but not to retrieve the data. How did you solve this? @bemeall

**Comment by versdivers** [comment]
The reason why is because ->get() method will try to format the URL for you. So you end up with a weird URl if you provide a full url yourself. something like : https://start.exaconlin.be/v1/division/https://start.exactonline.be/api/v1/division/read/....

Maybe a check if the url starts with 'http' and see if it then needs to reformat the url ?

So if you provide a fill url it doesn't reformat it?

**Comment by versdivers** [comment]
Or create a new function like i did : 
    /**
     * @param $url
     * @param array $params
     * @param array $headers
     * @return mixed
     * @throws ApiException
     */
    public function getWithFullUrl($url, array $params = [], array $headers = [])
    {
//        $url = $this->formatUrl($url, $url !== 'current/Me', $url == $this->nextUrl);

        try {
            $request = $this->createRequest('GET', $url, null, $params, $headers);
            $response = $this->client()->send($request);

            return $this->parseResponse($response, $url != $this->nextUrl);
        } catch (Exception $e) {
            $this->parseExceptionForErrorMessages($e);
        }

        return null;
    }

**Comment by versdivers** [comment]
I have created a pull request for this

```
   public function get($url, array $params = [], array $headers = [])
    {
        
        // Check if has http/https -> if it does do not reformat URL. We assume Full URL is supplied
        $urlbuild = parse_url($url);
        if (empty($urlbuild['scheme'])) {
            $url = $this->formatUrl($url, $url !== 'current/Me', $url == $this->nextUrl);
        }

        try {
            $request = $this->createRequest('GET', $url, null, $params, $headers);
            $response = $this->client()->send($request);

            return $this->parseResponse($response, $url != $this->nextUrl);
        } catch (Exception $e) {
            $this->parseExceptionForErrorMessages($e);
        }
        
        return null;
    }
```
