### ISSUE TITLE
 SalesInvoice Creation

### ISSUE THREAD

**Issue by rajj1990** [picqer/exact-php-client#117]
Hi, 

I will try to create SalesInvoices in Exact online . But trigger error. 

Error 400: Error processing request stream. The request should be a valid top-level resource object. 

Mycode: 

$items = [ 
'Item' => 'ba22c9630-1d66-49df-a8e5-43298e575cee', 
'Code' => 123, 
'Description' => 'Samle Product', 
'CostPriceStandard' => 199, 
]; 

$salesInvoice = new \Picqer\Financials\Exact\SalesInvoice($connection); 
$salesInvoice->InvoiceTo = 'fd6023d5-b665-4cab-93e2-02277be162ce'; 
$salesInvoice->Creator = 'fd6023d5-b665-4cab-93e2-02277be162ce'; 
$salesInvoice->OrderedBy = 'fd6023d5-b665-4cab-93e2-02277be162ce'; 
$salesInvoice->SalesInvoiceLines = $items; 
//echo '<pre>'; print_r($salesInvoice); die('aa'); 

How to create salesInvoice?  Please help me......

**Comment by GewoonRoy** [comment]
Hi @rajj1990 ,

When creating a SalesInvoice take a look at the documentation.
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=salesinvoiceSalesInvoices

You need to have the following required fields:
- Journal _(Missing in given example)_
- OrderedBy
- SalesInvoiceLines

Try to add a Journal Code. 

If it still doesn't work, try to create SalesInvoiceLines and those to $salesInvoice->SalesInvoiceLines.
