### ISSUE TITLE
SalesEntries - Ongeldig: Grootboekrekeningtype

### ISSUE THREAD

**Issue by davidvandertuijn** [picqer/exact-php-client#121]
Adding a SalesEntryLine to a SalesEntry result in error 'Ongeldig: Grootboekrekeningtype' .

SalesEntry:
Journal: 70 // Verkoopboek
Type: 20 // Sales entry

But only for SalesEntryLine with GLAccount:
1300 - Debiteuren - 6e1bc618-8cb7-4dcd-8385-6ede9a18704f
1500 - Af te dragen BTW hoog - 0168a901-bed8-4e59-93a8-212becdc6ae2

There are no issues with other GLAccount's:
8000 - Omzet binnenland hoog tarief 
8010 - Omzet binnenland laag tarief
8020 - Omzet binnenland nultarief

Any suggestions?

**Comment by stephangroen** [comment]
Usually this means you're using a GLAccount that is not allowed on this type of object. For example, a SalesEntryLine is not allowed to use the GLAccount 1500 - Af te dragen BTW hoog. 

All 8000 accounts are revenue accounts, while 1300 and 1500 are not. This might be the problem.

**Comment by davidvandertuijn** [comment]
In the XML API this is possible with GLTransactions:
`<GLAccount code="1500" type="24"></GLAccount>`

There is no GLAccountType attribute in SalesEntryLine :(

When i use endpoint GeneralJournalEntry, this result in error 'Error 500: Ongeldig: Dagboek'.

GeneralJournalEntry:
JournalCode: 70 // Verkoopboek
Status: 20 // Open
Type: 10 // Opening balance

GeneralJournalEntry:
GLAccount: 1500 - Af te dragen BTW hoog - 0168a901-bed8-4e59-93a8-212becdc6ae2
VATType: // A = Sales VAT to pay

**Comment by davidvandertuijn** [comment]
I found out the transactions are created automaticly based on the VATCode per SalesEntry.
A Vat-Code can be assigned to a GLAccount through 'VAT to pay account' or 'VAT to claim account'.
This is visible in 'Balance Sheet/Profit & Loss'.
https://ibb.co/mSAMDv
