### ISSUE TITLE
ItemGroup: Error 403: Forbidden

### ISSUE THREAD

**Issue by ddrenth** [picqer/exact-php-client#122]
When I try to add some Itemgroup in ExactOnline I get the error:  Error 403: Forbidden. Their are now only Itemgroups in ExactOnly and the Code is not duplicated or something?

```php
        try 
        {
            $item = new \Picqer\Financials\Exact\ItemGroup( $connection );
            
            if( !empty( $artikelgroep[ 'exactID' ] ))
            {
                $item->ID = $artikelgroep[ 'exactID' ];
            }
            
            $item->Code = $artikelgroep[ 'teller' ];
            $item->Description = $artikelgroep[ 'groep' ];
            $item->GLRevenueCode = '8002';
            $item->GLCostsCode = '7102';
            $item->GLStockCode = '7099';
            $item->save();            
            
            return true;
        }
        catch (\Exception $e)
        {
            return get_class($e) . ' : ' . $e->getMessage();
        }

**Comment by casperbakker** [comment]
In most cases, Error 403 means you do not have the right permissions to retrieve that information. Did you check that this user/apikey has the right permissions to access ItemGroups or that specific ItemGroup?

**Comment by ddrenth** [comment]
As I can find in ExactOnline I have full rights. When I try to add some Itemgroup in ExactOnline it is working normaly. I can change also the existing itemGroups.

**Comment by stephangroen** [comment]
ItemGroup seems to have gotten the Storable trait by it's creator, but it is in fact not storable. The Exact Online docs state only the GET method is available for ItemGroups: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=logisticsItemGroups

You're getting the 403 because storing an ItemGroup is not possible / allowed.

**Comment by ddrenth** [comment]
Why they should block this? Is this not really strange?

**Comment by stephangroen** [comment]
You should ask Exact this :)
