### ISSUE TITLE
Call to undefined method setBaseUrl

### ISSUE THREAD

**Issue by Teneobelgium** [picqer/exact-php-client#123]
Hi

I've been trying to get this running all day. But I just can't seem to get it right.
I cleaned everyhting in my webfolder and ran the composer command.
I then loaded the example code and changed my secret id , etcetera.

Now I get the error : 
Fatal error: Call to undefined method Picqer\Financials\Exact\Connection::setBaseUrl()

Indeed, when I look in the vendor\picqer\exact-php-client\src\picqer\finaancials\exact\connections.php file there is no such function. 
When I add it manually the error goes away and then the next error is there

Fatal error: Call to undefined method Picqer\Financials\Exact\Connection::setTokenUpdateCallback()

And that function too is missing, etcetera ...

What am I doing so wrong ?
Thanks !

**Comment by casperbakker** [comment]
Coul you post the code you are using? Do not forget to remove your secret ID etc.

**Comment by Teneobelgium** [comment]
Yes sir, please find below the code used.

`<?php

// Autoload composer installed libraries
require '/vendor/autoload.php';

/**
 * Function to retrieve persisted data for the example
 * @param string $key
 * @return null|string
 */
function getValue($key)
{
    $storage = json_decode(file_get_contents('storage.json'), true);
    if (array_key_exists($key, $storage)) {
        return $storage[$key];
    }
    return null;
}

/**
 * Function to persist some data for the example
 * @param string $key
 * @param string $value
 */
function setValue($key, $value)
{
    $storage       = json_decode(file_get_contents('storage.json'), true);
    $storage[$key] = $value;
    file_put_contents('storage.json', json_encode($storage));
}

/**
 * Function to authorize with Exact, this redirects to Exact login promt and retrieves authorization code
 * to set up requests for oAuth tokens
 */
function authorize()
{
    $connection = new \Picqer\Financials\Exact\Connection();
    $connection->setRedirectUrl('replacedwithmydomain');
    $connection->setExactClientId('**************');
    $connection->setExactClientSecret('**********');
    $connection->setBaseUrl('https://start.exactonline.be');
    $connection->redirectForAuthorization();
}

/**
 * Callback function that sets values that expire and are refreshed by Connection.
 *
 * @param \Picqer\Financials\Exact\Connection $connection
 */
function tokenUpdateCallback(\Picqer\Financials\Exact\Connection $connection) {
    // Save the new tokens for next connections
    setValue('accesstoken', $connection->getAccessToken());
    setValue('refreshtoken', $connection->getRefreshToken());

    // Save expires time for next connections
    setValue('expires_in', $connection->getTokenExpires());
}

/**
 * Function to connect to Exact, this creates the client and automatically retrieves oAuth tokens if needed
 *
 * @return \Picqer\Financials\Exact\Connection
 * @throws Exception
 */
function connect()
{
    $connection = new \Picqer\Financials\Exact\Connection();
    $connection->setRedirectUrl('replacedwithmydomain');
    $connection->setExactClientId('******************');
    $connection->setExactClientSecret('*****************');
    $connection->setBaseUrl('https://start.exactonline.be');
	

    // Retrieves authorizationcode from database
    if (getValue('authorizationcode')) {
        $connection->setAuthorizationCode(getValue('authorizationcode'));
    }

    // Retrieves accesstoken from database
    if (getValue('accesstoken')) {
        $connection->setAccessToken(getValue('accesstoken'));
    }

    // Retrieves refreshtoken from database
    if (getValue('refreshtoken')) {
        $connection->setRefreshToken(getValue('refreshtoken'));
    }

    // Retrieves expires timestamp from database
    if (getValue('expires_in')) {
        $connection->setTokenExpires(getValue('expires_in'));
    }

    // Set callback to save newly generated tokens
    $connection->setTokenUpdateCallback('tokenUpdateCallback');

    // Make the client connect and exchange tokens
    try {
        $connection->connect();
    } catch (\Exception $e) {
        throw new Exception('Could not connect to Exact: ' . $e->getMessage());
    }

    return $connection;
}

// If authorization code is returned from Exact, save this to use for token request
if (isset($_GET['code']) && is_null(getValue('authorizationcode'))) {
    setValue('authorizationcode', $_GET['code']);
}

// If we do not have a authorization code, authorize first to setup tokens
if (getValue('authorizationcode') === null) {
    authorize();
}

// Create the Exact client

$connection = connect();

// Get the journals from our administration
try {
    $journals = new \Picqer\Financials\Exact\Journal($connection);
    $result   = $journals->get();
    foreach ($result as $journal) {
        echo 'Journal: ' . $journal->Description . '<br>';
    }
} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}`

**Comment by Teneobelgium** [comment]
Secondly, thet setBaseUrl does not seem to work as it is still redirecting to the .nl domain. But i manually replace the .nl for .be

**Comment by Teneobelgium** [comment]
I got it working !!! :-)

**Comment by casperbakker** [comment]
👍
