### ISSUE TITLE
Matching / Reconciling outstanding items

### ISSUE THREAD

**Issue by arendvw** [picqer/exact-php-client#127]
I'm looking for a way to match a sales entry (line?) to a general journey entry (line) in exactonline, but I can't seem to find the correct way on how to handle this using the exact online API?

The way it's handled now the two entries are matched pretty well in the "Outstanding items" tab in exactonline, but I can't seem to find a way to match or reconcile them automatically.

**Comment by thijssnowcountry** [comment]
Hi, Arendvw, do you mean 'afletteren'(in dutch)? This is only possible via the XML api.

**Comment by arendvw** [comment]
Sorry - I missed out on your answer. This is indeed what I mean. 

Great, thanks a lot - I now found out there's another API. For reference, it's [this XML api ](https://developers.exactonline.com/#XMLIntro.html%3FTocPath%3DExact%2520Online%2520XML%2520API%7C_____1) that thijsnowcountry is talking about.

**Comment by i6media** [comment]
"XML APIs will be discontinued soon; transition to REST APIs" - Email from Exact 27th of July 2026

AFAIK there's still no 'afletteren' endpoint for REST API?

**Comment by remkobrenters** [comment]
Yup. We were just talking about that here in the office as we use those endpoints for one specific but very heavy usage case. Would make a very big client very unhappy if it went away. We will ask for clarification about that one but recommend everyone to do so. Maybe it helps.

**Comment by i6media** [comment]
I created a Ticket in Exact Support, if I get a reply I'll post it here

**Comment by i6media** [comment]
Reactie van Exact:

V: Komt er een REST-equivalent voor MatchSets (programmatisch afletteren van openstaande posten), en wat is de verwachte planning? 
A: Er is nog geen planning voor een eventuele vervanging van het XML Topic matchsets. Ook wordt dit Topic nu nog niet uitgefaseerd

V: Blijft [url removed] met Topic=MatchSets gegarandeerd werken totdat dit REST-equivalent beschikbaar is? Is er al een (voorlopige) einddatum? 
A: Dit kan ik niet garanderen omdat er op dit moment nog geen einddatum is of een Rest api equivalent in de maak is.

V: Is er in de tussentijd een ondersteunde REST-route om een betaling automatisch af te letteren tegen een openstaande factuur, bijvoorbeeld via financialtransaction/BankEntryLines met het veld OurRef (factuurnummer)? Leidt dat tot automatische matching bij verwerking? 
A: Geen enkele boeking die via API wordt aangemaakt wordt automatisch afgeletterd. Dus helaas ook uw voorbeeld niet. De enige manier om af te letteren via API is via XML topic MatchSets.

"Helaas kan ik u dus niet meer duidelijkheid geven. Het enige dat ik kan doen is u aanraden om regelmatig de BreakingChanges pagina en de Releasenotes in de gaten te houden via onderstaande links. U kunt de linkjes gebruiken in een browser waarin uw Exact online niet open staat."

https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-breaking-changes-breakingchanges

**Comment by remkobrenters** [comment]
Think they had a morning of calming people down who were afraid the MatchSets would be gone as I got a similar confirmation this morning. I will leave this issue open but for now I think we are good and it will get an REST API equivalent before it is deleted.
