### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Rikgeffen** [picqer/exact-php-client#136]
How can i fix this?
Fatal error: Class 'Connection' not found in C:\xampp\htdocs\PhpPrograms\sdf.php on line 2
I dont want to search in the C:\xampp\htdocs\PhpPrograms\sdf.php only on my pc?

**Comment by stephangroen** [comment]
Did you install with Composer and have autoloading setup correctly?

**Comment by Rikgeffen** [comment]
Hi stephangroen,

Yes i did use Composer And i didn't use autoloading.

<?php
$connection = new \Picqer\Financials\Exact\Connection();
$connection->setRedirectUrl('http://localhost/EO/EOConnect.php');
$connection->setExactClientId('04cb4a38-ae4a-43f6-ac83-5de0f5fbe3ab');
$connection->setExactClientSecret('z5O6yWGiJiTh');
$connection->redirectForAuthorization();
?>

The first time i use it it work whitout any problem but now it always say.

Fatal error: Class 'Picqer\Financials\Exact\Connection' not found in C:\xampp\htdocs\EO5.3.0\EO5.3.0.php on line 2

I placed my picqer folder in C:Picqer\..
I placed my local server in  C:\xampp\htdocs\..

I use Neon eclipse PHP to write the code.

**Comment by Rikgeffen** [comment]
Now i try,

include('\Picqer\Financials\Exact\Connection.php');

and the first stap going well and than i need to go the next class and it repeat itself.

Fatal error: Class 'Windows\syswow64\vendor\picqer\exact' not found in C:\xampp\htdocs\EO\EOConnect.php on line 2

**Comment by stephangroen** [comment]
You have to setup autoloading correctly first. The include you're doing is incorrect. 

https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by Rikgeffen** [comment]
Thank you for all the help i get from you!
I did what you say and it work but this is my output:


Journal: Kasboek
Journal: Memoriaal
Journal: Activamutaties
Journal: Inkoopboek
Journal: Bank
Journal: Verkoopboek

I hope this is correct.
But now as soon as i add the item object :
$item = new Item($connection);
$item->Code = $productcode;
$item->CostPriceStandard = $costprice;
$item->Description = $name;
$item->IsSalesItem = true;
$item->SalesVatCode = 'VH';
$item->save();


// Retrieve an item
$item = new Item($connection);
$item->find(ID);

// List items
$item = new Item($connection);
$item->get();

// List items with filter (using a filter always returns a collection)
$item = new Item($connection);
$items = $item->filter("Code eq '$productcode'"); // Uses filters as described in Exact API docs (odata filters)

// Create new invoice with invoice lines
$items[] = [
		'Item'      => $itemId,
		'Quantity'  => $orderproduct['amount'],
		'UnitPrice' => $orderproduct['price']
];

$salesInvoice = new SalesInvoice($this->connection());
$salesInvoice->InvoiceTo = $customer_code;
$salesInvoice->OrderedBy = $customer_code;
$salesInvoice->YourRef = $orderId;
$salesInvoice->SalesInvoiceLines = $items;

It says : Fatal error: Class 'Item' not found in C:\xampp\htdocs\CM\newfile.php on line 115

**Comment by Rikgeffen** [comment]
And now i type this 

try {
	$Mes = new \Picqer\Financials\Exact\Me($connection);
	$result1   = $Mes->get();
	foreach ($result as $Mes) {
		echo 'Me: ' . $Mes->UserID. '<br>';
	}
} catch (\Exception $e1) {
	echo get_class($e1) . ' : ' . $e1->getMessage();
}

for only see my userID and i get this ERROR;

Notice: Undefined index: get in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me: 

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me: 

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me: 

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me: 

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me: 

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
 Me:

**Comment by casperbakker** [comment]
You cannot use the same variable `$Mes` twice.

But these issues are just basic PHP and have nothing to do with this package. So please ask them at StackOverflow for example.
