### ISSUE TITLE
HowTo: Use multiple filters

### ISSUE THREAD

**Issue by davidvandertuijn** [picqer/exact-php-client#142]
What is the syntax to use multiple filters? I try comma-seperated but this result in a Syntax error.

```
$oResults = $oTransactionLine->filter("JournalCode eq '60'", '', 'EntryID, JournalCode, GLAccountDescription, Date'); // Single filter works!
$oResults = $oTransactionLine->filter("Date gt datetime'2018-01-01'", '', 'EntryID, JournalCode, GLAccountDescription, Date'); // Single filter works!
$oResults = $oTransactionLine->filter("JournalCode eq '60', Date gt datetime'2018-01-01'", '', 'EntryID, Date'); // Error 400: Syntax error at position 24.
```

**Comment by cyrnetix** [comment]
You should be able to concat the filters with 'and' and 'or' like sql. Example: "JournalCode eq '60' and Date gt datetime'2018-01-01'"

**Comment by davidvandertuijn** [comment]
Thanks, i also just found documentation about filters:
http://www.odata.org/documentation/odata-version-2-0/uri-conventions/
