### ISSUE TITLE
How to secure webhook

### ISSUE THREAD

**Issue by justijndepover** [picqer/exact-php-client#146]
I'm making an application which has a user database. So I store my credentials in my User Model.

- accessToken
- refreshToken
- tokenExpires
- authorisationCode

I'm using webhooks to notify my website if an Invoice has been created. But based on the content I get in my webhook i'm not sure what user to notify.

My webhook callback url is `/webhooks`. 

The docs say i'll get something like this: 

```
{
Content:{
	Topic: 'FinancialTransactions',
	Action : UPDATE,
	Division : {division},
	Key : 'DD0273AA-67BC-410B-9321-F27C40AF22A9',
	Endpoint:…/api/v1/{division}/financialtransaction/Transactions(guid'{DD0273AA-67BC-410B-9321-F27C40AF22A9}')
},
HashCode:‘xxxxxxxxxxxxxxxxx’
}
```

Should I store the division in my user object?

**Comment by hajcu** [comment]
No, this is information that new transaction entry is made. So now to check to which account invoice is made you need to parse this response, and run

```php
$request = new Picqer\Financials\Exact\Transaction($connection);
$transaction = $request->find($id);
```

$id =['Content']['Key'] from your webhook callback

So:
- Division - administration in exact, this is information in wchich company in exactonline system invocie was made
- Topic - webhook was registered to this topic
- Action - UPDATE or DELETE, when DELETE you only remove invoice from your internal database, invoice with this key in exactonline system no longer exist
- HashCode - checking token, security reason

**Comment by justijndepover** [comment]
I cannot access the `$connection` variable since there is no logged in user if they access my webhook. 

I currently store the division on the user object so I can match it with the one in the request.
