### ISSUE TITLE
CashEntryLine error

### ISSUE THREAD

**Issue by justijndepover** [picqer/exact-php-client#148]
The CashEntryLine model contains a wrong url

It should be 

```php
protected $url = 'financialtransaction/CashEntryLines';
```

instead of 

```php
protected $url = 'financialtransaction/CashEntryLine';
```

**Comment by justijndepover** [comment]
I have also noticed that your `SalesInvoice` object is missing the `PaymentReference` property

**Comment by stephangroen** [comment]
Feel free to submit a PR, I might not get to this very soon.
