### ISSUE TITLE
API does not return any Journals

### ISSUE THREAD

**Issue by justijndepover** [picqer/exact-php-client#155]
We use this plugin to manage invoices for our customers.

Something weird is going on but i'm guessing it is an api related issue:

At random moments we are unable to get Journals from the API. If this occurs we cannot retrieve any Journal objects (empty array), but GLAccounts work as expected.

Whenever this occurs we have to reset the parameters

**Comment by stephangroen** [comment]
If the API does not return any journals, isn't that an issue for Exact?
