### ISSUE TITLE
Find doesn't work on account + webhook example

### ISSUE THREAD

**Issue by Threesa** [picqer/exact-php-client#156]
Hey,

When using find with an ID on an account my object remains empty.
However if I use filter with the same string as used in the Findable class I do get a result... Albeit in a resultset (which is logical in that case).

Furthermore: I'm having trouble implementing webhooks. No decent documentation or examples available.

I'd like a simple setup. I have a webpage showing some clients (Exact Online demo).
If one of the users gets updated somewhere I want the open webpage to get the notification and reload.

How can I do that please?

**Comment by tomcoonen** [comment]
@Threesa please provide an example of what you're doing

**Comment by Threesa** [comment]
`<?php

    require 'vendor/autoload.php';
    
    function getValue($key)
    {
        $storage = json_decode(file_get_contents('storage.json'), true);
        if (array_key_exists($key, $storage)) {
            return $storage[$key];
        }
        return null;
    }
    
    function setValue($key, $value)
    {
        $storage       = json_decode(file_get_contents('storage.json'), true);
        $storage[$key] = $value;
        file_put_contents('storage.json', json_encode($storage));
    }
    
    function authorize()
    {
        $connection = new \Picqer\Financials\Exact\Connection();
        $connection->setRedirectUrl('http://www.mysite.com/titeca/index.php');
        $connection->setExactClientId('{client_id}');
        $connection->setExactClientSecret('{client_secret}');
        $connection->redirectForAuthorization();
    }
    
    function connect()
    {
        $connection = new \Picqer\Financials\Exact\Connection();
        $connection->setRedirectUrl('http://www.mysite.com/titeca/index.php');
        $connection->setExactClientId('{client_id}');
        $connection->setExactClientSecret('{client_secret}');
    
        if (getValue('authorizationcode')) // Retrieves authorizationcode from database
        {
            $connection->setAuthorizationCode(getValue('authorizationcode'));
        }
    
        if (getValue('accesstoken')) // Retrieves accesstoken from database
        {
            $connection->setAccessToken(getValue('accesstoken'));
        }
    
        if (getValue('refreshtoken')) // Retrieves refreshtoken from database
        {
            $connection->setRefreshToken(getValue('refreshtoken'));
        }
    
        if (getValue('expires_in')) // Retrieves expires from database
        {
            $connection->setTokenExpires(getValue('expires_in'));
        }
    
        // Make the client connect and exchange tokens
        try {
            $connection->connect();
        } catch (\Exception $e) {
            throw new Exception('Could not connect to Exact: ' . $e->getMessage());
        }
    
        // Save the new tokens for next connections
        setValue('accesstoken', $connection->getAccessToken());
        setValue('refreshtoken', $connection->getRefreshToken());
        setValue('expires_in', $connection->getTokenExpires());
    
        return $connection;
    }
    
    if (isset($_GET['code']) && is_null(getValue('authorizationcode'))) {
        setValue('authorizationcode', $_GET['code']);
    }
    
    $connection = connect();
?>

<!DOCTYPE html>
<html lang="nl">
<head>
    <title>Exact Online</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1" />
    <meta name="description" content="Exact Online" />
    <meta name="keywords" content="exact online, sdk, rest, api" />
    <meta name="author" content="Threesa" />
    
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        if(typeof String.prototype.trim !== 'function') {
            String.prototype.trim = function() {
                return this.replace(/^\s+|\s+$/g, ''); 
            }
        }
    </script>
</head>
<body>

    <?php
        
        if(!empty($_POST) && isset($_POST["action"]) && $_POST["action"] == "update"){
            EXTRACT($_POST);
            
            if(isset($eo_accounts) && is_array($eo_accounts) && count($eo_accounts) > 0){
                foreach($eo_accounts as $eo_account_id){
                    $these_accounts = new \Picqer\Financials\Exact\Account($connection);
                    //$this_account->find($eo_account_id);
                    $result = $these_accounts->filter("ID eq guid'$eo_account_id'");
                    
                    foreach($result as $this_account){
                        if(isset($status[$eo_account_id])){
                            $this_account->Status = $status[$eo_account_id];
                        }
                        
                        $this_account->IsSupplier = (isset($is_supplier[$eo_account_id]) && $is_supplier[$eo_account_id] == 1 ? 1 : 0);
                        $this_account->IsAccountant = (isset($is_accountant[$eo_account_id]) && $is_accountant[$eo_account_id] == 1 ? 1 : 0);
                        $this_account->IsReseller = (isset($is_reseller[$eo_account_id]) && $is_reseller[$eo_account_id] == 1 ? 1 : 0);
                        $this_account->IsCompetitor = (isset($is_competitor[$eo_account_id]) && $is_competitor[$eo_account_id] == 1 ? 1 : 0);
                        
                        $this_account->save();
                    }
                }
                
                echo "<div style='text-align: center; font-weight: bold; color: red;'>Changes have been saved!</div>\n";
            }
        }
        
        echo "<form method='POST' action='" . $_SERVER["PHP_SELF"] . "'>\n";
        echo "  <input type='hidden' name='action' value='update' />\n";
        
        try {
            $accounts = new \Picqer\Financials\Exact\Account($connection);
            $result = $accounts->filter("Status eq 'C'");
            echo "<ul>\n";
            foreach($result as $account){
                    //echo "<pre>"; print_r($account); echo "</pre>\n";
    
                    echo "<input type='hidden' name='eo_accounts[]' value='" . $account->ID . "' />\n";
                    echo "<li><b>" . $account->Name . "</b>";
                    
                    if(trim($account->AddressLine1) != ""){ echo "<br />" . $account->AddressLine1; }
                    if(trim($account->Postcode) != "" || trim($account->City) != ""){ echo "<br />" . $account->Postcode . " " . $account->City; }
                    if(trim($account->StateName) != ""){ echo "<br />" . $account->StateName; }
                    if(trim($account->CountryName) != ""){ echo "<br />" . $account->CountryName; }
                    
                    echo "<table>\n";
                    echo "<tr>\n";
                    echo "<td>\n";
                    echo "  <select name='status[" . $account->ID . "]'>\n";
                    echo "      <option value='A' " . ($account->Status == "A" ? "selected='selected'" : "") . ">None</option>\n";
                    echo "      <option value='C' " . ($account->Status == "C" ? "selected='selected'" : "") . ">Client</option>\n";
                    echo "      <option value='P' " . ($account->Status == "P" ? "selected='selected'" : "") . ">Prospect</option>\n";
                    echo "      <option value='S' " . ($account->Status == "S" ? "selected='selected'" : "") . ">Suspect</option>\n";
                    echo "  </select>\n";
                    echo "</td>\n";
                    echo "<td><input type='checkbox' name='is_supplier[" . $account->ID . "]' value='1' " . ($account->IsSupplier ? "checked='checked'" : "") . " /> Supplier</td>\n";
                    echo "<td><input type='checkbox' name='is_accountant[" . $account->ID . "]' value='1' " . ($account->IsAccountant ? "checked='checked'" : "") . " /> Accountant</td>\n";
                    echo "<td><input type='checkbox' name='is_reseller[" . $account->ID . "]' value='1' " . ($account->IsReseller ? "checked='checked'" : "") . " /> Dealer</td>\n";
                    echo "<td><input type='checkbox' name='is_competitor[" . $account->ID . "]' value='1' " . ($account->IsCompetitor ? "checked='checked'" : "") . " /> Competitor</td>\n";
                    echo "</tr>\n";
                    echo "</table>\n";
                    
                    echo "<br /><br /></li>\n";
            }
            echo "</ul>\n";
        } catch (\Exception $e) {
            echo get_class($e) . ' : ' . $e->getMessage();
        }
        echo "<div style='text-align: center;'><input type='submit' value='Save' style='font-weight: bold;' /></div>\n";
        echo "</form>\n"
    ?>
</body>
</html>`

**Comment by GewoonRoy** [comment]
For Webhooks you can start the research with the following links:
https://developers.exactonline.com/#WebhooksTut.htm?Highlight=webhook
https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/WebhookSubscription.php

It's pretty straight forward creating a Webhook in Exact online. Give up your CallbackUrl (keep in mind that your redirect uri is within the webhook CallbackUrl.). Add `Accounts` to the Topic field and save the Webhook.

When an Account in Exact online is changed it will call the `CallbackUrl` with a payload. You can listen to the that CallbackUrl to pick up the payload and do anything you want your webpage to do. To let the browser remotely refresh you need to take a look at Javascript or Sockets.
