### ISSUE TITLE
Item update fails: Error 500: Verplicht: Serie

### ISSUE THREAD

**Issue by tomcoonen** [picqer/exact-php-client#161]
Since this morning we get errors from Exact when updating an Item (Picqer\Financials\Exact\Item->update()):
```
Picqer\Financials\Exact\ApiException: Error 500: Verplicht: Serie
```

Seems like they made changes since our application didn't change, a support request is already open at Exact but that might take a while I guess.

Anybody here has any idea what the 'Serie' refers to regarding an 'Item' or 'ItemGroup'?
The documentation doesn't mention it anyways: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsItems .

**Comment by stephangroen** [comment]
E_NOCLUE

Please keep us informed on the result of your support request :)

**Comment by WebDevTmas** [comment]
We made the same support request to exact, they didn't say a time it would be fixed\ready with more information.
Seems like it should be an easy fix on their part, either the documentation or the 'Serie requirement'.

**Comment by tomcoonen** [comment]
I guess they deployed something new yesterday and broke something, I don't care about the fix either but their communication is terrible at the moment.

**Comment by tomcoonen** [comment]
@stephangroen issue found after return call of an Exact developer, can you accept my PR in a few minutes please so we don't have to wait for a fix from Exact? 😄

**Comment by stephangroen** [comment]
Monitoring :)

**Comment by tomcoonen** [comment]
Here we go: https://github.com/picqer/exact-php-client/pull/163

**Comment by stephangroen** [comment]
https://github.com/picqer/exact-php-client/releases/tag/v3.7.0

**Comment by tomcoonen** [comment]
Teamwork 💪 

Could you kick packagist? Seems to be lagging.. https://packagist.org/packages/picqer/exact-php-client

**Comment by stephangroen** [comment]
@tomcoonen Done!
