### ISSUE TITLE
Picqer\Financials\Exact\ApiException : Error 403: Forbidden when salesInvoice Create

### ISSUE THREAD

**Issue by Grazulex** [picqer/exact-php-client#166]
Hello,
I try your class like the example file.
I can create the account and the item but when I try to create the saleInvoice I have always a Picqer\Financials\Exact\ApiException : Error 403: Forbidden error...
Can somebody help me ?

Thanks

**Comment by GewoonRoy** [comment]
Looks like it's Forbidden toe create the SalesInvoice. Are you using an user with Sales rights?
