### ISSUE TITLE
Connection class not open for extension

### ISSUE THREAD

**Issue by MartijnZuijd** [picqer/exact-php-client#168]
Currently the `exact-php-client/src/Picqer/Financials/Exact/Connection.php` contains a lot of private methods that handle, for instance, the actual refresh logic of the OAuth token.
I would like to suggest to make these functions protected so the SDK becomes more extendable. 
As of now I have to copy portions of the Connection class to extend certain logic.

**Comment by stephangroen** [comment]
That's fine by me, submit a PR if you like.
