### ISSUE TITLE
SalesInvoice - InvoiceNumber is NULL on save()

### ISSUE THREAD

**Issue by sefaYavuz** [picqer/exact-php-client#171]
I've created a sales invoice. Like so:

```
$salesInvoice = new \Picqer\Financials\Exact\SalesInvoice($connection);
$salesInvoice->InvoiceTo = $exactCustomer->exact_id;
$salesInvoice->OrderedBy = $exactCustomer->exact_id;
$salesInvoice->OrderNumber = $invoice->po_number;
$salesInvoice->Description = $invoice->description;
$salesInvoice->SalesInvoiceLines = $itemsArr;
$salesInvoice->Journal = 70;
$salesInvoice->Type = 8020;
$salesInvoice->save();
```

But when I look in to Exact, the field for the invoice number is empty?

**Comment by sefaYavuz** [comment]
No answer to this problem?

**Comment by stephangroen** [comment]
Code seems correct to me. You could get the JSON that is being sent to Exact and contact them with the details of the request you are doing.

**Comment by sefaYavuz** [comment]
Nevermind the Exact API says the following: 

> Assigned at entry or at printing depending on setting.

The latter was the problem in my case.
