### ISSUE TITLE
Error 500: Ongeldig: Factuur voor (Type)

### ISSUE THREAD

**Issue by blyleven** [picqer/exact-php-client#172]
All of a sudden I'm receiving this error when creating an invoice. Anybody else got this error? I'm actually sending the Type 8020 with the request which should be ok as it's an sales invoice...

**Comment by stephangroen** [comment]
Seems to be working for me. Haven't heard anything of our clients either.

**Comment by Teneobelgium** [comment]
I've had this in the past when I was linking an invoice to a relation that did not have the "customer" status , only "supplier" status. You might want to check the status of the relation to which you are linking the SalesInvoice.

**Comment by blyleven** [comment]
@Teneobelgium thanks for your input. It seems like that was the problem. All of a sudden the possibility of selecting which status a relation should have was hidden in Exact.
