### ISSUE TITLE
SalesInvoice remains open

### ISSUE THREAD

**Issue by Teneobelgium** [picqer/exact-php-client#176]
When I send our SalesInvoices from our backoffice to Exact they appear in the SalesInvoice list as "Te verwerk"n so "unprocessed". When I then let Exact process them all the Invoicenumbers are wrong.

How do I link an invoice with the API so that it immediatly is booked/processed/verwerkt ?

**Comment by GewoonRoy** [comment]
Have you tried using the PrintedSalesInvoice? This will try to process the 'SalesInvoice' so GeneralJournalEntries can be created.

**Comment by Teneobelgium** [comment]
Hi GewoonRoy

Great! That worked perfect. Onyl thing to figure out now is how to retain the original invoicenumber.
When printing an invoice that I created with InvoiceNumber = 20170908 it saves the invoice with the internal numbering from Exact.

**Comment by GewoonRoy** [comment]
@Teneobelgium I don't think it's possible to overrule the InvoiceNumber field of Exact Online. Maybe you can use the field `YourRef` of the SalesInvoice or the field `ExtraText` of the PrintedSalesInvoice?

[Exact online API sources](https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10)

**Comment by Teneobelgium** [comment]
You are correct, it was not. I decided to rewrite the full project and used "SalesEntry" and "SalesEntryLines" endpoints instead. Now document numbering is working perfect.
I will open a new issue for my last remaining question at this point.

PS : Just wanted to say thanks for writing this wrapper. It saved me a LOT of time !! Good job.

**Comment by michielverkoijen** [comment]
I made some improvements to the PrintedSalesInvoice class and added some examples in the readme. This will return the saved information to the class upon saving. Will push when my previous pull request has been approved hopefully in a few days.
