### ISSUE TITLE
No ID filled in PurchaseOrderLine

### ISSUE THREAD

**Issue by GewoonRoy** [picqer/exact-php-client#177]
Hi,

I am using the object PurchaseOrderLine and i am trying to retrieve the ID property of the PurchaseOrderLine instance. I found out that it wasn't returned to me which mostly would be the case if Exact Online didn't return it or the field isn't specified in the PurchaseOrderLine instance. Both of the theories would be kind of weird so i looked a little further.

There is a space on the end of ID within the PurchaseOrderLine in the $fillable list which creates this little bug.

**Comment by stephangroen** [comment]
Thanks

Fixed in 5d2ec686b5e7f78e2557536f7941991ce31fc46e
