### ISSUE TITLE
DocumentAttachments

### ISSUE THREAD

**Issue by Teneobelgium** [picqer/exact-php-client#178]
I'm kind of stuck. I can create a Document without a problem via \Picqer\Financials\Exact\Document but now I need to attach a PDF file to it ...
The description has the field "Attachment" which expects a "binary" value ??
I have absolutely no idea how to attach a PDF , and no matter what I try as "Attachment" value I always get:

**Error 400: Error processing request stream. Error encountered in converting the value from request payload for property 'Attachment' to type 'Byte[]'**

Any advise on how to add a PDF file ?

**Comment by Teneobelgium** [comment]
**Solved! The variable has to be base64 encoded.**

$contents = file_get_contents('test.pdf');
$contents = base64_encode($contents);
$attachment = new \Picqer\Financials\Exact\DocumentAttachment($connection);
$attachment->Document = $documentid;
$attachment->Attachment = $contents;
$attachment->FileName = "test.pdf";
$attachment->save();
`

**Comment by erikdep** [comment]
@Teneobelgium  Can you please show how you create a document and obtain your $documentid ?

**Comment by Teneobelgium** [comment]
@erikdep  yes, please find code below.

`
$document = new \Picqer\Financials\Exact\Document($connection);
$document->Account = $uniqueid;
$document->FinancialTransactionEntryID = $entryID;
$document->DocumentDate = $invoicedate;
$document->Subject = "my subject";
$document->Type="10";
$document->Category="mycategoryid";
$document->save();
$documentid = $document->ID;
`

$documentid contains the documentid.

**Comment by tkslabz** [comment]
Hello Teneobelgium,
I am facing the same error when i creating the SalesInvoice. I think the error occur for InvoiceTo and OrderBy parameters. In which format i need to send the ids? Could you pleas help to sortout the error. 
Thanks
