### ISSUE TITLE
SalesEntryLines end point pointing to Invoices

### ISSUE THREAD

**Issue by vgsglobal** [picqer/exact-php-client#20]
The SalesEntryLines end point is not correct. 

Check this: https://start.exactonline.co.uk/docs/HlpRestAPIResourcesDetails.aspx?name=SalesEntrySalesEntryLines

protected $url = 'salesentry/SalesEntryLines';

instead of:

protected $url = 'salesinvoice/SalesInvoiceLines';

**Comment by stephangroen** [comment]
Thanks @vgsglobal 

Fixed and tagged new versions.
