### ISSUE TITLE
New tag missing, can't get update by composer

### ISSUE THREAD

**Issue by danielvdbilt** [picqer/exact-php-client#204]
Hi,

I see you've added some models like: https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/Layout.php.

However I can't get them in my project with composer. Can it be that you have to create a new tag number of am I doing something wrong?

Thank you!

**Comment by stephangroen** [comment]
That's right. There are some other PR's I'd like to merge first, before doing a new release. You can however get the current master commit if you'd like. See: https://stackoverflow.com/questions/21314381/how-to-correctly-require-a-specific-commit-in-composer-so-that-it-would-be-avail

**Comment by danielb1987** [comment]
Thanks for your quick reply! I will checkout the master for now and change it back when you do a new release.

Have a nice day!
