### ISSUE TITLE
/crm/Contacts overlapping fields

### ISSUE THREAD

**Issue by remkobrenters** [picqer/exact-php-client#206]
We noticed that we were not able to update the fields for mobile phone and email. Together with Exact support we figured out that the issues lies in the fact that Exact overwrites fields if empty equivalents are provided. For example:

If you try to save BusinessEmail with an value of 'test@test.com' but do not set the field Email the latter will overwrite the first one. As the default behavior of the storable is to take all existing values and fill them up with the submitted values the Email field will remain empty. 

A quick fix would be to overwrite values for Email with BusinessEmail if provided, Mobile with BusinessMobile and Phone with BusinessPhone. I wonder if this is something worth mentioning in the comments for the Contact.php model or in usage instructions. Can imagine it will take someone else quit a while to figure out why the values are not updating (especially since it is not an error so the Exact API will tell you all went OK). 

In addition: If I lookup the fields used in Exact user interface it seems only BusinessMobile, BusinessPhone and BusinessEmail are used. All other fields (including the ..PhoneExtension fields) seem to be phased out (or used in some other context that I am overlooking).

**Comment by stephangroen** [comment]
> I wonder if this is something worth mentioning in the comments for the Contact.php model or in usage instructions.

We could at least put it in the comments so it's noted somewhere.
