### ISSUE TITLE
Exception after updating account

### ISSUE THREAD

**Issue by blyleven** [picqer/exact-php-client#21]
Hallo Stephan, 

Bedankt voor deze code, het heeft mij een heel stuk op weg geholpen. Ik loop alleen tegen een ding aan bij het updaten en verwijderen van een record. 

De wijzigingen worden wel doorgevoerd binnen Exact, maar na het verwerken van mijn opdracht krijg ik deze foutmelding. 

ApiException in Connection.php line 498: array_key_exists() expects parameter 2 to be array, null given

Heb jij enig idee wat hier het probleem zou kunnen zijn?

Vriendelijke groet, 

Michael

**Comment by stephangroen** [comment]
Hi Michael,

Welke versie gebruik je? Dit is even een fout geweest, maar moet in de laatste versie verholpen zijn door deze commit: e3b169a0edaa990b806c9bd29bb1b0898c08c491

**Comment by blyleven** [comment]
Hi Stephan, 

I was using yesterdays version (2.1.1), just updated to the version of this morning (2.1.2) but still the error is shown.

When I outcomment this line in, for example, function put in Connection.php:
return $this->parseResponse($response);
the error (ofcourse) is gone. 

When I activate it again and trackdown function parseResponce, I see the script is actually generating a nice output for return $json['d']['results'][0]; but after that, there's where the error comes in.

**Comment by stephangroen** [comment]
@blyleven Thanks for the info! I've released v2.1.3 with a fix for this.

**Comment by blyleven** [comment]
Thank you so much! Works like a charm!
