### ISSUE TITLE
Can't get output of "AddressLine, City, FaxNumber, MiddelInitial, Note, State, ZipCode"

### ISSUE THREAD

**Issue by Rikgeffen** [picqer/exact-php-client#211]
I tryed to get data of "Contact" but i can't get these tags "AddressLine, City, FaxNumber, MiddelInitial, Note, State, ZipCode" when i looked in ExactOnline i saw that under "Contact" Voornaam, Tussenvoegsel, Achternaam, Functienaam, Telefoon, Mobiel, E-mail and these are the thing I only get a output of (if its filled in). then I looked further and I saw "Relatie" over here are the parts i want but can't call it. How can i fix this?

**Comment by GewoonRoy** [comment]
@Rikgeffen `Relatie` is known as `Account` within Exact. An `Account` can have 1 `MainContact` and multiple contacts for additional data. 

Can you try to get data from `Account` instead?
