### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by vengo071** [picqer/exact-php-client#212]
Could someone help me to setup a proper filter? Cannot find anything in manual or webpostings.

I use following example code:
`            $journals = new \Picqer\Financials\Exact\Account($connection);
            $journals->filter("Postcode eq '2417'"); 
            $result   = $journals->get();
            print_r($result);`

This returns all data, non filtered. 
Is it also possible to sort output alphabetically?

Thanks in advance!

**Comment by stephangroen** [comment]
The filter() call already gets results from the API. Do not add a ->get(); call after that.
