### ISSUE TITLE
Bugs in usage with multiple divisions

### ISSUE THREAD

**Issue by wouterraateland** [picqer/exact-php-client#214]
When using this client with an account that has multiple divisions, the division that is used most recently is automatically selected and used by this client.

This is good default behaviour, but it can lead to hard-to-find bugs. Therefor I think that there should be a way to select a division manually.

**Comment by stephangroen** [comment]
There is a way do set a division manually :)

```php
// Optionally set administration, otherwise use the current administration of the user
$connection->setDivision(123456);
```

**Comment by wouterraateland** [comment]
Sorry, missed that!

**Comment by stephangroen** [comment]
Np :)
