### ISSUE TITLE
Get results as multiple 'resultsets'.

### ISSUE THREAD

**Issue by mbm-peter** [picqer/exact-php-client#215]
I'm interested in having an API that works like this: it's like a two-stage resultset, that doesn't download all results at once. It results in batches. This is more efficient in terms of memory requirements as not all items have to be kept in memory at once. I will implement this and hope that it could be merged, when I provide it.

    $resultset = (new Item($connection))->getResultSet();

    while ($resultset->hasMore()) {
        $results = $resultset->next();
        foreach ($resultset as $item) { 
              // use $item.
        }
    }

**Comment by GewoonRoy** [comment]
@mbm-peter Doesn't the api already use this kind of method to get results? Exact online has a limit of 60 results on a request which means the api will create multiple requests with a `->nextUrl` method in the `Findable`

**Comment by mbm-peter** [comment]
The difference is that this new API doesn't load all (could be thousands) objects in one array, but gets a new array of 60 everytime. That way there is much less memory needed to load a big list of items.
