### ISSUE TITLE
Get all products but with a 'select'

### ISSUE THREAD

**Issue by versdivers** [picqer/exact-php-client#217]
Hello

I would like to get all products but only the field that i need to save space in the request. (Exact has a limit on how big this can be).

Anyone any idea?

`->get(array('select' => 'Description'))
`
Something like this?

**Comment by GewoonRoy** [comment]
@versdivers try the following:
`->filter('', '', 'Description');`

**Comment by versdivers** [comment]
I did it with  ->get(array('$select' => 'Description'))
