### ISSUE TITLE
All results are protected?

### ISSUE THREAD

**Issue by Silassiai** [picqer/exact-php-client#218]
Hi,

Think this is a stupid question but can't find the awnser.
All the results i get are protected, i want to have access to a specific property, but i get null.

example >

call: 

$contacts = new \Picqer\Financials\Exact\Contact($connection);
$first_contact = current($contacts->filter('', '', '', ['$top'=> 1]));
var_dump($first_contact);

result: 

object(Picqer\Financials\Exact\Contact)#49 (6) {
  ["fillable":protected]=>
  array(64) {
    [0]=>
    string(2) "ID"
    [1]=>
    string(7) "Account"
    [2]=>
    string(17) "AccountIsCustomer"

How do i access the $fillable array from the Contacts class?

**Comment by stephangroen** [comment]
You can access a property by using the magic getter:

`$first_contact->Account`

**Comment by Silassiai** [comment]
Yess and how do i get all the available properties?

**Comment by stephangroen** [comment]
You mean like this?

```php
$first_contact->attributes()
```
