### ISSUE TITLE
Count result odata not working?

### ISSUE THREAD

**Issue by Silassiai** [picqer/exact-php-client#219]
Why is this wrong?
$contacts = new ExactContact($connection);
$contacts = $contacts->filter('', '', '', ['$count' => true]);

result:
Error 400: The query parameter '$count' begins with a system-reserved '$' character but is not recognized.

**Comment by DaveyGiesen** [comment]
Because it is not a filtered result. 

http://www.odata.org/getting-started/basic-tutorial/#count

The request should looks like this:
```
https://start.exactonline.nl/api/v1/{division_id}/crm/Contacts/$count
```

**Comment by Mathijs-Zuiderlicht** [comment]
What would be a working code example? 
This code also doesn't work:

`        
$account = new \Picqer\Financials\Exact\Account($connection);
$account = $account->get(['$count' => true]);
`

Whenever I use the $count parameter, I get the same error as mentioned above.
