### ISSUE TITLE
Json output

### ISSUE THREAD

**Issue by bertjuuhh** [picqer/exact-php-client#22]
Hi, 
I'm using your library for a while now and i really like it. But i have a question about the output of a save action.
If i make a save action i get output that is protected so i can't really use it.
Is there a way to just get the json output from exact so i can use that for more actions?

regards,
Egbert

Ps, i wrote this in english but i am dutch, so if its more convenient to answer in dutch thats possible ;)

**Comment by stephangroen** [comment]
Hi @bertjuuhh,

Thank you :) You can assign the new object to a variable by using `$item = $item->save();` after which `$item` is filled with the new data. After that `$item->json()` will give you a json representation of the object.

Is this enough of the json you need? If not, please let me know what exactly you need from the raw json from Exact.

**Comment by bertjuuhh** [comment]
Hi @stephangroen,

Thats it!! 
Thank you very much for the reply :)

Regards
Egbert

**Comment by stephangroen** [comment]
Great!

**Comment by bertjuuhh** [comment]
Hi @stephangroen,

is the same trick supposed to work for a the get function as well?
So 
$result = $item->get();
$result-json().

regards,
Egbert

**Comment by stephangroen** [comment]
You can always use json() method on an object that extends the Model (so all entities support it).

**Comment by bertjuuhh** [comment]
Alright, maybe i'm using it wrong then. Because if I use it like this :
$vatCode = new \Picqer\Financials\Exact\VatCode($connection);        
$result = $vatCode->get();
$resultjson = $result->json();

I get the error : Call to a member function json() on a non-object.

I use it the exact same way with the save function.
Regards
Egbert

**Comment by stephangroen** [comment]
It seems you are not getting a valid result from `$vatCode->get();`. You might want to check into that first. `var_dump($result)`.

**Comment by bertjuuhh** [comment]
Yeah i have results, i checked it on another function aswell. The same error as result.
The result are filled with a lot of stuff as well, but it starts like this : 
[0]=>
  object(Picqer\Financials\Exact\VatCode)#38 (5) {
    ["fillable":protected]=>
    array(40) {

I get result now via another way, but thats timeconsuming.

**Comment by stephangroen** [comment]
Whoops, I see the problem now. Since you are doing a get call (retrieve all vatcodes), you will get an array of VatCode objects. So $result[0]->json(); will give a JSON representation of the first object in the array.

**Comment by bertjuuhh** [comment]
Ah, that explain's it, thank you :)
