### ISSUE TITLE
SalesInvoice Remaining amount

### ISSUE THREAD

**Issue by Pirabarlen-Cheenaramen** [picqer/exact-php-client#223]
Hi, not really an issue, but rather a question, how does one gets the associated remainder from a salesinvoice? There seems to be no remainder fields, how do you guys know that an invoice was actually paid and if there is any remainder to be paid?

**Comment by versdivers** [comment]
Are you syncing payments to Exact or from Exact?

**Comment by thijswiersema** [comment]
The easiest way is with the ReceivableList from Exact:
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadFinancialReceivablesList

You will get a list of all the (printed) invoices in Exact that are 'unpaid'. The amount field is the unpaid amount of the invoice.

**Comment by Pirabarlen-Cheenaramen** [comment]
Thanks @thijswiersema , I used receivableList and it worked great!
@versdivers , no was just reading the payments to match locally.
