### ISSUE TITLE
Division using hrm/divisions endpoint

### ISSUE THREAD

**Issue by alexjeen** [picqer/exact-php-client#229]
The Division model is now using /hrm/Divisions as endpoint.

This causes incomplete Division lists because it depends on which administration you have selected in Exact Online.

If you change it to system/Divisions all is well.

**Comment by DannyvdSluijs** [comment]
@alexjeen it seems you would need to use the SystemDivision class instead of the Division class. Also notice both of them are a different model.

```bash
$ diff System.txt Hrm.txt -u
--- System.txt	2018-08-21 20:58:02.000000000 +0200
+++ Hrm.txt	2018-08-21 20:59:15.000000000 +0200
@@ -1,53 +1,29 @@
 Code
-AddressLine1
-AddressLine2
-AddressLine3
 BlockingStatus
-BusinessTypeCode
-BusinessTypeDescription
-ChamberOfCommerceEstablishment
-ChamberOfCommerceNumber
-City
 Class_01
 Class_02
 Class_03
 Class_04
 Class_05
-CompanySizeCode
-CompanySizeDescription
 Country
+CountryDescription
 Created
 Creator
 CreatorFullName
 Currency
-Current
+CurrencyDescription
 Customer
 CustomerCode
 CustomerName
-DatevAccountantNumber
-DatevClientNumber
 Description
-Email
-Fax
-Hid
-IsMainDivision
-Legislation
+HID
+Main
 Modified
 Modifier
 ModifierFullName
-Phone
-Postcode
-SbiCode
-SbiDescription
-SectorCode
-SectorDescription
-ShareCapital
 SiretNumber
 StartDate
-State
 Status
-SubsectorCode
-SubsectorDescription
 TaxOfficeNumber
 TaxReferenceNumber
 VATNumber
```

**Comment by alexjeen** [comment]
I know, we already do 👍 

The difference between the endpoints is subtle but important:

/hrm/Divisions: Depends on what division you have selected in Exact, shows a shortlist 
/system/Divisions: Shows you all divisions you have access to (it's like the full list in Exact Online)
