### ISSUE TITLE
Question: Logging

### ISSUE THREAD

**Issue by DaveyGiesen** [picqer/exact-php-client#238]
Exact Online has announced to have API limits on their REST API.
What is the best way to log all outgoing API calls to Exact Online?
Anyone has some ideas?

**Comment by tomcoonen** [comment]
I had the same issue, I'm incrementing a Redis counter per call now.
At some time interval I store this to the database to create a history.

**Comment by meijdenmedia** [comment]
At which point did you increment the count? How should I implement this?
