### ISSUE TITLE
Upgrading from 3.9.0 to 3.12.0 causes curlError in DocumentAttachment class

### ISSUE THREAD

**Issue by alexjeen** [picqer/exact-php-client#244]
We have some code that downloads a proposal from Exact Online. After upgrading we get the following stack trace back when downloading:

    Feb 20 13:40:03 vps.dataswitcher.com app.log: 2018-02-20 13:40:03 [95.97.42.86][-][-][error][GuzzleHttp\Exception\ConnectException] GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: documents; Name or service not known (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/databrydge/application/releases/20180219154942/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

Seems like it's missing the base URL like start.exactonline.com
When downgrading to 3.9.0 the problem goes away.

**Comment by stephangroen** [comment]
Are you sure you're not missing something? This specific class doesn't seem any different then other classes. Maybe a wrong call to set the base URL is made before executing this?

**Comment by stephangroen** [comment]
I see the Downloadable trait uses `$this->Url` instead of `$this->url`. I think this is the problem. Could you try this? We can create a bugfix release if this fixes the problem.

**Comment by alexjeen** [comment]
Not sure that is related because I have had a look and I think it was also $this->Url when the version was 3.9.0

I think the problem is in one of the other classes.

The code works exactly as we written it for 3.9.0 but not anymore for the newer version. I can send you a full stacktrace by email maybe that will narrow it down?

**Comment by stephangroen** [comment]
Please send it to me at info@picqer.com.

**Comment by stephangroen** [comment]
Can you paste it here? Otherwise please send it to me at info@picqer.com.

**Comment by stephangroen** [comment]
Fixed in https://github.com/picqer/exact-php-client/releases/tag/v3.12.1
