### ISSUE TITLE
Downloading attachment stopped working

### ISSUE THREAD

**Issue by WebDevTmas** [picqer/exact-php-client#246]
I was getting attachments of an invoice I just created like this:
However this suddenly stopped working a few days ago, can anybody help here?

Following error occurs: 
Picqer\Financials\Exact\ApiException: Error 400: Unrecognized 'Edm.Guid' literal 'guid''' in '12'. (uncaught exception) at /var/web/partners/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php line 560 while creating an invoice.

```
$printedInvoice = new PrintedSalesInvoice($this->exact);
$printedInvoice->InvoiceID = $invoice->InvoiceID;
$documentData = $printedInvoice->save();
        
$attachment   = new DocumentAttachment($this->exact);
$attachments  = $attachment->filter(sprintf("Document eq guid'%s'", $documentData['Document']));
```

**Comment by roland-d** [comment]
Hello,

I am using this code
```
$documentAttachment = new DocumentAttachment($this->connection);

return $documentAttachment->filter("Document eq guid'" . $guid . "'");
```

This works fine for me. I see no issues with your code.

The only thing I am trying to figure out is how to download the PDF files using a script. Are you doing that as well?

**Comment by LiquidSebbey** [comment]
I had the same issue when I was unable to get the download working but fixed it as followed:

- Create a new acces token,
- Use cURL to download the URL you get from documentAttachment with  added headers called:
`
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, TRUE); // We'll parse redirect url from header.
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, FALSE); // We want to just get redirect url but not to follow it.        
curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Bearer ".$accessToken));
`

- when `curl_exec`, it'll output the PDF file

You can fetch the (pdf) output and save it, or stream it to the end-user.

**Comment by roland-d** [comment]
@LiquidSebbey Thank you so much for this hint. I have it working now as well.

**Comment by WebDevTmas** [comment]
In the end I found out the invoice was going into a book year that didn't exist yet. (we have a start and end date for our invoice).
After making the book year it was able to print the invoices again.

**Comment by gunjanbgpl** [comment]
> Hello,
> 
> I am using this code
> 
> ```
> $documentAttachment = new DocumentAttachment($this->connection);
> 
> return $documentAttachment->filter("Document eq guid'" . $guid . "'");
> ```
> 
> This works fine for me. I see no issues with your code.
> 
> The only thing I am trying to figure out is how to download the PDF files using a script. Are you doing that as well?

I am also struggling for same - unable to download pdf invoice(https://github.com/picqer/exact-php-client/issues/465)
Can you please share your code for downloading it, It will be a big help?
