### ISSUE TITLE
SalesInvoice example not working?

### ISSUE THREAD

**Issue by sebastiaan-dharma** [picqer/exact-php-client#249]
```
$salesInvoice = new SalesInvoice($connection);
$salesInvoice->InvoiceTo = $customer_code;
$salesInvoice->OrderedBy = $customer_code;
$salesInvoice->YourRef = $orderId;
$salesInvoice->SalesInvoiceLines = $invoiceLines;
$salesInvoice->save();
```

When using the example as given in de readme, and having the correct values (invoiceLines, the correct GUID for the customer etc.) I get the following error:

`Error 500: Ongeldige referentie: Leveren aan\r\nOngeldige referentie: Besteld door\r\nOngeldige referentie: Factuur voor`

I have no clue what is going wrong. The customer code is a GUID of the contact within an account. Which seems legit. The invoice lines are correct GUIDs as well.

**Comment by stephangroen** [comment]
Get the raw request and contact Exact. They will be able to provide the details of what exactly is wrong.
