### ISSUE TITLE
Error while creating invoice using Exact Online

### ISSUE THREAD

**Issue by tkslabz** [picqer/exact-php-client#257]
Hello
I am facing the "Error encountered in converting the value from request payload for property 'OrderedBy' to type 'Guid', which is the property's expected type" error when i creating the SalesInvoice. I think the error occurs for InvoiceTo and OrderBy parameters. In which format i need to send these parameters? I have used the guid'xxxx-xxxx-xxx-xxxx' format, but it's not working for me, Could anybody please help me to sort out the error.
Thanks

**Comment by brasileric** [comment]
Hi. Have you fixed this issue already? I experience the same error with InvoiceTo and OrderBy.

**Comment by rickgoemans** [comment]
I'm not sure if this is related to your problem but if you're filtering on Guid's you have to use the following format:

`$salesEntry = new SalesEntry($connection);`
`$salesEntry = $salesEntry->filter("EntryID eq guid'5e9ec63d-1e6e-4920-b799-bd636a6055c9'")[0];`
`dd($salesEntry);`

**Comment by stephangroen** [comment]
Do any of you have a code example? That makes it a lot easier to assist :)

The value of InvoiceTo should be the ID of an Account. So if you get an account first for example you can use:
```php
$salesInvoice->InvoiceTo = $account->ID;
```
