### ISSUE TITLE
Update account record using Exact Online API

### ISSUE THREAD

**Issue by tkslabz** [picqer/exact-php-client#258]
Hello, 
I want update the account record using API, anybody please tell how i can update the existing account record. I am using "update" function, but i do not understand, how i can send the "guid" as parameter to update function. Anybody help me on this.
Thanks.

**Comment by TLWebdesign** [comment]
I'm having similar trouble. Did you figure out how to do this? Because it keeps asking me for account name but that is not a field that should be updated.
