### ISSUE TITLE
Doing a lot of requests to Exact loses its connection.

### ISSUE THREAD

**Issue by DaveyGiesen** [picqer/exact-php-client#264]
When doing a lot of requests to Exact it will loses its connection and it will result in a "400 Bad Request". When I do a tail on the exact.api.json file it will truncate the file after every request. I think the reason why it will lose connection because it cannot write the json file that fast.

Anyone experience the same issue?

**Comment by ersinpw** [comment]
I found this information on their website, maybe it will help you:


## API rate limits
Integration services will be limited by applying two rate limits:

Bursting limit - your app can make 60 API calls, per company, per 60 second window.
Daily quota limit - your app can make 50,000 API calls, per company, per day.
Both rate limits will limit the number of requests that your app is permitted to send during a time window. Each limit has a specific behaviour when it is exceeded.

## Bursting limit
If your app exceeds the bursting limit for a company, the requests for that company will be queued. Queued requests will be delayed until the bursting limit is no longer exceeded. Queuing results in an increase in the response time.

For example, if you send 40 requests in a first second then the bursting limit can only allow 20 requests for the remaining 59 seconds. Within that time frame, anything above 20 requests will be queued.

When the queue becomes too extensive after too many requests, any further requests will be blocked with an HTTP 503 (Service Unavailable) response until the bursting limit is no longer exceeded. No special HTTP response headers are returned to keep track of the bursting limit.

https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits

**Comment by DaveyGiesen** [comment]
I made a Jobs system what handles all incoming request, this solved this issue.
