### ISSUE TITLE
Cannot connect error 400 in Live, Demo works fine

### ISSUE THREAD

**Issue by ericappcomm** [picqer/exact-php-client#266]
Connection to a Demo-environment of Exact give me  positive responses.
My storage.json-file looks oke:
`{"authorizationcode":"xCL0!...dAN","accesstoken":"gA...3g4","refreshtoken":"zsP...ZA","expires_in":1525442466}`

To a LIVE-environment Error occurs

Setup:
If cleared the storage.json : `{}`
Then I get the authorizationcode and placed it into the storage.json, leaving the accesstoken and refreshtoken empty to get new once:
`{"authorizationcode":"5F33!...YAVI","accesstoken":"","refreshtoken":"","expires_in":}`
Now I cannot access Exact.
```
Fatal error: Uncaught Exception: Could not connect to Exact: Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response:
Bad Request
```
I cannot pass line 445 of function acquireAccessToken() in Picqer/Financials/Exact/Connection.php

        $response = $this->client()->post($this->getTokenUrl(), $body);

$this->getTokenUrl():
https://start.exactonline.nl/api/oauth2/token

with a 'old' refresh_token $body = 
```
array(1) {
  ["form_params"]=>
  array(4) {
    ["refresh_token"]=>
    string(295) "zsPl!.....xZA"
    ["grant_type"]=>
    string(13) "refresh_token"
    ["client_id"]=>
    string(38) "{5..-..-..-..49}"
    ["client_secret"]=>
    string(12) "F..........Y"
  }
}
```

without  a refresh_token $body = 
```
array(1) {
  ["form_params"]=>
  array(5) {
    ["redirect_uri"]=>
    string(39) "http://xxx.xxx.xxx/exact2/index.php"
    ["grant_type"]=>
    string(18) "authorization_code"
    ["client_id"]=>
    string(38) "{5..-..-..-..49}"
    ["client_secret"]=>
    string(12) "F..........Y"
    ["code"]=>
    string(401) "xCL0!....dAN"
  }
}
```

Can settings in the LIVE environment be the bad guy?
In DEMO I've a App-Center user.
In Live I cannot find this usertype. But I've registrated my applications logedin as main user

**Comment by alexjeen** [comment]
Make sure your redirect URL is OK, it needs to match exactly for your client_id you are using to production. It will give Bad Request otherwise.
