### ISSUE TITLE
reconcile cash payment

### ISSUE THREAD

**Issue by pavoxbv** [picqer/exact-php-client#268]
Hi, I run into a problem I was not able to solve :(

I create invoices. Some are paid in cash.
First I create  the invoice, this goes ok! (some vars are declare earlier but that is not important right now)

        /* create Invoice */
	$f = new \Picqer\Financials\Exact\SalesEntry($connection);
	$f->EntryDate = $invoice_date;
	$f->Description = $invoice_ref;
	$f->YourRef = $invoice_ref;
	$f->Journal = '70';
	$f->Customer =  $config['customer_guid'];
	$f->PaymentCondition = $paymentCondition;
	
	foreach ($invoicelines as $invoiceline) {
		$f->addItem($invoiceline);
	}
	$f->save();

	/* Create document and attach PDF data */
	$doc = new \Picqer\Financials\Exact\Document($connection);
	$doc->Subject = $invoice_doc;
	$doc->Account = $config['customer_guid'];
	$doc->Type = 10;
	$doc->SalesInvoiceNumber = $f->InvoiceNumber;
	$doc->YourRef = $invoice_ref;
	$doc->save();

	$attachment = new \Picqer\Financials\Exact\DocumentAttachment($connection);
	$attachment->Document = $doc->ID;
	$attachment->Attachment = $pdf_data;
	$attachment->FileName = $invoice_doc;
	$attachment->save();

	$f->Document = $doc->ID;
	$f->save();

Then, in case of a cash payment I create the following 

      $k = new \Picqer\Financials\Exact\CashEntry($connection);
      $k->JournalCode = '10';
	$k->addItem( array(
		'Account' => $config['customer_guid'],
		'AmountFC' => $payment['amount'],
		'Date' => $invoice_date,
		'GLAccount' => $config['GLAccounts']['1300'],
		'Description' => $invoice_ref,
		'OurRef' => $f->InvoiceNumber
		) 
	);
	$k->save();

This also works fine!  EXCEPT: The 	'OurRef' => $f->InvoiceNumber adds the invoice to the field for reconcilation but when I look manually in Exact the invoice is not checked and therefore not reconciled :( 

What an I missing to have invoice reconciled by the cash payment ?
Now I have to manually go troug all cash payments to reconcile.
Thanks!
![afbeelding1](https://user-images.githubusercontent.com/13970772/40103103-a60e5558-58ec-11e8-90ff-7b8515ad5c5e.jpg)
![afbeelding2](https://user-images.githubusercontent.com/13970772/40103104-a62d778a-58ec-11e8-905b-4a82fdedb319.jpg)

**Comment by alexjeen** [comment]
The only way to reconcile "automatically" is to use the XML API (<Matches> element). You have to give two posts to match against each other. Exact Online does not do this automatically via the REST API as far as I know. Example:

            $matchSets[] = ['MatchSet' => [
                'GLAccount' => ['@code' => '1300'],
                'Account' => ['@code' => $letterT->accountcode],
                'WriteOff' => [
                    '@type' => '4',
                    'GLAccount' => $settings['exact_gl_difference'],
                    'Description' => 'Koersverschil '.$letterT->invoice_id,
                    'FinYear' => $letterT->invoice_finyear,
                    'FinPeriod' => $letterT->invoice_finperiod,
                    'Date' => $weekInfo['batch_date'],
                ],
                'MatchLines' => [
                    // first line refers back to the sales booking
                    ['MatchLine' => [
                        '@finyear' => $letterT->invoice_finyear,
                        '@finperiod' => $letterT->invoice_finperiod,
                        '@journal' => $settings['exact_journal_sales'],
                        '@entry' => $letterT->invoice_entry,
                        '@amountdc' => $letterT->invoice_amount_eur,
                    ]],
                    // second line refers back to the memorial booking
                    ['MatchLine' => [
                        // so this much match
                        '@finyear' => $letterT->memo_finyear,
                        '@finperiod' => $letterT->memo_finperiod,
                        '@journal' => $settings['exact_journal_memo'],
                        '@entry' => $letterT->memo_entry,
                        // but this
                        '@amountdc' => $letterT->invoice_real,
                    ]],
                ],
            ]];

You can find more information about this in the XML documentation.

**Comment by mwansinck** [comment]
Does anyone know if this is already possible through the REST API?

**Comment by alexjeen** [comment]
Unfortunately not, but here is a piece of code that let's you communicate with the XML API ;)
You have to change it to work in your situation (we use Yii2), you have to make a class that extends \Picqer\Financials\Exact\Connection (so you have access to getAccessToken). We use FluidXML to mutate an array to XML, you can find the topics in the XML documentation inside Exact Online (click import in Exact Online and then XML reference).

    /**
     * Posts XML for an division.
     *
     * @param string $division division code
     * @param string $topic    the topic
     *
     * @return false on failure or SimpleXMLElement
     */
    public function postXml($division, $topic, $xml)
    {
        // auto determine
        $fluid = new FluidXml('eExact');
        $fluid->add($xml);

        $body = $fluid->xml();

        $client = new Client([
            'base_uri' => 'https://start.exactonline.nl/docs/',
        ]);
        // save start
        $time_start = microtime(true);
        try {
            // refreshes the token for 7 min
            $this->connect();
            // headers after connect
            $headers = ['Authorization' => 'Bearer '.$this->getAccessToken()];
            // save start
            $time_start = microtime(true);
            // huh
            $response = $client->request('POST', 'XMLUpload.aspx', [
                'query' => ['Topic' => $topic, '_Division_' => $division],
                'headers' => $headers,
                'body' => $body,
            ]);

            $time_end = microtime(true);

            return (string) $response->getBody();
        } catch (\Exception $e) {
            $time_end = microtime(true);
            \Yii::error(date('d-m-Y H:i:s').' op Guzzle Error ('.($time_end - $time_start).' seconds) ('.$topic.') ('.$division.'): '.$e->getMessage());
        }

        return false;
    }

**Comment by alexjeen** [comment]
Ow and use GuzzleHttp\Client for the client.

**Comment by mwansinck** [comment]
@alexjeen Thanks, this is very helpful
