### ISSUE TITLE
Update SalesInvoice

### ISSUE THREAD

**Issue by tkslabz** [picqer/exact-php-client#278]
Hello,
It is possible to update invoice using API? i want to update the invoice date.
Thanks 
Regards

**Comment by markjongkind** [comment]
You can update a SalesInvoice via the API:

    $SalesInvoice = new \Picqer\Financials\Exact\SalesInvoice($connection);
    $invoice = $SalesInvoice->find(ID);
    $invoice->Description = 'New description for invoice';
    $invoice->save();

Regarding updating the invoice date, the documentation says:

> Official date for the invoice. When the invoice is entered it's equal to the field 'EntryDate'. During the printing process the invoice date can be entered

I don't think you can update the invoice date. It gets populated when an invoice is sent to a relation, and updating a sent invoice is not possible (I assume even by law?).

**Comment by tkslabz** [comment]
Hello @markjongkind
Thanks for the help
