### ISSUE TITLE
Authenticate webhook

### ISSUE THREAD

**Issue by rickgoemans** [picqer/exact-php-client#279]
**Problem**
I'm trying to authenticate webhook calls from Exact but the authenticate function on the Authenticatable trait seems to fail. 

The result of the preg_match in the authenticate function gives `matched ` = 1  and `matches` is an array where the matched[2] does not match the strtoupper(hash_hmac('sha256', $requestContent, $webhookSecret)).

**Code**
I'm using Laravel 5.5 and here is my code.

The function on my controller:
```
public function webhookNotifications(Request $request)
{
  $data = $request->all();

  if (!$data) {
    return $this->sendResponse(true, "Exact webhook successfully registered");
  }

  $jsonRequest = json_encode($request->toArray(), JSON_UNESCAPED_SLASHES);

  if ($this->authenticate($jsonRequest, env("EXACT_WEBHOOK_SECRET"))) {
    dump("Valid");

    //...

    return $this->sendResponse(true, "Webhook notification processed successfully");
  } else {
    dump("Invalid");
  }
}
```

To clarify `Request` is the Laravel request class which extends the Symfony Request class `Symfony\Component\HttpFoundation\Request`.

**Authenticate function logging**
I changed the authenticate function to display logging, here is how it looks:
```
public function authenticate($requestContent, $webhookSecret)
{
  $matches = [];
  $matched = preg_match('/^{"Content":(.*),"HashCode":"(.*)"}$/', $requestContent, $matches);

  dump($matches);
  dump($matched);

  if ($matched === 1 && isset($matches[1]) && isset($matches[2])) {
    $hashed = strtoupper(hash_hmac('sha256', $matches[1], $webhookSecret));
    dump('Hashed:' . $hashed);

    return $matches[2] === strtoupper(hash_hmac('sha256', $matches[1], $webhookSecret));
  }
  return false;
}
```

**Output**
```
"{"Content":{"Topic":"Contacts","ClientId":"d0435ab3-fd1c-480f-89e1-c23f71bc432c","Division":"2124439","Action":"Update","Key":"8ccd300c-0b19-4408-812c-5745136487cf","ExactOnlineEndpoint":"https://start.exactonline.nl/api/v1/2124439/crm/Contacts(guid'8ccd300c-0b19-4408-812c-5745136487cf')","EventCreatedOn":"2018-07-04T17:24:40.46"},"HashCode":"82006A05AF4A4F104B7872109A455585E1C1D7FE1DE96BA6B5B91CCCB79BF8B5"}"
array:3 [
  0 => "{"Content":{"Topic":"Contacts","ClientId":"d0435ab3-fd1c-480f-89e1-c23f71bc432c","Division":"2124439","Action":"Update","Key":"8ccd300c-0b19-4408-812c-5745136487cf","ExactOnlineEndpoint":"https://start.exactonline.nl/api/v1/2124439/crm/Contacts(guid'8ccd300c-0b19-4408-812c-5745136487cf')","EventCreatedOn":"2018-07-04T17:24:40.46"},"HashCode":"82006A05AF4A4F104B7872109A455585E1C1D7FE1DE96BA6B5B91CCCB79BF8B5"}"
  1 => "{"Topic":"Contacts","ClientId":"d0435ab3-fd1c-480f-89e1-c23f71bc432c","Division":"2124439","Action":"Update","Key":"8ccd300c-0b19-4408-812c-5745136487cf","ExactOnlineEndpoint":"https://start.exactonline.nl/api/v1/2124439/crm/Contacts(guid'8ccd300c-0b19-4408-812c-5745136487cf')","EventCreatedOn":"2018-07-04T17:24:40.46"}"
  2 => "82006A05AF4A4F104B7872109A455585E1C1D7FE1DE96BA6B5B91CCCB79BF8B5"
]
1
"Hashed:9925B17859BE224A88CD4DBCFE004EB7857EEAB4603C4DBEFE16E4A91E826957"
"Invalid"
```

**POST Request**
Here is a POSTMAN request representing a real webhook notification:
```
{
  "Content": {
    "Topic": "Contacts",
    "ClientId": "d0435ab3-fd1c-480f-89e1-c23f71bc432c",
    "Division": "2124439",
    "Action": "Update",
    "Key": "8ccd300c-0b19-4408-812c-5745136487cf",
    "ExactOnlineEndpoint": "https://start.exactonline.nl/api/v1/2124439/crm/Contacts(guid'8ccd300c-0b19-4408-812c-5745136487cf')",
    "EventCreatedOn": "2018-07-04T17:24:40.46"
  },
  "HashCode": "82006A05AF4A4F104B7872109A455585E1C1D7FE1DE96BA6B5B91CCCB79BF8B5"
}
```
**The big question**
Is there anything I'm doing wrong (for instance incorrect supplying the request content to the authenticate function)?

**Comment by rickgoemans** [comment]
Retrieving the reponse is not a problem, it's validating whether the request is a valid Exact webhook callback or not(HashCode matches the hash of the json request's Content) which is the problem. The Authenticatable trait should help with this but the result of the authenticate function is always false for me.

I didn't know your way of retrieving the json reponse so I gave it a shot and the results for preg_match is:
```
$matches: []
$matched: 0
```

So it also returns `false`.

For now I just made this Laravel validation request:

```
<?php

namespace Donna\Exact\Http\Requests\API;

use Illuminate\Foundation\Http\FormRequest;

class ExactWebhookAPIRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'Content'                     => 'required|array',
            'Content.Topic'               => 'required_with:Content|string',
            'Content.ClientId'            => 'required_with:Content|string',
            'Content.Division'            => 'required_with:Content|integer',
            'Content.Action'              => 'required_with:Content|string|in:Create,Update,Delete',
            'Content.Key'                 => 'required_with:Content|string',
            'Content.ExactOnlineEndpoint' => 'required_with:Content|url',
            'Content.EventCreatedOn'      => 'required_with:Content|date',
            'HashCode'                    => 'required|string'
        ];
    }
}
```

But this does not check for the `HashCode` to be equal to `strtoupper(hash_hmac('sha256', $matches[1], $webhookSecret)`but only for the presence of the fields and data types.

**Comment by mahamood** [comment]
Thank you for your clear explanation of your problem.

follow below example you will able to validate your webhook response.

$requestContent= file_get_contents('php://input');  // (this is json responce)
$webhookSecret='XXXXXXXXXXXXXXXX';

$returnvalue=authenticate($input,$webhookSecret);


function authenticate($requestContent, $webhookSecret)
    {
        $matches = [];
        $matched = preg_match('/^{"Content":(.*),"HashCode":"(.*)"}$/', $requestContent, $matches);

        if ($matched === 1 && isset($matches[1]) && isset($matches[2])) {
            return $matches[2] === strtoupper(hash_hmac('sha256', $matches[1], $webhookSecret));
        }
        return false;
    }

**Comment by rickgoemans** [comment]
Thanks it is working now, guess I just had an incorrect POSTMAN request data to test.
