### ISSUE TITLE
More documentation calling webhook endpoint

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [picqer/exact-php-client#281]
I found this in your documentation:

For authenticating incoming webhook calls you can use the [Authenticatable](src/Picqer/Financials/Exact/Webhook/Authenticatable.php) trait.
Supply the authenticate method with the full JSON request and your Webhook secret supplied by Exact, it will return true or false.

Ok i understand i can use it as a trait. But can you tell me how to connect with the POST information of the webhook? 

I get this for example:

{"Content":{"Topic":"Items","ClientId":"78c73eec-2882-459d-b3f4-83a21a49591a","Division":2256995,"Action":"Update","Key":"dbc9f824-02bc-4eac-84b7-ff29a25fc828","ExactOnlineEndpoint":"https:\/\/start.exactonline.nl\/api\/v1\/2256995\/logistics\/Items(guid'dbc9f824-02bc-4eac-84b7-ff29a25fc828')","EventCreatedOn":"2018-08-10T13:14:50.07"},"HashCode":"5B5A7D43BB608545D87B7B494EED628D1AC770B56EEEDB805417491B618C62E6"} 

i was trying to connect with this endpoint with the get function, but i get:  array_key_exists() expects parameter 2 to be array, null given.

So how do i connect fast with "https:\/\/start.exactonline.nl\/api\/v1\/2256995\/logistics\/Items(guid'dbc9f824-02bc-4eac-84b7-ff29a25fc828" ? 

Its seem i also can connect with this function ->item and then use the key. But i think the best way is to connect with the endpoint.

**Comment by freddyamsterdam** [comment]
How about this, presuming $requestBody is the JSON string and $yourConnection returns a valid Exact connection:

```php
$content = json_decode($requestBody, true)['Content'];
$itemInstance = new Picqer\Financials\Exact\Item($yourConnection);
$itemFields = ['ID', 'BarCode', 'Description']; // Fields to retrieve
$item = $itemInstance->filter("ID eq '{$content['Key']}'", "", implode(',', $itemFields));

return $item
```
