### ISSUE TITLE
Oauth token request always returns invalid_request error

### ISSUE THREAD

**Issue by rudiedirkx** [picqer/exact-php-client#282]
I'm doing a

    $client = $connection->connect();

to start the flow. The start works, and Exact redirects back with a `code`. The lib tries to trade it for an access token, and then error:

    Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request` response:
    {"error":"invalid_request"}

I'm assuming the lib works for most people, so I wonder what Exact thinks is wrong with this request. I've tried:

* adding `force_login` to `form_params` in `acquireAccessToken()`, bc I saw that somewhere
* double url-decoding `code`, because the `!` is a `%21` in Exact's `code` (Exact fault, not the lib), but the examples I've found have a `!`
* wrapping client_id in `{}`, bc I saw that somewhere

but it's always `invalid_request` without details.

----

Somewhat relevant:

If the request returns a non-2xx response, Guzzle throws an exception, but the lib doesn't catch that, so this will never work:

```
$response = $this->client()->post($this->getTokenUrl(), $body);

if ($response->getStatusCode() == 200) {
    // success, get access token
}
else {
    throw new ApiException('Could not acquire or refresh tokens');
}
```

So `http_errors` should be false, or `acquireAccessToken()` should catch Guzzle's `ClientException`.

**Comment by Rogierownage** [comment]
I also experience this issue.

**Comment by rudiedirkx** [comment]
The inexplicable `invalid_request` error resolved itself. Probably Exact's fault. The `ApiException` bug is still a bug.

**Comment by rudiedirkx** [comment]
`ApiException` bug in #283
