### ISSUE TITLE
Unable to set the "Journal" value while creating sales invoice

### ISSUE THREAD

**Issue by tkslabz** [picqer/exact-php-client#287]
Hello,
I am creating a sales invoice and i want to set the journal value. My code is as follows.

       $salesInvoice = new \Picqer\Financials\Exact\SalesInvoice($connection);			
	$salesInvoice->OrderedBy 			=	$accounts->findId("Customer Name","Name");
	$salesInvoice->Journal				=	$journals->findId("Journal Name","Description");
	$salesInvoice->YourRef 				=	"test";
	$salesInvoice->Description			=	"My Test Invoice";
	$salesInvoice->SalesInvoiceLines	         =	$invoiceLines;
	$salesInvoice->save();
	$invoiceid	=	$salesInvoice->InvoiceID;

An invoice is created in the system, but it is  always pointed to default Journal instead of the journal which i pass to the journal parameter. Anybody what i need to do to set the Journal value which i required.

Thanks 
Regards

**Comment by DannyvdSluijs** [comment]
@tkslabz I was wondering if the result of `$journals->findId("Journal Name","Description");` could be null. This would explain why the sales invoice would be created with the default (`null`) journal.
A quick scan of the code base looks like `\Picqer\Financials\Exact\Query\Findable::findId` could return null as there are two paths which don't have a return value.
