### ISSUE TITLE
How to get the Exact API log

### ISSUE THREAD

**Issue by tkslabz** [picqer/exact-php-client#288]
Hello 
I want to maintain the API log,  so i can check the errors if API operation failed,
So how i can do it?
Thanks
Regards

**Comment by DannyvdSluijs** [comment]
Exact-php-client uses Guzzle V6 which supports middleware and already has some default middleware. 

Out of the box with this lob you should be able to setup a connection as follows:
`
$connection = new ExactOnlineConnection();
/* Some setters for client id, secret etc. */
$connection->insertMiddleWare(
    \GuzzleHttp\Middleware::log(
        $this->logger, 
        new \GuzzleHttp\MessageFormatter()
    )
);
`
