### ISSUE TITLE
Error: Object moved

### ISSUE THREAD

**Issue by patricksindelka** [picqer/exact-php-client#292]
After using the API and this script for years, I suddenly get 401 error's with:
Object moved to here.
With 'here' as a hyperlink, linking to the API I just called, for example /docs/Login.aspx?ReturnUrl=/api/v1/[my division id]/crm/Addresses

I didn't change my script the last months, it just suddenly stopped working. I already updated all composer packages but it didn't fix anything.

Is there anything changed to the Exact API, or does someone knows another solution for this?

**Comment by markvdlaan93** [comment]
I have the same issue here: /docs/Login.aspx?ReturnUrl=/api/v1/[my division id]/crm/Accounts but also /docs/Login.aspx?ReturnUrl=/api/v1/[my division id]/financial/GLAccounts. It seems this error is given for every call I actually make. Is there any solution for this problem?

**Comment by markjongkind** [comment]
I had this problem some days back. Exact changed the length of access tokens to ~600-650 characters. In my case, the access token field in my DB supported 600 characters, so the access token was saved partly (last part was cut-off).

With an incorrect access token, you get weird (not useful or relevant) error messages about moved objects and login URL's. Hope this points you in the right direction!

**Comment by patricksindelka** [comment]
Thanks, this fixed the issue. I had also a 600 characters limit in my database.

**Comment by fredattack** [comment]
> I have the same issue here: /docs/Login.aspx?ReturnUrl=/api/v1/[my division id]/crm/Accounts but also /docs/Login.aspx?ReturnUrl=/api/v1/[my division id]/financial/GLAccounts. It seems this error is given for every call I actually make. Is there any solution for this problem?

Same error also with a LongText fiel format for the access token. any other solution?
