### ISSUE TITLE
How can you link a parent item to a BOM?

### ISSUE THREAD

**Issue by alexjeen** [picqer/exact-php-client#295]
We are using the BOM functionality, but it's unclear how to find a parent item for a item belonging to BOM. There is no parent column in BillOfMaterialMaterials.

Does anyone have an example on how to use this functionality?

**Comment by markjongkind** [comment]
I don't understand your question completely I think but maybe this helps:

Every BillOfMaterialMaterials object has an ItemVersion field, with a GUID of a BillOfMaterialVersions object. In this BillOfMaterialVersions, you can find the Item which is linked to the BOM.

**Comment by alexjeen** [comment]
Thanks, we are looking for the parent ID of the BillOfMaterials:

![image](https://user-images.githubusercontent.com/1567497/46027699-c8e4fe00-c0ee-11e8-8738-78a200a319ee.png)

So these two items belong to a item called XXX, we want to figure out how to find out what BOM is actually linked. I think we can get pretty far with your comment. Thanks!
