### ISSUE TITLE
No Quotation send function

### ISSUE THREAD

**Issue by vdmsolutions** [picqer/exact-php-client#299]
Hi,

I noticed there is no option to send a Quotation in the API. I took the liberty of creating it myself, see code:

`<?php
/**
 * Class PrintQuotation
 *
 * @package Picqer\Financials\Exact
 * @see https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMPrintQuotation
 *
 * @property string $QuotationID Primary key, Identifier of the quotation
 * @property Int32 $Division Division code
 * @property string $Document Contains the id of the document that was created
 * @property String $DocumentCreationError Contains the error message if an error occurred during the creation of the document
 * @property String $DocumentCreationSuccess Contains information if a document was succesfully created
 * @property string $DocumentLayout Based on this layout a PDF is created and attached to an Exact Online document and an email
 * @property String $EmailCreationError Contains the error message if an error occurred during the creation of the email
 * @property String $EmailCreationSuccess Contains confirmation that an email was sent. If an email cannot be delivered this property will still show confirmation that the email was sent.
 * @property string $EmailLayout Based on this layout the email text is produced
 * @property String $ExtraText Extra text that can be added to the printed document and email
 * @property DateTime $QuotationDate Date of the quotation printed
 * @property Boolean $SendEmailToCustomer Set to True if an email containing the invoice should be sent to the invoice customer
 * @property Boolean $SendInvoiceToCustomerPostbox Set to True if a postbox message containing the invoice should be sent to the invoice customer
 */

namespace Picqer\Financials\Exact;

class PrintQuotation extends Model
{
    protected $primaryKey = 'QuotationID';

    protected $fillable = [
        'QuotationID',
        'Division',
        'Document',
        'DocumentCreationError',
        'DocumentCreationSuccess',
        'DocumentLayout',
        'EmailCreationError',
        'EmailCreationSuccess',
        'EmailLayout',
        'ExtraText',
        'QuotationDate',
        'SendEmailToCustomer',
        'SenderEmailAddress'
    ];

    /**
     * @return $this
     */
    public function save()
    {
        $this->fill($this->insert());
        return $this;
    }

    public function insert()
    {
        return $this->connection()->post($this->url, $this->json(0, true));
    }

    protected $url = 'crm/PrintQuotation';
}`

**Comment by DaveyGiesen** [comment]
Just add this in a pull request.
