### ISSUE TITLE
Webhook detect resource creation

### ISSUE THREAD

**Issue by Raqbit** [picqer/exact-php-client#307]
Hi,

What would be the best way to detect the creation of a resource with Exact Online Web-hooks?

AFAIK Exact only gives `UPDATED` and `DELETED` events.

I was looking at the `Created` property most resources have, (Could filter out resources which have a `Created` date which is not recent) but this has it's own drawbacks.

Cheers!

**Comment by DannyvdSluijs** [comment]
Based on there [docs](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-webhookstut) there is indeed no CREATE event.
Not sure if perhaps a new entity would be considered an UPDATE event as the web hook is subscribed to a topic. And in some parts of the documentation this is pointed at as follows:

> Subscribe to the topic Quotations to get updates on the QuotationLines resource

I guess the proof is in the pudding (e.g. should try and find out) if the creation of a new entity (Account etc) will lead to an event.

**Comment by Raqbit** [comment]
It seems like the creation of a resource indeed triggers the `UPDATED` event, but this also triggers for resource updates, which I am not interested in.

**Comment by stephangroen** [comment]
Seems like an issue for Exact Online, not this library.
