### ISSUE TITLE
Resultset class: type exception on getting second page (v3.15.1, PHP 7.2.8)

### ISSUE THREAD

**Issue by rubenvincenten** [picqer/exact-php-client#308]
Argument 2 passed to Picqer\Financials\Exact\Connection::get() must be of the type array, null given

call:

```php
$query = [
    '$filter' => implode(' and ', [
        'Status eq 50',
        sprintf("Created gt datetime'%s'", date('Y-m-d\TH:i:s', $since->getTimestamp()))
    ]),
    //    '$top'    => $top,
    //    '$skip'   => $skip,
    //    '$orderby' => 'Created desc'
];
$invoice_model    = new \Picqer\Financials\Exact\SalesInvoice($connection);
$resultset = $invoice_model->getResultSet($query);

while ($resultset->hasMore()) {
    $invoices = $resultset->next();
}
```

Connection::get() obviously requires an array for params. Resultset however sets params to NULL.

**Comment by stephangroen** [comment]
Please let me know if this is still actual in the current version (3.19.0).

**Comment by dietlev** [comment]
`
$products = new \Picqer\Financials\Exact\AccountItem($connection);
$query = [
     'accountId' => "guid'00000000-0000-0000-0000-000000000000'",
    '$select' => implode(',', ['ID', 'Account', 'IsWebshopItem'])
];
        
$results = $products->getResultSet($query);

while( $results->hasMore() ){
    $r = $results->next();
}`

This still has the same problem, the params are not stored in 3.19.0
