### ISSUE TITLE
How to add a "Boeking | Verkoopboek"

### ISSUE THREAD

**Issue by robinvalk** [picqer/exact-php-client#31]
Hi,

We're trying to add a "Boeking | Verkoopboek".
I tried adding a SalesEntry but I'm stuck with the error: "Ongeldige referentie: Journals"

Is `SalesEntry` the correct model? And so, how can I fix the error above?
This is our current situation with the given error. Notice that I retrieve the journal id specifically to prevent any mismatch.
```php
$journals = (new Journal($exact->connection()))->get();
$journal = array_filter($journals, function($journal) {
    return $journal->Code == 70;
});
$journal = array_shift($journal);

\Log::info($journal->ID);

$accountingServiceEntry = new SalesEntry($exact->connection(), [
    'Currency' => $invoice->valuta_id,
    'Customer' => $invoice->klant->accounting_service_id,
    'YourRef' => $invoice->nr,
    'Journal' => $journal->ID,
    'Description' => $description,
]);

$items = $invoice->getItems();

foreach($items as $invoiceItem) {
    $accountingServiceEntry->addItem([
        'Description' => $invoiceItem->omschr,
        'Quantity' => (int) $invoiceItem->aantal,
        'AmountFC' => $invoiceItem->bedrag,
        'VATPercentage' => $invoiceItem->btw_perc,
    ]);
}

\Log::info($accountingServiceEntry->save());
```

Cheers

**Comment by stephangroen** [comment]
Hi @robinvalk,

I don't use SalesEntry myself, we only use SalesInvoices for sales. Looking at the Exact API reference, I think you shouldn't supply the `$journal->ID` but you should use the `$journal->Code`. Yes, Exact works that way :)

**Comment by robinvalk** [comment]
Thanks, using SalesInvoices would also work for us indeed. We just need to set it to processed directly. That would work using [PrintedSalesInvoices](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoicePrintedSalesInvoices), which isn't implemented, right?
Would you accept a PR to add the model?

**Comment by stephangroen** [comment]
PrintedSalesInvoices is not implemented yet. A PR is always welcome!
