### ISSUE TITLE
$top=1 instructions unclear

### ISSUE THREAD

**Issue by bert-w** [picqer/exact-php-client#315]
This sample in the readme doesnt work. It still returns
"Error 400: Please add a $select or a $top=1 statement to the query string."
```
$test = new GeneralJournalEntry($connection);
var_dump($test->filter('', '', '', ['$top'=> 1]));
```

**Comment by freddyamsterdam** [comment]
He Bert,

Instruction on how to use $top (and $filter, $select, etc) can be found on this page about [oData 2 Uri Conventions](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/).

Judging from your code snippet, you aren't actually selecting any attributes.

https://github.com/picqer/exact-php-client/blob/b362143aaa18f383416ce68c0a922fd9196465ab/src/Picqer/Financials/Exact/Query/Findable.php#L86

You may want to try something like this:

```php
$test = new GeneralJournalEntry($connection);
$selectAttributes = 'EntryID, GeneralJournalEntryLines';
$expandAttributes = 'GeneralJournalEntryLines';

var_dump($test->get([
    '$expand' => $expandAttributes, 
    '$select' => $selectAttributes, 
    '$top'=> 1
]));
```

**Comment by bert-w** [comment]
yes i got it working eventually. Code samples in the readme should work out of the box though

**Comment by freddyamsterdam** [comment]
@bert-w true that!
