### ISSUE TITLE
Requesting SalesOrders by OrderID returns empty

### ISSUE THREAD

**Issue by NickMainline** [picqer/exact-php-client#316]
Hi there,
$salesOrder->find($order_id); returns nothing not even an error, I have tried using the filter and using other references but still nothing.
I'm probably doing something wrong, can anyone help me please.
I can add orders with order lines to exact, but just can't recall them.
Thanks...

**Comment by NickMainline** [comment]
Hi, Turns out the solution/workaround is to omit the connection object and just return the result.
`$collection = [];
        foreach ($result as $r) {
            //$collection[] = new self($this->connection(), $r);
            $collection[] = $r;
        }
        echo json_encode($collection);
        //return $collection;`

**Comment by ivaralink** [comment]
I have the same problem, I cannot retrie items by ID nor filter and get a result

**Comment by freddyamsterdam** [comment]
Hey @NickMainline! Could you send over a bit more code, please? Are you sure you are querying the correct division in Exact?

**Comment by NickMainline** [comment]
Hi @freddyamsterdam, my BlockingStatus = 0 so looks like I'm not blocked, So I can retrieve single Items and Accounts, but can't get SalesOrders.

**Comment by markjongkind** [comment]
`$result   = $journals->filter("Code eq '6854'");`

Account codes have a fixed length of 18 characters and contains leading spaces. See [Tips and Tricks](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-resttips) (last section) for details. You need to use trim(Code) in your filter, like this:

`$result   = $journals->filter("trim(Code) eq '6854'");`

Regarding the `$salesOrder->find($order_id)` issue: this never works for me, I always use `filter()`.
