### ISSUE TITLE
Cannot update PaymentReference on SalesEntry

### ISSUE THREAD

**Issue by VincentdeWit94** [picqer/exact-php-client#323]
I recently noticed that when trying to update the PaymentReference on a SalesEntry, Exact returns: Error code 500: Gegeven bestaat reeds. Exact support is telling me that this is (probably) because the PUT payload contains the whole model instead of just the PaymentReference.

Any thoughts?

Thanks!
Vincent

**Comment by DannyvdSluijs** [comment]
Probably easiest is to add some logging to the API connection as described [here](https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-responsel). This will enable you to review the data being send to Exact, and if the PUT payload contains the whole model. (Or even if there is a PUT request is being done)

**Comment by VincentdeWit94** [comment]
Hi Danny,

Thanks for you response. Just did a quick test and I can indeed confirm that the payload to Exact contains the whole model. A quick test in Postman (with the whole model), returns error 500, but succeeds with just the PaymentReference.

I guess this is something fundamental in this SDK since it is not tracking which fields are updated and thus which to send to Exact. Or did someone else solve this already?

**Comment by DannyvdSluijs** [comment]
Hi @VincentdeWit94,

Seems like the codebase doesn't allow for PATCH updates but Exact also doesn't use them. It seems the PUT can be (ab-)used for partial updates as per Exact Online documentation interactive examples.

Besides that I could seem a difference in number of properties for the POST request (48) and the PUT request (27). Currently it seems that the implementation doesn't differ between the body for an insert or update. Could you share the request body perhaps as well?

As a alternative approach (outside of the model) you could try the following:
```php
$entry = new SalesEntry();
$primaryKey = '00000000-0000-0000-0000-000000000000';
$reference = 'Some fancy new reference';

$connection->put(
    $entry->getUrl() . "(guid'$primaryKey')",
    json_encode(['PaymentReference' => $reference])
);
```

This pseudo code would only update the payment reference for a given primary key of a SalesEntry. Let me know if this works, as we can add this to the project Wiki on how to update a single parameter.

**Comment by stephangroen** [comment]
Thanks for the support @DannyvdSluijs :)
