### ISSUE TITLE
Unable to upload pictures

### ISSUE THREAD

**Issue by Badjas69** [picqer/exact-php-client#326]
Trying to upload a picture, the url works when I go to it myself, tried to urlencode it, also responded with null.

before save():
![image](https://user-images.githubusercontent.com/45967000/50397487-fd5d6a00-0770-11e9-9457-3e523dbedafc.png)

after save():
![image](https://user-images.githubusercontent.com/45967000/50397496-09e1c280-0771-11e9-83cf-cb7645f1586d.png)

**Comment by DannyvdSluijs** [comment]
Hello @Badjas69,

I believe it could be helpful to provide more context to your issue in order for people to assist.
Perhaps you can include some (_redacted if needed_) code which shows the API flow you are using. Currently your screens only provide some key and values related to some Model?

**Comment by Badjas69** [comment]
Thought this would be enough but okay, I'm trying to transfer over my products to exact online using the rest api.
I'm using this library, here is the item Model:

![image](https://user-images.githubusercontent.com/45967000/50645776-9f9cff00-0f74-11e9-855a-4e05ecdd5f1c.png)

which outputs this before saving ( $item->save() ) it:

![image](https://user-images.githubusercontent.com/45967000/50645910-ff93a580-0f74-11e9-95af-59d11b3dcafe.png)

When I paste this URL in my browser I see the image. So I'm expecting this is the right url?

after I save it ($item->save() ) I get this:

![image](https://user-images.githubusercontent.com/45967000/50646147-a8da9b80-0f75-11e9-961f-60687bb77514.png)

When I GET the item via the api I get the standard place holder images.

![image](https://user-images.githubusercontent.com/45967000/50646325-0bcc3280-0f76-11e9-8a71-5ef259a91481.png)

Maybe I used some wrong terms, sorry if that's the case.

**Comment by stephangroen** [comment]
I would guess this is the correct way, based on the Exact docs. Maybe contact Exact Online and submit them the request you're doing.
