### ISSUE TITLE
After adding AmountDiscount parameter no invoice email sent

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#329]
Hello Team ,

I am working on Sales invoice and its working fine only its not sending an invoice email attachment when  'AmountDiscount' is greater than zero(0) means if discounted price is set (its based on condition some time its becoming zero means no discount sent and some times it will send some discount amount with it) then its not generating an invoice email attachment to the customer and i have printed in the catch block so its returning me as a error **Picqer \ Financials \ Exact \ ApiException: Error 500: Not available: Setting ( General ledger accounts : Links - Sales invoice discounts )** , Please look into this and let me know whats wrong in  this.

Please check my code/parameters

                   $salesInvoice->InvoiceTo = $eo2_id;
                    $salesInvoice->OrderedBy = $eo2_id;
                    $salesInvoice->YourRef = $order_id;
                    $salesInvoice->Description = (string) $order_id;
                    $salesInvoice->SalesInvoiceLines = $invoiceLines;
                    $salesInvoice->AmountDiscount = $discount_amount;
                    $salesInvoice->OrderDate = date("Y-m-d");
                    $woocommerce_exactonline2_jrnal  = get_option("woocommerce_exactonline2_jrnal") ;
                    if(!empty($woocommerce_exactonline2_jrnal) && $woocommerce_exactonline2_jrnal!=""){
                         $salesInvoice->Journal = $woocommerce_exactonline2_jrnal;
                    }
                   $salesInvoice->save();

Thanks

**Comment by FawadNL** [comment]
We have same issue

**Comment by wasimman** [comment]
Hello Team,

I did not hear anything on this issue so unable to finish this module in the project, Please update me on this as soon as  possible so that we can close this.

Thanks

**Comment by FawadNL** [comment]
We solved this, you need to add the GL Code of discount to Salesinvoicediscount in settings page of EO.
