### ISSUE TITLE
Get last inserted id 

### ISSUE THREAD

**Issue by FawadNL** [picqer/exact-php-client#333]
Hello Team ,

I am working on the API's But i am unable to read the Last inserted id Of Exact online of saved API call.

Thanks

**Comment by markjongkind** [comment]
If you create an entity (for example a Project), you can retrieve the created ID this way:

    $Project = new \Picqer\Financials\Exact\Project($connection);
    $Project->Code = '123';
    $Project->Description = 'Test project';
    $Project->Type = 1;
    $Project->save();
    
    $created_id = $Project->ID;

**Comment by FawadNL** [comment]
Ok Thanks,

 I got it.
