### ISSUE TITLE
Unable to add Selling price in Invoice Items

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#334]
Hello Team ,

I am using sales invoice API in which i wants to add Sales price for item and to achieve this i used /vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/SalesItemPrice.php but its always adding price in the 'Price agreement not in 'Selling prices' in Exact online , Please guide me on this how we can achieve this.

Thanks

**Comment by FawadNL** [comment]
Same issue here

**Comment by stephangroen** [comment]
Do you have a code example for this?

**Comment by wasimman** [comment]
Yes i have the code ,

Please review it.


$eo_fina_vari_price= $regular_price_product+$sales_price_product;
$variation_id = 3306;
$result_item = $item->filter("Code eq '$variation_id'");
if(!$result_item){
    //Create a new item
    try {
        $item->Code = $variation_id;
        $item->CostPriceStandard = $item_total;
        $item->Description = $var_item_name;
        if(!empty($result_to_subscription)){
            $item->GLRevenueCode = $eo2_revenue_ledger_account_id;
            $item->GLRevenue = $result_to_subscription[0]->ID;
        }
        if($start_fee_flag){
            $item->GLRevenueCode = $eo2_signup_ledger_account_id;
            $item->GLRevenue = $result_to_signup[0]->ID;
        }
       
        if(!empty($cost_unit_id)){
            $item->Unit = $cost_unit_id;
        }
        $item->IsSalesItem = true;
        //$item->SalesVatCode = $vat_list[0]->Code;;
        $item->SalesVatCode = $woocommerce_exactonline2_tax_rate;
        $item->save();
        $result3 = $item->filter("Code eq '$variation_id'");
       $eo2_item_id=$result3[0]->ID;
        $sales_item_price_var = get_post_meta( $variation_id, 'sales_item_price_var_'.$variation_id, true );
        if(empty($sales_item_price_var)){
            $sales_item_price_var_result= $salesitemprice1->filter("Code eq '".$variation_id."'");
            if(!empty($sales_item_price_var_result)){
                try{
                    $rip= $salesitemprice->find($sales_item_price_var_result[0]->ID);
                    $rip->Item = $eo2_item_id;
                    $rip->Price = $eo_fina_vari_price;
                    $rip->save();
                    delete_post_meta($variation_id, 'sales_item_price_var_'.$variation_id); 
                    add_post_meta( $variation_id, 'sales_item_price_var_'.$variation_id,$sales_item_price_var_result[0]->ID);
                    
                }catch (\Exception $e1) {
                    echo ($fp, "\n  : sales_item_price_var_result create error inside 1".$e1->getMessage());
                }
            }else{
                try{
                     $salesitemprice->Item = $eo2_item_id;
                    $salesitemprice->Price = $eo_fina_vari_price;
                    $salesitemprice->save();
                    delete_post_meta($variation_id, 'sales_item_price_var_'.$variation_id); 
                    add_post_meta( $variation_id, 'sales_item_price_var_'.$variation_id, $salesitemprice->ID );
                }catch (\Exception $e1) {
                    echo ($fp, "\n  : sales_item_price_var_result item error in first else   ".$e1->getMessage());
                }
            }
        }else{
            try{
                 $salesitemprice->Item = $eo2_item_id;
                $salesitemprice->Price = $eo_fina_vari_price;
                $salesitemprice->save();
                delete_post_meta($variation_id, 'sales_item_price_var_'.$variation_id); 
                add_post_meta( $variation_id, 'sales_item_price_var_'.$variation_id, $salesitemprice->ID );
            }catch (\Exception $e1) {
                echo ($fp, "\n  : sales_item_price_var_result item error in first else   ".$e1->getMessage());
            }
        }
    }catch (\Exception $e1) {
       echo " error in getting the item =".get_class($e1) . ' : ' . $e1->getMessage();
    }
}

Thanks
