### ISSUE TITLE
Unable to add invoice line sales price

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#337]
Hello Team,

I am working on invoice section but  i am unable to post Sales item price Its returning me **Moet zijn: Uniek - Artikel, Valuta, Eenheid, Aantal, Actief vanaf, Actief tot**
 Means **Must be: Unique - Item, Currency, Unit, Quantity, Active from, Active to** even though i have passed all the parameters.

Please check my code with the parameters 
```php
 try{
// $salesitemprice->Account = $eo2_id;
$salesitemprice->Item = '74bb10f9-3573-4dd6-bdff-8caf3ebdccd6';
$salesitemprice->Price = $eo_fina_vari_price;
$salesitemprice->Currency = 'Euro';
$salesitemprice->Quantity = 1;
$salesitemprice->StartDate = date("Y-m-d");
$salesitemprice->EndDate =  date('Y-m-d', strtotime('+1 year'));
//$salesitemprice->DateTime = date("Y-m-d");
$salesitemprice->Unit = 'month';
$salesitemprice->save();
fwrite($fp, "\n  : salesitemprice->ID   ".$salesitemprice->ID);
} catch (\Exception $e1) {
    echo "\n  : salesitemprice add error 111 = ". $e1->getMessage();
}
```
Please check and let me know whats wrong in the above code, I am following https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsSalesItemPrices POST method . 

Thanks

**Comment by stephangroen** [comment]
I haven't used this before, but I see some things that might help:

The datetime must be of type Edm.DateTime according to the docs. The stated format is `yyyy-mm-ddThh:mm[:ss[.fffffff]]`. Your format seems incorrect.

You could get the JSON of your response and submit that to Exact support along with the error you're getting and ask them what is wrong with the data you are submitting.

To get the JSON you could [insert a logging Middleware](https://stackoverflow.com/questions/32681165/how-do-you-log-all-api-calls-using-guzzle-6) of quick and dirty add a line in the Storable trait in the insert method:
```php
        var_dump($this->json(0, true)); exit;
```

so the total method looks like this:

```php
    public function insert()
    {
        var_dump($this->json(0, true)); exit;
        return $this->connection()->post($this->url(), $this->json(0, true));
    }
```

**Comment by wasimman** [comment]
Thanks for updates, 

Will change the date format and print the lines as per your suggestion and get back to you with on this. 

Thanks
