### ISSUE TITLE
No version set (parsed as 1.0.0) + conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by AWINK010** [picqer/exact-php-client#338]
I cannot unpack this api with composer.
it keeps on crashing with the following description:

The requested package picqer/exact-php-client No version set (parsed as 1.0.0) is satisfiable by picqer/exact-php-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Any thoughts would be nice

With regards
Wink

**Comment by stephangroen** [comment]
How did you require the package with composer? I don't get any issues.

**Comment by flapsup** [comment]
Exactly the same message here; 
Any suggestion? 

Problem 1
    - The requested package picqer/exact-php-client No version set (parsed as 1.0.0) is satisfiable by picqer/exact-php-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Regards,
Hans

**Comment by flapsup** [comment]
> Exactly the same message here;
> Any suggestion?
> 
> Problem 1
> - The requested package picqer/exact-php-client No version set (parsed as 1.0.0) is satisfiable by picqer/exact-php-client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
> 
> Regards,
> Hans

Found it. Composer was not correct installed. Now it's working!
