### ISSUE TITLE
Unable to update bank account number for customer 

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#339]
Hello Team ,

I am unable to update bank account number for customer in Exact online.

Please check my code below,

    $bankaccount = new BankAccount($connection);
    $eo_bank_account_id = 'exact online bank account it';
    $bank=  1234 9874 1231 12;
    $account_holder=   'Person name';
    $eo2_id=  'exact online id';
        try{
             $res_bankaccount = $bankaccount->find($eo_bank_account_id);
             $res_bankaccount->BankAccount = $bank;
             $res_bankaccount->BankAccountHolderName = $account_holder;
             $res_bankaccount->save();
        } catch (\Exception $e1) {
         echo ("\n  :  error ".$e1->getMessage());
      }

Thanks

**Comment by stephangroen** [comment]
Please format your issue a bit so it's readable for everyone.

**Comment by wasimman** [comment]
Hello Team ,

I am unable to update bank account number for customer in Exact online.

Please check my code below,

        $bankaccount = new BankAccount($connection);
        $eo_bank_account_id = 'exact online bank account it';
        $bank=  1234 9874 1231 12;
        $account_holder=   'Person name';
        $eo2_id=  'exact online id';
            try{
                 $res_bankaccount = $bankaccount->find($eo_bank_account_id);
                 $res_bankaccount->BankAccount = $bank;
                 $res_bankaccount->BankAccountHolderName = $account_holder;
                 $res_bankaccount->save();
            } catch (\Exception $e1) {
             echo ("\n  :  error ".$e1->getMessage());
          }
       
Thanks

**Comment by joostvanmeeuwen** [comment]
Hi wasimman,

Could you please elaborate a bit more? Do you get an error? What is the result of your find query? Is there a bank account returned from the API?

Also, please check your `$bank` variable, I assume it's some dummy data in order to give us an code example, but it should be a string. Check the [Exact Online REST API docs](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMBankAccounts) for more info.

**Comment by stephangroen** [comment]
Has any of you contacted Exact Online about this? They might have an answer for you.

**Comment by FawadNL** [comment]
I got the solution on this If we assign Mandates to particular bank account then that bank account 
 number wont editable , We need to create new bank account account for the same user and update in 
 that and i was not getting any 403 forbidden error so dont know about the 403 error  it was just not  
 updating the bank account number for me.

 Thanks

**Comment by StefanoGroenland** [comment]
Told EO about this, they said i should sent them all HTTP requests and stuff. But i just waited a day, and didn't get the error since then.
