### ISSUE TITLE
Don't know how to get RateLimit headers

### ISSUE THREAD

**Issue by JorniCornelese** [picqer/exact-php-client#341]
I've seen some issues regarding the RateLimit headers. but they're still unclear to me. 

Are the RateLimit's already activated as said in [this comment](https://github.com/picqer/exact-php-client/issues/255#issuecomment-422339130) , and if so, how do I get them?

If it's not activated yet, what is the best way to count my requests, and when does the RateLimit reset?

**Comment by stephangroen** [comment]
Continuing this in #255
