### ISSUE TITLE
Unable to add cost unit for subscription line items

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#342]
Hello Team,

    I am working on subscriptions module where i am posting subscriptions to exact online and its working fine but when i am adding 'Costunit' to the line items then its throwing me an error i have tried different different way to add the Costunit but did not got success.

    Please check below code.

    $subscription_line_items = Array ( [0] => Array ( [Item] => 8e3627e4-0217-49c1-b08d-000966fd6513 [Quantity] => 1 [UnitPrice] => 48.76 [Costunit] => month ) [1] => Array ( [Item] => 2bac5501-d7c9-4f2c-b9a1-b92ed483629e [Quantity] => 1 [UnitPrice] => 8.26 [Costunit] => month ) ) 

    $subscription_line_items = Array ( [0] => Array ( [Item] => 8e3627e4-0217-49c1-b08d-000966fd6513 [Quantity] => 1 [UnitPrice] => 48.76 [Costunit] => month  ) [1] => Array ( [Item] => 2bac5501-d7c9-4f2c-b9a1-b92ed483629e [Quantity] => 1 [UnitPrice] => 8.26 [Costunit] => month  ) )

    $subscription_line_items = Array ( [0] => Array ( [Item] => 8e3627e4-0217-49c1-b08d-000966fd6513 [Quantity] => 1 [UnitPrice] => 48.76 [Costunit] => 2bac5501-d7c9-4f2c-b9a1-b92ed48362111) [1] => Array ( [Item] => 2bac5501-d7c9-4f2c-b9a1-b92ed483629e [Quantity] => 1 [UnitPrice] => 8.26 [Costunit] => 2bac5501-d7c9-4f2c-b9a1-b92ed48362111  ) ) 

    For above three array i am getting - Invalid reference: Cost unit

    Array ([0] => Array ([Item] => 8e3627e4-0217-49c1-b08d-000966fd6513 [Quantity] => 1 [UnitPrice] => 48.76 [Costunit] => 00108512 ) [1] => Array ([Item] => 2bac5501-d7c9-4f2c-b9a1-b92ed483629e [Quantity] => 1 [UnitPrice] => 8.26 [Costunit] => 00108512 ))

    For above  array i am getting 

    -Error 500: Item unit must have the property 'Time' and the unit Months, Quarter, Half Year or Year.

    Please check my code below for subscriptions.

    try {
        $subscription->OrderedBy = $eo_id;
        $subscription->InvoiceTo = $eo_id;
        $subscription->Description = $rand_number;
        $subscription->SubscriptionLines = $subscription_line_items;
        $subscription->SubscriptionType = $cost_sub_type_id;
        $subscription->InvoicingStartDate = $sub_start_date;
        $subscription->StartDate = $sub_start_date;
        $subscription->save();
    } catch (\Exception $e1) {
            echo " subscription add error =".get_class($e1) . ' : ' . $e1->getMessage();
    }

    Thanks

**Comment by stephangroen** [comment]
Could you please format your issue contents? It's very hard to read.

**Comment by stephangroen** [comment]
According to the [Exact Online Docs](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptionLines) the Costunit is an Edm.String and references a [Costunit](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=HRMCostunits), you probably need to reference the Code of a Costunit there.

**Comment by wasimman** [comment]
Yes you are right, we need to send Code as a parameter and its working fine on Invoice line Costunit and if i am passing  same in subscription line items then its showing me below error. 

**Picqer \ Financials \ Exact \ ApiException: Error 400: Error processing request stream. The property name 'CostUnit' specified for type 'Exact.Web.Api.Models.SubscriptionLine' is not valid** 

Thanks
