### ISSUE TITLE
Object moved

### ISSUE THREAD

**Issue by RienBijl** [picqer/exact-php-client#343]
`$customer = new \Picqer\Financials\Exact\Account($connection);
$customer->find(3037);
`

This returns for me: 
`
Fatal error: Uncaught Picqer\Financials\Exact\ApiException: Error 401: <html><head><title>Object moved</title></head><body> <h2>Object moved to <a href="/docs/Login.aspx?ReturnUrl=%2fapi%2fv1%2fcurrent%2fMe">here</a>.</h2> </body></html> in REDACTED/api/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php:605 Stack trace: #0REDACTED/api/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(211): Picqer\Financials\Exact\Connection->parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException)) #1 REDACTED/api/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Me.php(80): Picqer\Financials\Exact\Connection->get('https://start.e...') #2 REDACTED/public_html/api/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php(408): Picqer\Financials\Exact\Me->find() #3 REDACTED REDACTED/api/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php on line 605
`

Connection with exact is running, this ping-endpoint in my project tests the connection.
http://prntscr.com/micqjf

I read a previous issue which stated that I didn't store the authorizationcode correctly (too low max length), so I set that max-length to 900. Didn't resolve it.

Anybody an idea?

**Comment by alexjeen** [comment]
That error occurs for two reasons:

- Your access token is not correct
- You don't have access to the division
- You are accessing the wrong URL for the country (ie. start.exactonline.co.uk for UK)
