### ISSUE TITLE
 Deprecate Transactions API

### ISSUE THREAD

**Issue by davidvandertuijn** [picqer/exact-php-client#345]
> Deprecate Transactions API
> As of the 1st of April the “/financialtransaction/Transactions” API will be deprecated, meaning you can no longer use this API.
>  
> You are receiving this message because we can see that an application which is registered under your own account uses this API and is therefore effected by this change, please read this e-mail carefully and let us know if you have any further questions via the known communication channels.
>  
> Off course we would not do this in such a time frame before making sure there is a proper solution.
>  
> Currently the “/financialtransaction/TransactionLines” API has all the available fields/resources that were included in the “/financialtransaction/Transactions” API.
> Therefore it is already unnecessary to call the “/financialtransaction/Transactions” API.
>  
> Please see the TransactionLines API here: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=FinancialTransactionTransactionLines
>  
> Next to the “/financialtransaction/TransactionLines” API we have also launched a bulk endpoint.
> Bulk endpoints are capable of delivering 1000 records per call instead of the normal 60 records per call.
> You can find more information about the “/bulk/Financial/TransactionLines” endpoint via: https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkFinancialTransactionLines
>  
> The reason of the deprecation of this “/financialtransaction/Transactions” API has a lot to do with performance. The “/financialtransaction/Transactions” API was one of our first ever APIs created and is therefore currently outdated.
>  
> If you are not the developer of the application, please make sure that the supplier of the application which is registered under you account, receives this e-mail.
> 
>  
> Kind Regards,
>  
> Exact Online API Team

**Comment by florowebdevelopment** [comment]
https://github.com/picqer/exact-php-client/pull/353
