### ISSUE TITLE
After deleting browser cookies connection is getting lost

### ISSUE THREAD

**Issue by wasimman** [picqer/exact-php-client#347]
Hello Team,

 My exact online connection is getting lost if i am  deleting browser cookies and i need to re connect it, Can 
 you please have a look in to this or let me know if we have any solution on this.

 Thanks
 Wasim

**Comment by markjongkind** [comment]
Your Exact Online connection is made on the server with access tokens stored on your server (in JSON file or database). This has nothing to do with your browser or browser cookies.

When you make the first API connection, you need to give your app/server access to Exact and you need to log in via the browser. This is only needed once to setup the connection between Exact and your app/server.

It is possible that you are logged in via the browser (https://start.exactonline.nl), and after deleting cookies you are logged out. This doesn't matter, you don't have to be logged in to use the API from your server.

**Comment by wasimman** [comment]
Hello Mark Jongkind,

 We are storing access token in JSON file my problem is that when i am deleting cookies from the 
 browser then my connection is lost to API , So what could cause this?

 Thanks

**Comment by markjongkind** [comment]
Hi @wasimman,

As I said: this PHP library connects to Exact from your server, this has nothing to do with your browser or cookies. You store your access token in a JSON file on your server and when you want to use the Exact API, your PHP script uses the access tokens to connect to Exact. From your server to the Exact server, so without a browser and/or using cookies.

The API connection on your server uses access tokens from your JSON file.

You in your browser can be logged in to the Exact web app and this is handled via cookies, but has nothing to do with the API access on your server.
