### ISSUE TITLE
Download created invoice

### ISSUE THREAD

**Issue by sweebee** [picqer/exact-php-client#349]
I can't find it, but how do i download a created invoice?

I tried something with document, but it doesn't work.

**Comment by markjongkind** [comment]
You can try to find the Document attached to the SalesInvoice (`SalesInvoice->Document`), this is the GUID of the Document linked to the invoice.

If you request the Document data with this GUID, it has the field Attachments (`Document->Attachments`) with one or more attachments. Use the function `DocumentAttachment->download()` to get the file data.

**Comment by sweebee** [comment]
i retrieved a salesinvoice, but the Document attribute is always ```null```

**Comment by markjongkind** [comment]
@sweebee the [API documentation](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoiceSalesInvoices) says:

> Document   |   Edm.Guid   |   Document that is manually linked to the invoice


So if you don't manually link a document to your salesinvoice, the Document attribute will always be ```null```.

**Comment by sweebee** [comment]
Yes i know, but is there a way to download the created salesinvoice as pdf?

**Comment by markjongkind** [comment]
You can take a look at the [PrintedSalesInvoices](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoicePrintedSalesInvoices) entity in the API. This way, you can create and send a salesinvoice. This will generate a Document GUID and via this GUID you can retrieve the DocumentAttachments containing the data of the PDF file itself.

**Comment by sweebee** [comment]
Thx got it. Used the document id of the printedinvoice.

**Comment by PaulVanDeKamer** [comment]
Hi Sweebee,
I have the same issue. How did you manage to Use the documentid of the printedinvoice. Where did you find this id?
