### ISSUE TITLE
Fetch more than 60 results

### ISSUE THREAD

**Issue by robinvalk** [picqer/exact-php-client#35]
Hi,

I'm trying to fetch more than 60 results from the Exact API. I saw that you can limit the results using `$top` but how can I fetch a different "part" of the results.

Can't find anything in their documentation about pagination...

(Tried `$bottom` but that won't work obviously ^^)

Thanks.

**Comment by stephangroen** [comment]
According to Exact there should be a Skiptoken or TSPagingID on the API result which can be used to retrieve the next 60 items. I don't have an Exact account with over 60 items. Can you verify if this is correct and in the raw result from the API?

**Comment by robinvalk** [comment]
It's correct! I'll try to add it to the repo in a couple of weeks and create a PR. 60+ items also isn't our top priority, but would be nice if we could support it ;)

Thx for asking and responding!

**Comment by stephangroen** [comment]
Thanks, and I'll be happy to see the PR :dancers:

**Comment by vikrantbliss** [comment]
Can you please explain about "pass last received timestamp to get next page" . I have getting skiptoken url . For example "https://start.exactonline.nl/api/v1/{division}/crm/Accounts?$skiptoken=guid'123456-1234-1234-1234-123456789012'" . How to get next records .

**Comment by robinvalk** [comment]
There is no timestamp needed. The skiptoken url should work.

**Comment by vikrantbliss** [comment]
Please can you send one example how to pass skiptoken in url.

Thanks

**Comment by robinvalk** [comment]
See #42, it's already implemented.
