### ISSUE TITLE
How To - Save Sales Entry Line GUID's

### ISSUE THREAD

**Issue by florowebdevelopment** [picqer/exact-php-client#352]
I create a Sales Entry with Sales Entry Lines using `$oSalesEntry->addItem($aSalesEntryLine);`
But how do i save the GUID of the newly created sales entry lines ?

I try to create a Sales Entry withouth Sales Entry Lines, 
in order to add the Sales Entry Lines after one-by-one but this is NOT possible because at least one Sales Entry Line is required.

Perhaps its possible to fetch the Sales Entry Lines from a Sales Entry, how i do this ?

But then i face a new issue, how to match the Sales Entry Line back to the application's sales_invoice_lines, the description can occur multiple times so i have nothing unique. can you store your own id (any reference) in Sales Entry Lines somehow ?

**Comment by Christophvh** [comment]
Got a similar issue. Was able to create a SalesEntry without sales-entry-lines but that resulted in an empty EntryID so when I tried to create SalesEntries it asked for EntryID but that is always null

**Comment by Christophvh** [comment]
When doing $salesEntry->addItem(); you can add an array of sales entry-lines. This should auto-set the GUID
