### ISSUE TITLE
Refresh token doesn't seem to work in combination with php-resque

### ISSUE THREAD

**Issue by mcjansen** [picqer/exact-php-client#358]
We are using php-resque (https://github.com/mjphaynes/php-resque) to sync products in the background to Exact via the exact-php-client. We noticed that after 10 minutes the tokens are not refreshed. As a result, we get the infamous 'Could not connect to Exact: Could not acquire or refresh tokens' error similar to https://github.com/picqer/exact-php-client/issues/300

When I run the code without using php-resque it works fine. After 10 minutes the tokens are refreshed. 

Has anybody had similar issues? My guess is it has something to do with the forking that is used by php-resque.

**Comment by justijndepover** [comment]
Are you creating a job for each product or are you syncing all of your products inside one job?

**Comment by mcjansen** [comment]
We are creating a job for each product. We are seeing intermitting behavior. Recently, for example, yesterday we synced 10,000 products with three workers. Took about an hour. Worked flawlessly. After that, we started to sync customers and then after 10 minutes, we got the  'Could not connect to Exact: Could not acquire or refresh tokens'  error.

**Comment by mcjansen** [comment]
Just read https://github.com/picqer/exact-php-client/issues/359 where a similar issue appeared after upgrading to 3.18. Going back to 3.14 now to see if that resolves the issue.

**Comment by mcjansen** [comment]
Just tested with 3.14. The issue appears there as well. So it looks like it related to the combination of exact-php-client and php-resque

**Comment by mcjansen** [comment]
We finally found the solution based on a remark in https://github.com/picqer/exact-php-client/issues/359 from @davidvandertuijn where he suggested: "Please make sure you run requests in SEQUENTIAL order in order to save the new access-, and refresh token using setTokenUpdateCallback after each request." 

Since we started to use the **setTokenUpdateCallback** we haven't seen the _Could not connect to Exact: Could not acquire or refresh tokens'_ error.
