### ISSUE TITLE
Could not acquire or refresh tokens [http 401]

### ISSUE THREAD

**Issue by rowhel95** [picqer/exact-php-client#359]
After updating from v3.14 to latest v3.18 I get an exception when trying to refresh new token.
these are the versions used when installing composer package:
![composer](https://user-images.githubusercontent.com/17615589/56415225-67080380-628d-11e9-9e08-e4c444bccdf4.png)
I'm only able to make it work again after clearing authorization code, refresh token and access token
and then login again but after some time I get the same exception and it cant refresh tokens

**Comment by somegooser** [comment]
@stephangroen i also have the same problem since i have updated to v 3.18.

The refresh token seems to stop updating after a while (maximum 2 days, sometimes sooner).

Could not acquire or refresh tokens [http 401]

**Comment by somegooser** [comment]
when happy again?

**Comment by davidvandertuijn** [comment]
Please make sure you run requests in SEQUENTIAL order in order to save the new access-, and refresh token using setTokenUpdateCallback after each request.

Example below using Laravel:

`$oConnection->setTokenUpdateCallback('App\Classes\Exact::tokenUpdateCallback');`

```
/**
 * Token Update Callback.
 *
 * @param \Picqer\Financials\Exact\Connection $connection
 *
 * @return bool
 */
public static function tokenUpdateCallback(Connection $oConnection)
{
    $oExact = ExactModel::where('environment', '=', App::environment())->firstOrFail();

    $oExact->access_token = $oConnection->getAccessToken();
    $oExact->refresh_token = $oConnection->getRefreshToken();
    $oExact->token_expires = $oConnection->getTokenExpires();
    $oExact->division = $oConnection->getDivision();

    $oExact->save();

    return true;
}
```

**Comment by digitalrebelbv** [comment]
I still have this problem. After logging in to Exact I get a authorization code, but the rest stays empty in in the connection object. Which of course leads to the "Could not acquire or refresh tokens [http 400]" error message. Is there something I need to do in my Exact Account (a certain setting)?

**Comment by imuller** [comment]
Check issue #385  https://github.com/picqer/exact-php-client/issues/385
