### ISSUE TITLE
Change orderstatus for existing salesorder

### ISSUE THREAD

**Issue by jackmagielse** [picqer/exact-php-client#372]
I want to change the orderstatus of a salesorder to 20 after i retrieve it from the administration with status 12. I use the follwing php-code. I get no error but the change is not done.
What am i doing wrong?

try
{
   $l_salesorders = new \Picqer\Financials\Exact\SalesOrder($connection);
   $result = $l_salesorders->filter("Status eq 12");
   foreach ($result as $salesorder)
   {
      echo 'salesorder: ' . $salesorder->Description . ' ordernummer ' . $salesorder->OrderNumber . ' status ' . $salesorder->Status . ' ' . $salesorder->DeliveryStatus . '<br>';
      echo 'bijwerken<br>';
      $salesorder->Status = '20';
      $l_save_result = $salesorder->save();
      echo 'save resultaat ' . $l_save_result->Status . ' ' . $l_save_result->DeliveryStatus . '<br>';
   }
}
catch (\Exception $e)
{
   echo get_class($e) . ' : ' . $e->getMessage();
}

**Comment by markjongkind** [comment]
If you check the [SalesOrders API documentation](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrders), you'll see it's not possible to update (PUT) the `Status` property. 

As far as I know, the `Status` of a SalesOrder is a dynamic representation of the linked SalesOrderLines (and PurchaseOrderLines), delivery data, invoices, and more. Even in the Exact Online front-end, it's impossible to directly set a specific status for a SalesOrder.

**Comment by jackmagielse** [comment]
OK. Thanks.
Now i see how the documentation works. You only see the attributes which can be changed when you press the put/post buttons.
I already suspected it wasn't possible.

**Comment by DannyvdSluijs** [comment]
@jackmagielse this means your issue is solved and can be closed?
