### ISSUE TITLE
Getting all or searching for clients

### ISSUE THREAD

**Issue by timvanuum** [picqer/exact-php-client#39]
Hi there,

I'm completely new to Exact online. And I need to get all or search for clients in a application I'm making commissioned by my boss. Before downloading this and trying to make that work I want to ask if that is possible in the first place with this composer package? I can't seem to find anything like that in the examples.

I'm working with Laravel so this package would be ideal.

Thanks!

**Comment by timvanuum** [comment]
Ah, I see a find-able trait. Going to try this.

**Comment by stephangroen** [comment]
You can fetch all clients of search for them. For searching you can use something like this:

```php
        $account = new Account();
        $result = $account->filter('Name eq \'' . $name . '\'');
```

**Comment by timvanuum** [comment]
Awesome, just what I needed!

**Comment by timvanuum** [comment]
It's working and all. Great package love it already, but how can I search? I tried instead of 'eq' also like, contains, startswith. But none of them work. Keep getting: **Error 400: Expression of type 'System.Boolean' expected at position 0**.

**Comment by stephangroen** [comment]
Can you give a code snippet of the code where you get this error?

The filtering is described in the Exact Online API docs. This package just wraps it. Exact Online uses oData filters to search.

**Comment by timvanuum** [comment]
At the moment I'm trying something like **$result = $account->filter('substringof(Name, \'Tat\')');** but it says *Error 501: Not Implemented* 

Before I tried something like: **$result = $account->filter('Name contains \'Tat\'');**

**Comment by timvanuum** [comment]
Alright got it working with: `$result = $account->filter('startswith(Name, \'Tat\')');`.

But a containing search (substringof) would be better.

**Comment by timvanuum** [comment]
Fully fixed it with: `$result = $account->filter('substringof(\'Tat\', Name)');` had for the substringof method you have to turn the field and value around.

**Comment by stephangroen** [comment]
Nice! Great you solved it.
