### ISSUE TITLE
How to set Language header?

### ISSUE THREAD

**Issue by Taapo** [picqer/exact-php-client#391]
I have been trying to get the header function to work, but I think I'm making some mistakes.

For example GLAccount has the possibility to set CustomDescriptionLanguage -- but when I try with the code below, it just returns the language set when I created the administration.

```
try {
    $fetch = new \Picqer\Financials\Exact\GLAccount($connection);
    $results = $fetch->get(['$top'=> 100],['CustomDescriptionLanguage' => 'NL']);
    foreach ($results as $result) {
        echo $result->Code . " - " . $result->Description . "<br />";
    }
} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}
```

**Comment by Taapo** [comment]
Any tips?

**Comment by Zombaya** [comment]
I was stuck with this as well and have found that this works:

```php
use GuzzleHttp\Middleware;
use Picqer\Financials\Exact\Connection;

$connection = new Connection();
$connection->insertMiddleWare(Middleware::mapRequest(static function (RequestInterface $request) {
    return $request->withHeader('CustomDescriptionLanguage', 'NL');
}));
```

I did not find the documentation for `CustomDescriptionLanguage` so if anyone can point me in the right direction, that would be very helpful.
