### ISSUE TITLE
Communication notes

### ISSUE THREAD

**Issue by advacom** [picqer/exact-php-client#400]
Hello all,

I'm trying to insert a communicationNote: [Exact docs](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ActivitiesCommunicationNotes
)
I tried the following : 
```
	$note = new \Picqer\Financials\Exact\CommunicationNotes($connection);
	$note->Account  = $created_id;
	$note->Notes 	= 'Dit is een note';

	$test3 = $note->save();
```

It keeps returning a Fatal 
`Fatal error: Class 'Picqer\Financials\Exact\CommunicationNotes' not found` 
I've checked the picqer directories but it seems there is no class that handles the CommunicationNotes.

Would be great if anybody could help me out!

Thanks in advance,

**Comment by markjongkind** [comment]
The `CommunicationNotes` are not (yet) available as a class in this Exact client. You can check which classes are available in [this list](https://github.com/picqer/exact-php-client/tree/master/src/Picqer/Financials/Exact).

You can add the class for CommunicationNotes yourself and use it.
