### ISSUE TITLE
Filter SalesEntry and delete

### ISSUE THREAD

**Issue by SativaNL** [picqer/exact-php-client#401]
I am having difficulties with the following method.
I want to search for a salesentry and then remove it:

        $api = new \Picqer\Financials\Exact\SalesEntry($this->connection);
        $data = $api->filter("EntryID eq guid'" . $key . "'");
        var_dump($api->delete());

The error I get:
DELETE https://start.exactonline.nl/api/v1/2307308/salesentry/SalesEntries(guid'')` resulted in a `400 Bad Request

How can I pass the guid (EntryID) from the filter?

Thanks!

**Comment by NexumIT** [comment]
Anyone?

**Comment by joren-etw** [comment]
I did this by defining the endpoint - I think this should be available through the ->getUrl() function but somehow that does not work for me - and executing a delete request the following way

```
$api = new \Picqer\Financials\Exact\SalesEntry(self::$eoConnection);
$url = 'salesentry/SalesEntries';
$ticketData = self::$eoConnection->Delete(
      $url . "(guid'$entryId')"
);
```

**Comment by NexumIT** [comment]
Thanks! It worked for me.
