### ISSUE TITLE
How can i update Account record?

### ISSUE THREAD

**Issue by dwaynehertroys** [picqer/exact-php-client#402]
For adding new accounts to Exact Online im doing this:
`
// Create a new account
$account = new Picqer\Financials\Exact\Account($connection);
$account->AddressLine1 = $customer['address'];
$account->AddressLine2 = $customer['address2'];
$account->City = $customer['city'];
$account->Code = $customer['customerid'];
$account->Country = $customer['country'];
$account->IsSales = 'true';
$account->Name = $customer['name'];
$account->Postcode = $customer['zipcode'];
$account->Status = 'C';
$account->save();
`

But now, how can i update this record? So for example, how to change the name?

**Comment by NexumIT** [comment]
When you save for the first time, you have to get the ID: $account->ID(), and save this in your database (as external_id in this example).

When updating the next time you set this and save:
$account->ID = $customer['external_id'];
$account->save();
