### ISSUE TITLE
Download / Print a normal Sales Order

### ISSUE THREAD

**Issue by PaulVanDeKamer** [picqer/exact-php-client#415]
You can take a look at the [PrintedSalesInvoices](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoicePrintedSalesInvoices) entity in the API. This way, you can create and send a salesinvoice. This will generate a Document GUID and via this GUID you can retrieve the DocumentAttachments containing the data of the PDF file itself.

_Originally posted by @markjongkind in https://github.com/picqer/exact-php-client/issues/349#issuecomment-473245654_

How can i get the document id of the printedinvoice.  
Just want to download invoices... and i am realy Stuck!

Hope that there is someone who can provide a sample.

**Comment by roland-d** [comment]
Not sure if this helps but this is how I do it:
```
$account = new Account($this->connection);
$result = $account->filter("Email eq '" . $email . "'");
$document = new Document($this->connection);
$documents = $document->filter("Account eq guid'" . $result[0]->ID . "'");
// Loop through the documents
$documentAttachment = new DocumentAttachment($this->connection);
$attachments = $documentAttachment->filter("Document eq guid'" . $document->ID . "'");
```

Very basic but it should get you going.
