### ISSUE TITLE
Exact no longer updating customers

### ISSUE THREAD

**Issue by roland-d** [picqer/exact-php-client#416]
So I have this connection with Exact running for over a year and all is fine and dandy until recently. One issue I dropped with Exact as the invoices are using the wrong layout but my other issue I wanted to check here.

I send customer info from my website to Exact online. If the customer exists, it will be updated. Since 2 days, I keep getting the error `Error 500: Gegeven bestaat reeds.` (entry already exists).

The process is as follows, I request the account from Exact based on email address, this gives me the user account. I update some info in this account and then call `save()`. This checks if the ID exists or not, if so an update via `PUT` is done.

Did something break on Exact side or do I need to change something?

This code hasn't been touched in a long time and was running fine. Thanks for any pointers.

**Comment by DannyvdSluijs** [comment]
You might not be aware but this is only an PHP implementation of the exact api. Which isn’t maintained by exact itself but by people of the OSS community. If you’re in need of support you should contact them though other means.  

Hoping to be helping this way even though it feels like sending you off, be it in the correct direction.

**Comment by roland-d** [comment]
@DannyvdSluijs I am aware that this is an OSS community and I will contact Exact when needed. I guess my wording was a bit blurred as I am not quite sure what I wanted to ask. Basically it comes down to, is it down for me or for everyone? :) If updating accounts work for other people, it clearly is something on my end.

If there is something broken in this library, we could look at fixing it. If it is just me, I will have to look elsewhere.

I don't feel like being send off and understand and follow the reasoning. As I said, I only came here to check if it is me or a general issue that may need to be fixed for everybody.

**Comment by roland-d** [comment]
Thank you for listening, today there is no such problem anymore. The wonders of the internet :)

**Comment by roland-d** [comment]
Just an update, I finally figured out what was the root cause here. I was filling the `Account->Code` with a value of an existing customer. This will generate this error. After sorting out the codes, all works as expected.
