### ISSUE TITLE
Update to current API

### ISSUE THREAD

**Issue by vdlp-mw** [picqer/exact-php-client#418]
Sorry for creating a separate issue for this but I was wondering when https://github.com/picqer/exact-php-client/pull/386/ could be merged? All feedback has been processed and there appear to be no merge conflicts.

We require some of the newer endpoints / fields available in the exact API but that are unavailable in the library. We've forked from jeff's PR and are now running that in production which is not desirable..

Thanks in advance!

**Comment by stephangroen** [comment]
Done: v3.24.0
