### ISSUE TITLE
itemId={Edm.Guid} param

### ISSUE THREAD

**Issue by Nico-uncinc** [picqer/exact-php-client#424]
Hi,

In the url for some models like `ItemDetailsByID`, the ItemId is already passed as a param including a placeholder, like so:

```protected $url = 'read/logistics/ItemDetailsByID?itemId={Edm.Guid}';```

How would you do a `get()` call for a model like this?

So far I've been using the `get()` function like this for retrieving information from every model, but here that doesn't work anymore. 

```$item_details = $item_details->get(['itemId' => "guid'$id'"]);```

Removing the param from the url like so makes it work again with the above line.

```protected $url = 'read/logistics/ItemDetailsByID';```

So is this a bug or am I just not fully understanding how to properly get these models?

**Comment by bedrijfsportaal** [comment]
Same issue here, solved it by removing the ?itemId={Edm.Guid} from the URL part. After this everything is working as expected.

**Comment by svansteenkiste** [comment]
Hi,

unfortunately, after your fix, i still cannot get this working for ItemDetailsByID

protected $url = 'read/logistics/ItemDetailsByID?itemId={Edm.Guid}';

Hope someone can help me on the right way to pass the Guid on a correct way 

$details = new \Picqer\Financials\Exact\ItemDetailsByID($connection);
$prodDetails = $details->get(???);

**Comment by bedrijfsportaal** [comment]
You can use array values;
```php
$prodDetails = $details->get([
    'itemId'  => "guid'{$prodGuid}'",
    '$select' => "Code,Description,IsFractionAllowedItem,IsSalesItem,SalesCurrency,SalesPrice"
]);

**Comment by svansteenkiste** [comment]
> You can use array values;
> 
> ```
> $prodDetails = $details->get([
>     'itemId'  => "guid'{$prodGuid}'",
>     '$select' => "Code,Description,IsFractionAllowedItem,IsSalesItem,SalesCurrency,SalesPrice"
> ]);
> ```

hi,,

thx for quick reply, unfortunately, i'm getting this error then:

Picqer\Financials\Exact\ApiException : Error 400: Bad Request - Error in query syntax.

**Comment by bedrijfsportaal** [comment]
Can you remove the dollar sign from the select, i think the library takes care of that part.

**Comment by svansteenkiste** [comment]
still same error

**Comment by bedrijfsportaal** [comment]
Same issue here, @casperbakker any suggestions on this?

**Comment by DannyvdSluijs** [comment]
I've created a PR (#529) which applies the fix mentioned by @bedrijfsportaal in https://github.com/picqer/exact-php-client/issues/424#issuecomment-659430900. As #467 was never merged the issue was never solved. But at this moment I'm realising this is breaking other code which was introduced in #478
