### ISSUE TITLE
500 error when updating Item

### ISSUE THREAD

**Issue by JonathanWebNL** [picqer/exact-php-client#425]
When updating an item Exact returns a generic 500 error. This is caused by the "IsSerialNumberItem" field. This field is obsolete and apparently Exact breaks when you send this field. 

Example code:
```php
$item = $item->find($product->exact_id);
$item->save();
```

We made a new Item class which removes the "IsSerialNumberItem" from the fillable as a temporary fix. We do not use the IsSerialNumberItem, so it does not need to be filled.

Code for temporary fix:
```php
namespace App\Models\Exact;


use Picqer\Financials\Exact\Connection;
use Picqer\Financials\Exact\Query\Findable;

/**
 * Class Item
 * @package App\Models\Exact
 */
class Item extends \Picqer\Financials\Exact\Item
{
    use Findable;

    /**
     * Item constructor.
     * @param Connection $connection
     * @param array $attributes
     */
    public function __construct(Connection $connection, array $attributes = [])
    {
        // Remove IsSerialNumberItem from fillable because this attribute causes a 500 error in exact when saving
        if(($key = array_search('IsSerialNumberItem', $this->fillable))) {
            unset($this->fillable[$key]);
        }

        parent::__construct($connection, $attributes);
    }
}
```

A possible permanent fix could be to add an `$ignore` property in which you can define attributes which are fillable, but shouldn't be used in requests to Exact. Then this property can be checked in the `->json()` method. This way implementation which still use the IsSerialNumberItem won't break, but `->save()` will also work.

**Comment by bvweijen** [comment]
`+1`
Had the same issue today! I'll try your fix for now. Thanks!

**Comment by remkobrenters** [comment]
@DannyvdSluijs as I think this can occur in other entities with obsolete properties as well: do you think it is technically possible (and a valid addition) to automatically detect 'obsolete' fields from the documentation and put them in a new array like `$obsoletes` (not really fancying the name but consistency is nice) which could be automatically filtered out in the filling process.

**Comment by DannyvdSluijs** [comment]
The [PicqerExactPhpClientGenerator](https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator) is aware of obsolete properties but perhaps the [implementation](https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator/blob/23d0a54bd2fae0fc82cde9c3bc5759ec635af976/src/Decorator/EndpointDecorator.php#L39) is a bit simple and could be improved upon.

However in this case it is odd that the fields wasn't removed as the original docs no longer contain such a field and therefor should be removed when running the tool. Something I'll have to look into.

**Comment by DannyvdSluijs** [comment]
After spending some time I've found that ExactOnline hides lines in their documentation (`style="display: none;"`).
The `IsSerialNumberItem` is part of the HTML as follows:
```
<tr class="hiderow hidedelete" style="display: none;">
	<td>
		<input type="checkbox" class="showget" name="IsSerialNumberItem" data-type="Edm.Boolean" data-isnavigation="False" data-key="False" data-hidden="True" onclick="updateGetExample(); updateEntityExpand();">
	</td>
	<td data-sortdata="IsSerialNumberItem">IsSerialNumberItem</td>
	<td class="showMandatory" data-sortdata="False" style="display: none;">False</td>
	<td class="showpost" style="display: none;">
		<input class="" type="text" name="IsSerialNumberItem" data-type="Edm.Boolean" onchange="updatePostOrPutExample('#examplePostJson', 'tr .showpost :text');" placeholder="false">
	</td>
	<td class="showput" style="display: none;">
		<input type="text" name="IsSerialNumberItem" data-type="Edm.Boolean" onchange="updatePostOrPutExample('#examplePutJson', 'tr .showput :text');" placeholder="false">
	</td>
	<td data-sortdata="Edm.Boolean">
		<a href="http://www.odata.org/documentation/odata-version-2-0/overview/#AbstractTypeSystem" target="_blank">Edm.Boolean </a>
	</td>
	<td class="webhook-content" data-sortdata="False"></td>
	<td class="webhook-content" data-sortdata="False"></td>
	<td>This property is obsolete. Use property 'IsSerialItem' instead.</td>
</tr>
```

Two thing I plan to do
- Improve the detection of the word obsolete as part of the description, Ref https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator/blob/23d0a54bd2fae0fc82cde9c3bc5759ec635af976/src/Decorator/EndpointDecorator.php#L34-L42
- Improve the meta data crawler to skip non visible lines as those aren't visible to human readers anyway. Ref: https://github.com/DannyvdSluijs/exact-online-meta-data-tool/blob/develop/MetaDataTool/DocumentationCrawler.php#L99-L100

Once one of these fixes is in place I can make another run.
