### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by sujeetthete** [picqer/exact-php-client#428]
Hello
I am getting an error when i am creating the Cost Center, but i am surprised because this error automatically disappears after some time and Cost Center created successfully. But the problem is the error occurs and disappears without any changes. Following errors occurs while i am creating the cost center OR fetching the cost center.

Uncaught exception 'Picqer\Financials\Exact\ApiException' with message 'Error 401: '

**Comment by valuco** [comment]
I am having the exact same problem!
We use this client for searching the crm/Accounts sections.
