### ISSUE TITLE
read the available price lists in Exact

### ISSUE THREAD

**Issue by softna** [picqer/exact-php-client#430]
You have this API endpoint "SalesPriceListDetails" which is the only way to read the available price lists in Exact, but this endpoint is all combinations between customers , price lists and products. This endpoint can result in a very large amount of data and it consumes the daily API rates and the data can grow exponentially as we add more customers and products ! We would need an endpoint where we can get only the combination between products and price lists, so we know which product has what discount in a specific price list through API. You have this working in your portal (SlsPriceListRangeCard), but not in API (at least not in documentation). Or maybe you could at least add in your API endpoint "SalesPriceListDetails" the possibility to filter out the zero Discount and null NewPrice from the endpoint.

**Comment by DannyvdSluijs** [comment]
Hello @softna. 
This repository is open source PHP implementation of the ExactOnline API. For the type of question your asking you need to reach out to ExactOnline through the appropriate support channels listed on their site.  Sorry we cannot be of help.

**Comment by softna** [comment]
Thank you, for the quick reply. I will contact Exact regarding this issue.
