### ISSUE TITLE
Updating account returns a 500 "Gegeven bestaat reeds" error

### ISSUE THREAD

**Issue by jonmldr** [picqer/exact-php-client#432]
The API request returns a 500 "Gegeven bestaat reeds" error while trying to update an account, which is correct, because the account _does_ exist.

`Account::exists()` returns `true` and a PUT request is sent, which should be correct.

Can anybody help?

**Comment by jsomhorst** [comment]
Share some code please

**Comment by voicecode-bv** [comment]
I just ran into the same issue and noticed that it fails when you update the Code property, even though is the same value.

```
$account->Code = $this->id;
```
