### ISSUE TITLE
How to fetch the opening balance using API

### ISSUE THREAD

**Issue by sujeetthete** [picqer/exact-php-client#439]
Hello,

I want to fetch the opening balance using the API. I have try to fetched the Transactions with type 10, but it's not fetching the opening balance transaction. Could you please help me.

**Comment by meckyp** [comment]
Do you mean this one?
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=OpeningBalanceCurrentYearProcessed

**Comment by alexjeen** [comment]
Best to use XML API Balances endpoint to get a full consolidation, including these OB/ entries.

**Comment by remkobrenters** [comment]
Both answers are valid and should work. I will close this issue.
