### ISSUE TITLE
Get 'reason' header on 403 Forbidden

### ISSUE THREAD

**Issue by arwinvdv** [picqer/exact-php-client#447]
Is there a way to get the reason header out of the thrown exception when you get a 403 Forbidden response?

Following this [documentation](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-respcodeserrorhandling) you can see that there is an extra response header added on a 403 Forbidden response.

I try it to get is like this, but the catch isn't catching the ClientException becase a ApiException is thrown without response data:
```php
            $paymentCondition = new PaymentCondition($this->handler);
            $paymentCondition->Code = 14;
            $paymentCondition->Description = '14 days';
            $paymentCondition->PaymentDays = 14;
            try {
                $paymentCondition->save();
            } catch (\GuzzleHttp\Exception\ClientException $exception) { // Don't work
                Log::error('PaymentCondition error: ' . print_r($exception->getResponse()->getHeaders(), true));
            }
            catch (\Picqer\Financials\Exact\ApiException $exception) { // Catches the exception but no response headers available
                //Log::error('PaymentCondition error: ' . $exception->getMessage());
            }
```

Any ideas to get the reason header? Or is this a new feature to add in the lib?

**Comment by barryvdh** [comment]
See #451 which adds it.

The ClientException is the 'previous' exception. You can get it by catching the ApiException en then `$exception->getPrevious()`
