### ISSUE TITLE
Update Subscription Line

### ISSUE THREAD

**Issue by pepijndik** [picqer/exact-php-client#450]
I am trying to update a subscription and its Lines :
 But it does'nt update on the exact side
what i tried: 

```php
$connection = app()->make('Exact\Connection');
 $sub = new Subscription($connection);
 $sub->EntryID = $order->id; 
  for ($x = 0; $x < $count_items; $x++) {
            $r_lines[] = [
                'EntryID' => '{'.$order->id.'}',
                'Item' => $request['product'][$x], //Exact Product ID
                'Discount' => str_replace(',', '.', $request['discount'][$x]), //Discount in Percentage
                'FromDate'=>  $request['start_rental'][$x],
                'ToDate' => $request['end_rental'][$x]
            ];
}
  $sub->SubscriptionLines = $r_lines;
            $sub->save();
```

When i try to update  it works  for all other fields,
but not for the subscription lines  they aren´t updated 
Any one a idea how i can update the Subscription lines?

When i created the subscription i have done it like this:
The $lines =  The same as above 
```php
 $sub = new Subscription(app()->make('Exact\Connection'));
        $sub->Created = now(); //Get current date time
        $sub->InvoiceTo = $to_id; //Subscription to
        $sub->StartDate =find_closest($request['start_rental'],date('Y-m-d'));
        $sub->InvoicingStartDate =find_closest($request['start_rental'],date('Y-m-d'));
        $sub->SubscriptionType = $request['subscription_type']; //Guid ID of Sub type
        $sub->OrderedBy = $to_id;
        $sub->SubscriptionLines = $lines;
        $sub->save();
```

I used this same way for updating a relation/ account and that work as i expected. 

Hopse some one has a idea :-)

**Comment by remkobrenters** [comment]
On creation you can provide an array with lines but when updating you need to use the `SubscriptionLine` endpoint and perform a PUT providing the ID of the `SubscriptionLine` you want to update. 

See also https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptions and https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptionLines.
