### ISSUE TITLE
What is the easiest way to run this PHP client?

### ISSUE THREAD

**Issue by 888ba8** [picqer/exact-php-client#459]
Hi,

I am a bit new with regads to REST APIs and PHP clients. What is the easiest way for me to run this PHP client please?
And can you briefly explain its use?

Kind regards.

**Comment by jsomhorst** [comment]
What is your use case?

**Comment by DannyvdSluijs** [comment]
This client isn’t a standalone client. There isn’t anything you can run or execute. It is an open source library which you can use in your PHP application. 

I’m afraid we aren’t here to help you get started with REST API’s in general. I would recommend reading the official ExactOnline API to get some basic understanding in what this API offers you.

**Comment by Christophvh** [comment]
Guzzle is a good way to start.
