### ISSUE TITLE
Webhook and recurring "Could not acquire or refresh tokens"

### ISSUE THREAD

**Issue by DePalmo** [picqer/exact-php-client#460]
Not long ago we discussed the issue with "Could not acquire or refresh tokens" under #385 and after I updated my code, it looked like it was solved. but the joy was shortly lived. Right now I am again experiencing this issue but it looks like it's pooping up randomly. I integrated all said in the #385 and the code works fine for about 95% of the time, it even handles multiple calls from ExactOnline properly (not executing code in parallel, but waiting for other process to finish), but as said, I still see the mentioned issue from time to time. Because of this, I also implemented that if this happens, our server responds with 500 so that ExactOnline's Webhook re-sends the data later.

This is why I would like to know on how exactly and properly to use Webhook and multiple calls to it. I thought I understand it, but it would look like I am missing something.

Our environment is core PHP (for now, will move to Laravel at some point) and it goes like this:
- a single user is responsible to connect ExactOnline to our app and only one user can do it
- that user can successfully authenticate ExactOnline
- when authenticated, code requests for tokens and also checks if a Webhook Subscription (for Topic "Accounts" only) exists
- if it does not, it creates it (code below)
- then the code is waiting for incoming calls from Webhook, updated this code with suggestions in #385
- once it receives the requests, it checks it out if its authorized and then calls ExactOnline to pull the data and process it on our end
- then the code responds with 200 or 500

If someone has some free time, would really appreciate if he or she can check out my code and let me know where I went wrong.
Cache I am using is phpFastCache 7.0 and it is initialized like this:
```
use \Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException;

try {
	CacheManager::setDefaultConfig(new Config([
		'path' => dir_root . '_cache',
		"itemDetailedDate" => false,
		'secureFileManipulation ' => true
	]));
} catch (PhpfastcacheInvalidConfigurationException $e) {
} catch (ReflectionException $e) {
}
$cache = new Psr16Adapter('Files');
```
Cache could easily be replaced with flock, but since I am already using it in the project, decided to use it here too.

So, the request comes to `/exact-online-webhook`, then it includes the `webhook.php` and calls `clients_webhook()` (please note that I removed some code that's debugging related ... it merely logs different states into .txt file, does not interfere how the code works):
```
define('webhook', true);

require_once(dir_root . 'classes/sync.php');
use \Picqer\Financials\Exact\Account;

function clients_webhook()
{
	global $exact_credentials;
	$input = file_get_contents('php://input');

	$authState = authenticate($input, $exact_credentials['webhook_secret']);
	$data = json_decode($input, true);

	if ($authState) {
		try {
			$connection = connect();

			if ($connection !== false) {
				$CRMClients = new Account($connection);
				$clients = $CRMClients->filter("ID eq guid'" . $data['Content']['Key'] . "'", '', 'ID,AddressLine1,AddressLine2,City,Country,CountryName,Created,Email,Language,MainContact,Modified,Name,Phone,PhoneExtension,Postcode,Status');

				$results = [];

				foreach ($clients as $client) {
					$data = [
						':exact_id' => $client->ID,
						':url' => URLify::filter($client->Name),
						':company_name' => (!empty($client->Name) ? trim($client->Name) : ''),
						':address' => (!empty($client->AddressLine1) ? trim($client->AddressLine1) : '') . (!empty($client->AddressLine2) ? ' ' . trim($client->AddressLine2) : ''),
						':postalcode' => (!empty($client->Postcode) ? trim($client->Postcode) : ''),
						':city' => (!empty($client->City) ? ucwords(trim($client->City)) : ''),
						':country' => (!empty($client->Country) ? trim($client->Country) : ''),
						':country_id' => (!empty($client->Country) ? get_country_id(trim($client->Country)) : 0),
						':telephone' => (!empty($client->Phone) ? trim($client->Phone) : ''),
						':email' => (!empty($client->Email) ? trim($client->Email) : '')
					];

					if (save_client($data)) {
						$results[] = true;
					} else {
						$results[] = false;
					}
				}

				setValue('last_exact_online_sync', date('Y-m-d\TH:i:s', time()));
			} else {
				return false;
			}
		} catch (Exception $e) {
			trigger_error('connection for webhook failed: ' . $e->getMessage());
			return false;
		}
	} else {
		return false;
	}
}
```

`sync.php`:
```
use Phpfastcache\Exceptions\PhpfastcacheSimpleCacheException;
use Picqer\Financials\Exact\Connection;
use Picqer\Financials\Exact\WebhookSubscription;
use Picqer\Financials\Exact\Account;

if (defined('webhook') === true) {

	require_once(dir_root . 'vendor/autoload.php');

	function getValue($key)
	{
		global $pdo;

		if (in_array($key, [
			'authorizationCode',
			'webhook_subscribed',
			'accessToken',
			'refreshToken',
			'last_exact_online_sync'
		])) {
			try {
				$db = $pdo->prepare("SELECT
					`configuration`.`$key`
					FROM `configuration`
					WHERE `configuration`.`id` = 1");
				$db->execute();
				if ($db->rowCount() > 0) {
					return $db->fetchColumn();
				} else {
					return false;
				}
			} catch (PDOException $e) {
				trigger_error("MySQL get value from DB error: " . $e->getMessage());
			}
		}

		return false;
	}

	function setValue($key, $value)
	{
		global $pdo;

		if (in_array($key, [
			'authorizationCode',
			'webhook_subscribed',
			'accessToken',
			'refreshToken',
			'expiresIn',
			'last_exact_online_sync'
		])) {
			try {
				$p = [':value' => $value];
				$db = $pdo->prepare("UPDATE `configuration` SET `configuration`.`$key`=:value WHERE `configuration`.`id` = '1'");
				$db->execute($p);
				return true;
			} catch (PDOException $e) {
				trigger_error("MySQL set value into DB error: " . $e->getMessage());
			}
		}

		return false;
	}

	function authorize($returnUrl = null)
	{
		global $exact_credentials;
		$connection = new Connection();
		$connection->setRedirectUrl($exact_credentials['redirect_url']);
		$connection->setExactClientId($exact_credentials['client_id']);
		$connection->setExactClientSecret($exact_credentials['client_secret']);

		return $returnUrl ? $connection->getAuthUrl() : $connection->redirectForAuthorization();
	}

	function connect()
	{
		global $exact_credentials, $cache;

		$connection = new Connection();
		$connection->setRedirectUrl($exact_credentials['redirect_url']);
		$connection->setExactClientId($exact_credentials['client_id']);
		$connection->setExactClientSecret($exact_credentials['client_secret']);

		$authorizationCode = getValue('authorizationCode');
		if (!empty($authorizationCode)) {
			$connection->setAuthorizationCode($authorizationCode);
		}

		$accessToken = getValue('accessToken');
		if (!empty($accessToken)) {
			$connection->setAccessToken($accessToken);
		}

		$refreshToken = getValue('refreshToken');
		if (!empty($refreshToken)) {
			$connection->setRefreshToken($refreshToken);
		}

		$expiresIn = getValue('expiresIn');
		if (!empty($expiresIn)) {
			$connection->setTokenExpires($expiresIn);
		}

		$connection->setTokenUpdateCallback(function ($connection) {
			setValue('accessToken', $connection->getAccessToken());
			setValue('refreshToken', $connection->getRefreshToken());
			setValue('expiresIn', $connection->getTokenExpires() - (2 * 60));
		});

		$connection->setRefreshAccessTokenCallback(function ($connection) {
			$connection->setAccessToken(getValue('accessToken'));
			$connection->setRefreshToken(getValue('refreshToken'));
			$connection->setTokenExpires(getValue('expiresIn'));
		});

		$connection->setAcquireAccessTokenLockCallback(function () {
			return mutex_lock();
		});

		$connection->setAcquireAccessTokenUnlockCallback(function () {
			return mutex_unlock();
		});

		try {
			$connection->connect();

			/*
						setValue('accessToken', $connection->getAccessToken());
						setValue('refreshToken', $connection->getRefreshToken());
						setValue('expiresIn', $connection->getTokenExpires() - (2 * 60));
			*/

			webhookSubscribe($connection);

			return $connection;
		} catch (Exception $e) {
			trigger_error('Could not connect to Exact: ' . $e->getMessage());

			return false;
		}
	}

	function check_if_client_exists($id)
	{
		global $pdo;

		try {
			$p = [':exact_id' => $id];
			$db = $pdo->prepare("SELECT
				`clients`.`id`
				FROM `clients`
				WHERE `clients`.`exact_id`=:exact_id");
			$db->execute($p);
			if ($db->rowCount() > 0) {
				return true;
			} else {
				return false;
			}
		} catch (PDOException $e) {
			trigger_error("MySQL check if client exists in DB error: " . $e->getMessage());
			file_put_contents(ini_get('error_log'), print_r($p, true), FILE_APPEND);

			return false;
		}
	}

	function save_client($data)
	{
		global $pdo;

		$client_exists = check_if_client_exists($data[':exact_id']);
		try {
			$sql = MySQLString($data);
			$db = $pdo->prepare("INSERT INTO `clients` ({$sql[0]}) VALUES ({$sql[1]}) ON DUPLICATE KEY UPDATE {$sql[2]}");
			$db->execute($data);

			return true;
		} catch (PDOException $e) {
			trigger_error("MySQL save new or update existing client error: " . $e->getMessage());
			file_put_contents(ini_get('error_log'), print_r($data, true), FILE_APPEND);

			return false;
		}
	}

	function authenticate($requestContent, $webhookSecret)
	{
		$matches = [];
		$matched = preg_match('/^{"Content":(.*),"HashCode":"(.*)"}$/', $requestContent, $matches);

		if ($matched === 1 && isset($matches[1]) && isset($matches[2])) {
			return $matches[2] === strtoupper(hash_hmac('sha256', $matches[1], $webhookSecret));
		}

		return false;
	}

	function mutex_lock()
	{
		global $cache;

		for ($i = 0; $i < 90 && $cache->has('exact-locked'); $i++) {
			sleep(1);
		}

		if (!$cache->set('exact-locked', true, 60)) {
			trigger_error('Mutex: unable to get a lock for new request!');
		}

		return true;
	}

	function mutex_unlock()
	{
		global $cache;

		return $cache->delete('exact-locked');
	}

	function webhookSubscribe($connection)
	{
		if (empty(getValue('webhook_subscribed'))) {
			try {
				$Webhook = new WebhookSubscription($connection);
				$Webhook->CallbackURL = site_domain_full . '/api/v1/exact-online-webhook/v2';
				$Webhook->Topic = 'Accounts';
				$Webhook->save();

				setValue('webhook_subscribed', 1);
			} catch (Exception $e) {
				trigger_error('Unable to set Webhook Subscription: ' . $e->getMessage());
			}
		}
	}
}

```

Using PHP v7.4, exact-php-client v3.26.0

**Comment by DePalmo** [comment]
Changed the workflow a bit, since I am still lost on how to properly utilise webhooks. Right now when data comes into webhook, it is stored into database. Then a CRON job is run every minute that checks for updates and process them.

For the moment, no errors. Hope it stays that way.

**Comment by paqio** [comment]
There is definitely something wrong with it, I opened the #385 issue a few years ago and it still goes bad. 

The issue appears when there is an error response from Exact after the expiration of accessToken time. The tokenRefreshCallback is called, and everything is saved but actually, the database isn't updated. @stephangroen @MaartenWaegeman mby you have a quick idea of why. Works if Exact request goes good

**Comment by MaartenWaegeman** [comment]
> 
> 
> There is definitely something wrong with it, I opened the #385 issue a few years ago and it still goes bad.
> 
> The issue appears when there is an error response from Exact after the expiration of accessToken time. The tokenRefreshCallback is called, and everything is saved but actually, the database isn't updated. @stephangroen @MaartenWaegeman mby you have a quick idea of why. Works if Exact request goes good

To get a proper refresh from multiple processes you should implement 4 callback functions:
- acquireAccessTokenLockCallback -> create the atomic / mutex lock
- acquireAccessTokenUnlockCallback -> release the atomic / mutex lock
- tokenUpdateCallback -> save the new received tokens from Exact to the database
- refreshAccessTokenCallback -> retrieve the tokens that might have been refreshed by another process from the database and set them in the connection

My callback functions look like this (Laravel)

``` php
public function aquireAccessTokenLock(Connection $connection){ // setAcquireAccessTokenLockCallback
    try {
        $this->atomicLock->block(30);
        // Lock acquired after waiting maximum of 30 seconds...

    } catch (LockTimeoutException $exception) {
        throw new ApiException('Exact Online Connector: Could not acquire the atomic lock to refresh the OAuth tokens, the lock timed out.');
    }
}

public function releaseAccesTokenLock(Connection $connection){ //  setAcquireAccessTokenUnlockCallback
    optional($this->atomicLock)->release();
}

public function updateAccessToken(Connection $connection) // setTokenUpdateCallback
{
     // save token to the database
    $this->oAuthToken->update([
        'access_token' => $connection->getAccessToken(),
        'refresh_token' => $connection->getRefreshToken(),
        'expires_in' => $connection->getTokenExpires()
    ]);
}

public function refreshAccesToken(Connection $connection){ // setRefreshAccessTokenCallback
    // fetch token fresh from the database and set the values in the connection
    $this->oAuthToken->refresh();

    $connection->setAccessToken($this->oAuthToken->access_token);
    $connection->setRefreshToken($this->oAuthToken->refresh_token);
    $connection->setTokenExpires($this->oAuthToken->expires_in);
}
```

**Comment by DePalmo** [comment]
I know that I pasted a lot of code, but I integrated exactly like that. And still got "Could not acquire or refresh tokens" for about 1% of requests. Sometime the next request(s) works OK and sometimes I see a hard failure, where I need to re-authenticate with EO.

**Comment by MaartenWaegeman** [comment]
@DePalmo I have found that the  "Could not acquire or refresh tokens" happens when you have 2 simultaneous token refresh calls to the Exact API. The Exact API will return 2 different tokens, so you have a 50/50 chance of the correct token being stored in the database. If the wrong token is stored, you get the issues you are describing. My best guess is that maybe something with your mutex goes wrong.

Laravel's mutex implementation is as follows: (https://github.com/illuminate/cache/blob/b06099606f544c4bd2827a19242548e9099e2742/Lock.php#L112)

```php
public function block($seconds, $callback = null)
{
    $starting = $this->currentTime();

    while (! $this->acquire()) {
        usleep($this->sleepMilliseconds * 1000);

        if ($this->currentTime() - $seconds >= $starting) {
            throw new LockTimeoutException;
        }
    }
...
}
```
I've had issues with the sleep/usleep function sometimes not behaving like I expect them to. Laravel solves this by actually relying on timestamps, to make sure when you say sleep(5) that the function actually sleeps for 5 seconds. So my suggestion would be, write a separate piece of code to stress test your mutex, and see if it works like it should. Because I think that your issue lies there and not with the Picqer library :)!

**Comment by paqio** [comment]
I don't really use any caching with laravel, should the whole mutex story bother me?

**Comment by paqio** [comment]
The thing is that the only time it goes wrong is when Exact requests errors out, missing field or something, and token is expired. When token is expired and no error from exact, it refreshes properly.

**Comment by paqio** [comment]
I think it comes from here and has nothing to do with the locks: 
```
Psr7\rewind_body($response);
            $body = json_decode($response->getBody()->getContents(), true);

            if (json_last_error() === JSON_ERROR_NONE) {
                $this->accessToken = $body['access_token'];
                $this->refreshToken = $body['refresh_token'];
                $this->tokenExpires = $this->getTimestampFromExpiresIn($body['expires_in']);

                if (is_callable($this->tokenUpdateCallback)) {
                    call_user_func($this->tokenUpdateCallback, $this);
                }
            } else {
                throw new ApiException('Could not acquire tokens, json decode failed. Got response: ' . $response->getBody()->getContents());
            }
```

**Comment by MaartenWaegeman** [comment]
> 
> 
> I don't really use any caching with laravel, should the whole mutex story bother me? And as far as I am aware there aren't by default multiple processes in laravel right?

Picture you have 2 webhooks from Exact coming in at the same time or 2 different users requesting a page that fetches data from the Exact API at the same time. If the token is expired when the requests / webhooks happen. Then you will have 2 separate php processes executing your code at the same time separate from each other. So in parallel, 2 processes could do a request to Exact to refresh a token. If these 2 requests happen at the same time, Exact will generate 2 new access tokens and 2 new refresh tokens. Only 1 access and refresh token will work. Depending on race conditions, you could have the wrong token stored. When you try to refresh the token, you are using a refresh token that's not valid, resulting into a 401 error (see https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-respcodeserrorhandling).

**Comment by paqio** [comment]
I think you relate to @DePalmo . In my case I don't.

**Comment by MaartenWaegeman** [comment]
> 
> 
> I think it comes from here and has nothing to do with the locks:
> 
> ```
> Psr7\rewind_body($response);
>             $body = json_decode($response->getBody()->getContents(), true);
> 
>             if (json_last_error() === JSON_ERROR_NONE) {
>                 $this->accessToken = $body['access_token'];
>                 $this->refreshToken = $body['refresh_token'];
>                 $this->tokenExpires = $this->getTimestampFromExpiresIn($body['expires_in']);
> 
>                 if (is_callable($this->tokenUpdateCallback)) {
>                     call_user_func($this->tokenUpdateCallback, $this);
>                 }
>             } else {
>                 throw new ApiException('Could not acquire tokens, json decode failed. Got response: ' . $response->getBody()->getContents());
>             }
> ```
@paqio That is exactly the piece of code that refreshes the access token :)!

**Comment by paqio** [comment]
yes that's from this library, I am trying to find why only when there is an error refresh doesn't work

**Comment by DePalmo** [comment]
@MaartenWaegeman I am aware of that issue and that's why I integrated locking and unlocking. Sleep() in my instance is merely postponing the execution of the code, the actual locking is done with caching library I mentioned. Except if the caching also doesn't work as it should, but there were no errors logged from that library.

When I logged the responses, I noticed that locking happens right before the API is being called and token refreshed, once that is done the code unlocks and continues with the execution. I can't find the reason why that alone would break things and why it would only do that in few rare instances, that's why I posted the code above if another eye would catch something.
I also noticed that execution of the code is not done in order which requests comes in. Requests comes in as 1 - 2 - 3 - 4 - 5 etc., but the code executes in 1 - 5 - 4 - 3 - 2. Not sure why it would do that ...

But as said, I already re-coded it and now when Webhook request comes in, it is stored into database. Then a CRON job is run every minute that processes all accumulated requests. Not ideal solution since I would prefer to process all requests when they come in. But until we require a "live" processing or searching, this will do.

**Comment by paqio** [comment]
Omg wasted 3 days on this. Thanks to logs of the database. Was making a transaction, which in case of failure would also drop this store request. Thanks, @MaartenWaegeman for proactive help

**Comment by websmurf** [comment]
A thank you from me as well @MaartenWaegeman; have applied the Atomic lock principe to the [laravel-exact-online](https://github.com/websmurf/laravel-exact-online) package as well and haven't run into the 401 error since then

**Comment by brunogoossens** [comment]
> Omg wasted 3 days on this. Thanks to logs of the database. Was making a transaction, which in case of failure would also drop this store request. Thanks, @MaartenWaegeman for proactive help

@paqio What did you change to fix the issue in case of failure?

**Comment by marnickmenting** [comment]
Just to suggest an alternative solution to using locks: we solved it using a (Laravel) Queue. When the webhook is received we add it to the queue, without any calls to Exact API. The queue is then processed using a single worker, so we never have overlapping calls to the API.

**Comment by WeTurkstra** [comment]
@marnickmenting Did this solution really solved the issues for you? In other issues i got comments from people who say Exact randomly fail to provide new tokens. Did you ever encounter any strange weird issues implementing/using the queue?

**Comment by marnickmenting** [comment]
> @marnickmenting Did this solution really solved the issues for you? In other issues i got comments from people who say Exact randomly fail to provide new tokens. Did you ever encounter any strange weird issues implementing/using the queue?

The system works good. We indeed had random issues with refresh tokens, but the implementation was not the problem.

**Comment by remkobrenters** [comment]
Is it safe to conclude this boils down to a (solved) implementation issue with how Exact tokens work and this issue can be closed?
