### ISSUE TITLE
How to modify the status property of SalesOrders endpoint?

### ISSUE THREAD

**Issue by anarmammad** [picqer/exact-php-client#462]
Hi, 

Would be glad if could get help to change the status of the existing order via API. According to [reference documentation](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrders), there are no Status properties in POST and PUT requests.

Are there any workarounds? How to modify the status of the order via API?

Glad to any help.

**Comment by WeTurkstra** [comment]
As far as i know the status of a salesorder is readonly. The state of your sales order is determined by the deliverystatus and invoicestatus. 
So if the invoicing and delivery of your salesorder is completed the salesorders status will also be completed.
If you only did a partial delivery the overall status of your salesorder will also be partial.
