### ISSUE TITLE
Send state parameter with authentication request

### ISSUE THREAD

**Issue by edwin-easytrans** [picqer/exact-php-client#463]
Hi, is it possible to send a 'state' parameter together with the authentication request?
This state parameter is returned by Exact in the redirect URL and can be used to help prevent CSRF as explained here: https://auth0.com/docs/protocols/state-parameters

**Comment by remkobrenters** [comment]
Don't spend to much time on this. Recently Exact updated the validation of the URI: https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2106-rn-appcenter-redirecturls

Main issue for us is this "Exact Online is implementing stricter security during URL validation. You can now only use HTTPS as redirect URLs, **and the entire URL will be validated**.". In multi tenant environments we use the `state` or a custom property like `?administration=xxx` but this no longer works. The URI must be exactly the same and dynamic properties no longer work.

**Comment by edwin-easytrans** [comment]
Hi Remko, I was also looking at using the state parameter to cope with multi tenant environments. I asked Exact how to handle this and their response was to actually use the state parameter.
So even with the announced change, I expect the state parameter would still be working. I have asked Exact for confirmation.

**Comment by remkobrenters** [comment]
Please let me know what the outcome of the request is as we tested and the `state` parameter does not work anymore (currently).

**Comment by edwin-easytrans** [comment]
Will do. Usually takes a few days.

**Comment by edwin-easytrans** [comment]
Hi Remko, the response from Exact support: "Het moet nog steeds mogelijk zijn om een State Parameter mee te geven. Ook met de striktere controle. " (Translated: The State parameter can still be used with the new URL validation)

**Comment by remkobrenters** [comment]
Just tested this with two different environments and yes, it is working again but I am 100% sure without doubt it did not work earlier when I ran into this (as a working production environment suddenly had a broken flow). I did various tests at that moment. Funny thing is that currently not only the request parameters can be different again (like before) but also the URL itself (like the callback url in the app `https://xxx.apibridge.nl/exact-online/callback` and configured in Exact `https://xxx.apibridge.nl/different` is working). 

So yeah, I think we can resolve this one as apparently there was a little configuration glitch on the side of Exact resulting in a too strict validation for the callback url.

**Comment by remkobrenters** [comment]
Did a lot more testing. It works for some of our clients / administrations but does not for others. We suspect little differences in the used versions / configuration of their Exact environment.

**Comment by remkobrenters** [comment]
@edwin-easytrans I think we can close this issue. Agree?

**Comment by edwin-easytrans** [comment]
@remkobrenters I would still like to pass the State parameter. Exact confirmed that this is still possible, even with the stricter URL validation. The reason I need this is so that I can make a central endpoint and use the info in the state parameter to forward to the right server that the customer is on.
You can only use one URI in the Marketplace, so I need this to publish my App as a public App.

**Comment by remkobrenters** [comment]
Yes of course. I agree it is a good addition and should be possible without breaking changes. You are welcome to create a PR for this. Please not my earlier comment that, despite Exact Online saying this should work, we tested this with various connections in which some of them did work while others did not (but for the majority it seemed to work as before so could be a bug in some versions of the Exact platform or something).

**Comment by Eligioo** [comment]
Coincidentally I recently asked Exact Support the same question. I use the state parameter to make my application tenant-aware. They responded with the following.

`Thanks for the question. We cannot say whether it will work for another 100 years. But for now it is the way to distinguish between different users. For now, it will continue to work this way.`
