### ISSUE TITLE
Unable to download invoice pdf when not logged into exactonline(in another tab in same browser)

### ISSUE THREAD

**Issue by gunjanbgpl** [picqer/exact-php-client#465]
Invoice pdf is already created on exactonline but when I pull invoice pdf document url & open it in browser to download it returns "De gegevens die u wilt ophalen kunnen niet gevonden worden of u hebt geen rechten om deze actie uit te voeren" on ExactOnline (in English the error it throws ="The data you want to retrieve cannot be found or you do not have rights to perform this action")

Secondly, If I pull invoice data it returns "Document" field=null/blank(I read somewhere that it must be manually linked with invoice) So How to manually link already created invoice pdf to invoice on exactonline(I dont want to recreate invoice) & if manually linked successfully, is my code correct to fetch them? And how to link it using script for bulk?

Note: Again, I think PrintedSalesInvoice will recreate invoice(and also sends to customer) which I dont want, but if it dosent create new invoice & help me download invoice pdf Can anyone share its code for reference?

Please atleast if anyone can if its atleast possible or not?

Here is my code

```
$documentAttachment = new \Picqer\Financials\Exact\DocumentAttachment($connection);
$attachments = $documentAttachment->filter("Document eq guid'".$doc->ID."'");
foreach($attachments as $docs)
{
	echo $docs->FileName; // I can get this
	if($docs->getDownloadUrl() && $docs->getDownloadUrl()!='')
	{
		echo $docs->getDownloadUrl(); // I can get url(Like https://start.exactonline.be/docs/SysAttachment.aspx?ID=<ALFANUMERIC CHARACTERS>&_Division_=<MY DIVISION ID>&Download=1 )
		// Clicking this URL I can able to download invoice pdf but only & only when I am logged into ExactOnline panel in another tab of my browser, which we dont want - I want it should be without login into ExactOnline

		// I even tried -> echo/print_r() -> $docs->download(); which then print some characterset but didnt downloaded pdf
	}
}
```

**Comment by roland-d** [comment]
@gunjanbgpl You need to make sure you are using the access token as bearer. Here is the code I use to download the file:
```
// Build the connection
$connection = (new Exact)->connect();
$accessToken = $connection->getAccessToken();

$url = 'https://start.exactonline.nl/docs/SysAttachment.aspx?ID='. $guid . '&_Division_=361639&Download=1';

// Get the PDF from Exact
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer ' . $accessToken));

$output = curl_exec($ch);

// Close curl resource to free up system resources
curl_close($ch);

// Offer the pdf to the customer
$filename = $invoiceId . '.pdf';
header('Content-type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Transfer-Encoding: binary');
header('Accept-Ranges: bytes');
echo $output;
```

**Comment by remkobrenters** [comment]
@roland-d thanks. As it has not been followed up I assume your answer was sufficient and I will close this issue.

**Comment by patricksteenks** [comment]
Thanks, I used this code as well and it worked. Unfortunate that there is not yet a specific class from the Picqer client to enable this.
