### ISSUE TITLE
Unable to do sorting for fetching orders from ExactOnline

### ISSUE THREAD

**Issue by gunjanbgpl** [picqer/exact-php-client#466]
We were able to fetch orders from ExactOnline using picqer lib,
but the orders we are getting are not showing Latest Placed Orders first
(Last placed order first - we are getting it in random order)
Atleast please can someone confirm, if its atleast it is possible or not?

```
$ESalesOrderObj = new \Picqer\Financials\Exact\SalesOrder($connection);
$ESalesOrderRes = $ESalesOrderObj->filter("OrderedBy eq guid'<account id of customer>'");
foreach($ESalesOrderRes as $ESalesOrder)
{
  echo $ESalesOrder->OrderNumber; // Lastest Orders is not appearing first
}
```

**Comment by markjongkind** [comment]
There is a separate filter option to order the results. See example code below:
```
$SalesOrderLine = new \Picqer\Financials\Exact\SalesOrderLine( connectExact() );
$SalesOrderLines = $SalesOrderLine->filter("OrderNumber eq " . $OrderNumber, '', '', ['$orderby' => 'LineNumber']);
```

**Comment by remkobrenters** [comment]
@markjongkind thank you for the correct answer. As it has not been followed up I assume it was sufficient and will close this issue.
