### ISSUE TITLE
Client uses CurrentDivision as default Divison ID, but due to changes in the API access might be restricted

### ISSUE THREAD

**Issue by jerbob92** [picqer/exact-php-client#470]
A while ago Exact added new functionality to restrict the connection to a limited list of divisions during authorization.
Due to this functionality, it's very well possible that the application does not have access to the CurrentDivision of the user if the user did not select the CurrentDivision in the allowed list of divisions.

I thought this might give some issues in the API, because this would make it impossible to request the list of divisions using the `system/Divisions` API call, but support told me the Division ID in this URL could be anything, even 123456, it's not validated.

I suggest the following changes:
 - Do not use CurrentDivision in the `system/Divisions` call but use a static fake number, to make it clear that the division ID is not relevant in this request
 - Get the list of available divisions and check whether CurrentDivision is in there, when no Division ID is set, to prevent errors
   - If CurrentDivision is not in there, pick IsMainDivision or the first one in the list

**Comment by HawkeyNL** [comment]
Hello,

I want to use the SystemDivision class to return all the divisions associated with the logged in account.

When using the `new SystemDivision()` (system/Divisions endpoint) it only return's the first division with the metadata uri `/api/v1/1234567/system/Divisions(1234567)`. Does anybody know why this is happening? When using the URI `/api/v1/{any division or integer}/system/Divisions` in the browser it return's all the divisions with ease.

**Comment by jerbob92** [comment]
@HawkeyNL Probably not related to this issue, but can you post more of your code?

**Comment by HawkeyNL** [comment]
Connect function in my exactonline helper class: 
```php
    public static function connect(): Connection
    {
        $connection = new Connection();
        $connection->setRedirectUrl(self::getRedirectURL());
        $connection->setExactClientId(self::getKey());
        $connection->setExactClientSecret(self::getSecret());

        // Retrieves authorizationcode from database
        $auth_code = self::getAuthorizationToken();
        if (!empty($auth_code) && $auth_code != null) {
            $connection->setAuthorizationCode($auth_code);
        }

        // Retrieves accesstoken from database
        $access_token = self::getAccessToken();
        if (!empty($access_token) && $access_token != null) {
            $connection->setAccessToken($access_token);
        }

        // Retrieves refreshtoken from database
        $refresh_token = self::getRefreshToken();
        if (!empty($refresh_token) && $refresh_token != null) {
            $connection->setRefreshToken($refresh_token);
        }

        // Retrieves expires timestamp from database
        $expires_date = self::getExpiresInDate();
        if (!empty($expires_date) && $expires_date != null) {
            $connection->setTokenExpires($expires_date);
        }

        $connection->setTokenUpdateCallback('\App\Helpers\ExactOnlineHelper::storeTokens');
        // Make the client connect and exchange tokens
        LogHelper::debug(__METHOD__ . ': connecting');

        $connection->connect();

        $division = self::getDivision();
        if (!empty($division) && $division != null) {
            $connection->setDivision($division);
        }

        return $connection;
    }
```
Setting the division before or after the connect does not matter.

Exactonline controller getSystemDivisions:
```php
           $connection = ExactOnlineHelper::connect();

            $system_division = new SystemDivision($connection);
            
            $data = $system_division->get([
                '$select' => 'Code', //,Created,CreatorFullName,CustomerCode,CustomerName,IsDossierDivision,IsMainDivision,Status
            ]);
```

Result:
![image](https://user-images.githubusercontent.com/24757491/121870809-b3331f00-cd03-11eb-95a1-0ee4b6dedafb.png)

Total Divisions:
![image](https://user-images.githubusercontent.com/24757491/121870860-bfb77780-cd03-11eb-8776-cc5c260f563b.png)

**Comment by jerbob92** [comment]
@HawkeyNL Should work. 
You should probably check in Exact whether your connection is limited to 1 specific division:

1. Log in to ExactOnline
2. Click on your name in the top right corner 
3. Click on "Mijn ExactOnline"
4. Click on "Beveiligingscentrum"
5. Scroll down to "Machtigingen voor mijn apps"
6. Check what it says in the column "Toegang tot"
7. You can click "Intrekken" to remove the connection, when you reconnect you can select which divisions to allow access to

**Comment by HawkeyNL** [comment]
Thank you so much :+1: 

Created a new test application, the app asked for permissions to read data for future companies (which I needed).

**Comment by jerbob92** [comment]
Great! :+1: 

You don't need to create a new application, you can also revoke the connection to the current application. When you re-connect it will ask you the same thing.

**Comment by remkobrenters** [comment]
Will close this issue as it is related to the permissions configured in Exact Online and not how the package handles divisions.

**Comment by jerbob92** [comment]
@remkobrenters It is related to how this package handles divisions though, as it uses `CurrentDivision` by default and since the changes it's possible that the package does not have access to that Division.

**Comment by remkobrenters** [comment]
Did some further testing and I see your problem. I am not sure if the suggested solution is the right way. 

I think the changes by Exact Online will not impact the majority of the users. The only situations it causes issues are:
- The user switched in Exact Online to a division the API has no acces to (and the connection does not uses a configured division);
- The configured division in the connection is (no longer) accessible for the API user.

Checking the permissions on every requests potentially doubles the requests. Especially for heavy users this could tip them over the rate limits. Honestly I have no good solution in mind right now but if you have I would gladly look into that.

**Comment by jerbob92** [comment]
Thanks for looking into it.

> The user switched in Exact Online to a division the API has no acces to (and the connection does not uses a configured division);
This CurrentDivision is a tricky one, because it's always the current division of that user. So it can switch at any time, also to one the connection does not have access to. 

Honestly, best it not to use CurrentDivision at all.

**Comment by remkobrenters** [comment]
Yes agree. Could result in unexpected datasets (in and out) but changing this would probably break a lot of implementations for a lot of people who either base their application on the division used by the user or have only one division and never even thought of the possible risk there is. 

Best thing I can think of is to make this part of a feature major update in which by default it no longer selects the `currentDivision` unless the developer explicitly chooses to do so to make people aware of the best-practice to choose a division they have access to. 

I don't think the situation of a division being revoked is important. This is something between the developers and their clients and should not happen in the first place in a normal workflow.

**Comment by jerbob92** [comment]
Yeah I agree. Building your integration based on CurrentDivision is probably not the best way, but you can't assume that everyone set's the division in the client.

What we do is described in the ticket:

- Get the list of available divisions and check whether CurrentDivision is in there, when no Division ID is set, to prevent errors
  - If CurrentDivision is not in there, pick IsMainDivision or the first one in the list
 
And the user can always change the division themselves. We never only let the CurrentDivision decide the division.

> I don't think the situation of a division being revoked is important. This is something between the developers and their clients and should not happen in the first place in a normal workflow.

I don't know, it's happened a few times with us, that CurrentDivision pointed to a division that the connection did not have access to.

Probably worth to note that we don't use this client, just wanted to "warn" you.

**Comment by remkobrenters** [comment]
I agree this could be a good solution but it will result in a lot of extra requests in some situations. Will think this one through and get back on this.

**Comment by remkobrenters** [comment]
I will close this thread as it is a very rare case scenario and I think the impact (code wise) is outweighing the problem.
