### ISSUE TITLE
invalid or empty chainId

### ISSUE THREAD

**Issue by sujeetthete** [picqer/exact-php-client#471]
Hello,

When we try to connect with the Exact API following error was occurs. 

'Could not connect to Exact:- Client error: `POST https://start.exactonline.be/api/oauth2/token` resulted in a `400 Bad Request` response:\n{ "error":"invalid_grant","error_description":"Token is not allowed, because of invalid or empty chainId" }

It was working fine before, but suddenly the error started.

**Comment by huubvdw** [comment]
Exactly the same error suddenly starting (around April 26th) to occur here.

I've tried to remove the access and refresh tokens and go through the Oauth flow again. When requesting a fresh access token with the (newly generated) authorisation code, I still get the `400 Bad request` response as described by @sujeetthete

**Comment by bkonetzny** [comment]
Same error here after requesting a lot of access tokens in a short amount of time. Maybe the message is wrong and this is more like a rate limit applied here? (see https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits)
As I'm not authorized via API, it's not possible to get the daily/minutely rate limits and their current use to check this... :(

**Comment by huubvdw** [comment]
After consulting Exact API support, it turned out the our implementation made multiple authorization requests at once and then used an incorrect authorization code to obtain an access token. 
(As we didn't made any changes to our implementation, we're still puzzled why this had even worked previously...)
