### ISSUE TITLE
fillable field DefaultSalesPrice is missing

### ISSUE THREAD

**Issue by matthijs-neijenhuijs** [picqer/exact-php-client#472]
fillable in Item.php is missing "DefaultSalesPrice". It's a hidden field and is not part of this documentation: 

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkLogisticsItems

**Comment by remkobrenters** [comment]
Can you elaborate a bit more about this missing field as I never seen it in a response from the bulk or regular `item` endpoint.

**Comment by DannyvdSluijs** [comment]
@matthijs-neijenhuijs I'm interested in this hidden field which isn't part of the documentation as I've build a tool which can crawl the website and apply changes to the code. Any hidden field would disappear when running the tool again when not added manually. So I'll keep an eye out for any progress here.

**Comment by remkobrenters** [comment]
I am tempted to close this as I have not been able to see anything that indicates this hidden field exists and I agree with the issue mentioned by @DannyvdSluijs that the new generator will not pick this up.
