### ISSUE TITLE
New Exact API hourly error limits

### ISSUE THREAD

**Issue by Phennim** [picqer/exact-php-client#475]
I received an email from Exact that explains new API/error limits that will go into effect on July 1st.

https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-oauth-eol-oauth-devstep3

This explains that if you request a new AccessToken sooner 9 minutes 30 seconds minutes after last one; it will count towards your hourly error rate.

The `tokenHasExpired()` function returns true after 9 minutes:
https://github.com/picqer/exact-php-client/blob/main/src/Picqer/Financials/Exact/Connection.php#L585

So I'm thinking we should subtract 15 seconds instead of 60.

**Comment by remkobrenters** [comment]
There is a PR with a resolution for this issue https://github.com/picqer/exact-php-client/pull/476

**Comment by casperbakker** [comment]
I drafted a new release: https://github.com/picqer/exact-php-client/releases/tag/v3.27.0
