### ISSUE TITLE
How to fetch SalesInvoiceLines from SalesInvoice where there is a '__deferred' array item?

### ISSUE THREAD

**Issue by SchizoDuckie** [picqer/exact-php-client#48]
I'm currently trying to fetch the SalesInvoiceLines for a SalesInvoice, but I'm a bit stuck on the API.

Can you clarify with a code example how I should fetch items that are referred with a __deferred array item?

![image](https://cloud.githubusercontent.com/assets/111710/13490610/0a240d8c-e12e-11e5-920a-40f2c57d1d2b.png)

Thanks for a great library by the way :+1:

**Comment by stephangroen** [comment]
Thanks!

I haven't run into that yet. Are you just retrieving one SalesInvoice?

**Comment by SchizoDuckie** [comment]
Thanks for the quick response :)

I've fetched all SalesInvoices from my test account (there are 2), and i'm trying to iterate over them to fetch the details:

```php
$item = new SalesInvoice($connection);
$invoices = $item->get();

foreach($invoices as $invoice) {
  // echo $invoice->InvoiceNumber
  foreach($invoice->SalesInvoiceLines as $l) {
    // now what :) 
  }
}
```

**Comment by SchizoDuckie** [comment]
Ah-hah! This is a special beast according to the docs.

> Getting the lines of an existing invoice 
> 
> You need to know the ID of the invoice because it has to be passed in the URI. There are 2 ways of doing this.
> 
> 1. URI: `../api/v1/{division}/SalesInvoice/SalesInvoices(guid'984be001-1f89-49f9-88a5-03597060283f')/SalesInvoiceLines`
> 2. URI: `../api/v1/{division}/SalesInvoice/SalesInvoiceLines?$filter=InvoiceID+eq+guid'984be001-1f89-49f9-88a5-03597060283f'`
> 
> Method: GET

**Comment by SchizoDuckie** [comment]
I've since fiddled this. Please advise on what you would do different, i'll wrap it in a PR and add some docblocks while i'm at it :+1: 

```
    /**
     * Updates the SalesInvoiceLines collection on a SalesInvoice if it's been detected as a deferred collection.
     * Fetches results and stores them on this object.
     *
     * @return mixed
     */
    public function getSalesInvoiceLines() {
        if(array_key_exists('__deferred', $this->attributes['SalesInvoiceLines'])) {
            $this->attributes['SalesInvoiceLines'] = (new SalesInvoiceLine($this->connection()))->filter("InvoiceID eq guid'{$this->InvoiceID}'");
        }
        return $this->attributes['SalesInvoiceLines'];
    }

```

**Comment by stephangroen** [comment]
Pretty good solution @SchizoDuckie :) Thanks.

I think this is great. I was in doubt about getting them automatically, but that would always trigger an extra API call for every SalesInvoice and additionally cause a major time increase.

If you can submit this as a PR I'll merge it and add some info to the README.

**Comment by SchizoDuckie** [comment]
Excellent.

I will create a pull request somewhere today hopefully :+1:

**Comment by stephangroen** [comment]
Thank you!

**Comment by SchizoDuckie** [comment]
Thanks for the quick merge!  :+1:

**Comment by BlueRayNL** [comment]
can someone provide an example code for getting the salesinvoiceline->attributes from an invoice?

i tryed ->

`try {
    $invoices = new \Picqer\Financials\Exact\SalesInvoice($connection);
    $result = $invoices->get();

    foreach ($result as $invoice) {
        echo 'invoice id: ' . $invoice->InvoiceID . '<br>';
        echo 'type: ' . $invoice->Type . '<br>';
        if($invoice->Type = 8020 || $invoice->Type = 8024){
            
            $factuuregels = $invoice->getSalesInvoiceLines();
            echo '<pre>' . var_export($factuuregels, true) . '</pre>';`


how ever no succes this returns the same as $invoice->SalesInvoiceLines;
i just need the attributes of the model
