### ISSUE TITLE
Check for valid access token with each request

### ISSUE THREAD

**Issue by jaapjansma** [picqer/exact-php-client#481]
Right now this library only checks whether the access token has expired when someone does `$connector->connect()` however it might be that after that function call the access token expires and resulting in errors coming back from Exact Online.

**Code to reproduce**

The code below is added to indicate how one can reproduce this problem.

```php

$exactConnection = new \Picqer\Financials\Exact\Connection();
// Set your credentials, division id etc...

// The function call below checks whether the access token is still valid
$exactConnection->connect();

sleep(10 * 60); // Wait for 10 minutes

// As a test retrieve the list of journals.
// This will result in an error becuase our access token is expired because of the sleep for 10 minutes.
$journals = new \Picqer\Financials\Exact\Journal($exactConnection);
$result = $journals->get();

```
**Expected behaviour**

When the function `$journals->get()` is called another check for valid access token should take place and if expired it should be refreshed.

**Comment by casperbakker** [comment]
I drafted a new release: https://github.com/picqer/exact-php-client/releases/tag/v3.27.0
