### ISSUE TITLE
Please update Examples in readme

### ISSUE THREAD

**Issue by artifex-media** [picqer/exact-php-client#483]
Hi,

First of all: thanks for this awesome library, which saved me hours and hours of work.
Second of all: love it!

If I can make a suggestion, please modify the following into your example in your readme:
```
$salesInvoice = new SalesInvoice($connection);
$salesInvoice->InvoiceTo = $customer_code;
$salesInvoice->OrderedBy = $customer_code;
```

You are referring to **$customer_code**, which is causing the confusing for whom are reading it that you must enter Excact's "**Code**" field of the Account, which is not the case, you should enter the **GUID**. This is confusing and it took me a few scrolls into the issues section to find that out as it somewhere has been mentioned in another issue. Obviously a developer should follow the Exact API Guidelines but as we know, developers, including me, tend to be a bit lazy.. :)

Thanks again and hope to see the change soon for others to help use the examples much more efficient.

**Comment by casperbakker** [comment]
Thanks for the kind words. If you would make a PR for this clarification we would definitely merge that.

**Comment by DannyvdSluijs** [comment]
I've created PR #496 to address this issue. Hope it is clearer from proposed changes.
