### ISSUE TITLE
Psr7\rewind_body depricated in version 7.2

### ISSUE THREAD

**Issue by meckyp** [picqer/exact-php-client#490]
Can you make this compatible with version 7.2+

**Comment by mjrider** [comment]
did you get the same error i got?
`Call to undefined function GuzzleHttp\Psr7\rewind_body()`
 because that is what i get with guzzlehttp/psr7 2.0.0

**Comment by meckyp** [comment]
@mjrider Yes, I did.
After a lot of debugging, I found out that the function is deprecated from version 7.2

![Screenshot 2021-07-01 at 09 40 10](https://user-images.githubusercontent.com/20825760/124247598-523c8100-db22-11eb-9668-252de66d8a0a.png)

For a workaround I downgrade "guzzlehttp/guzzle" to 7.1.0

**Comment by mjrider** [comment]
ah, my 'fix' was downgrading guzzlehttp/psr7  back to 1.8,  because that was what is was before the upgrade

**Comment by it-can** [comment]
there is a PR https://github.com/picqer/exact-php-client/pull/491

**Comment by casperbakker** [comment]
Fixed with just released version v3.29.0
