### ISSUE TITLE
BulkAccounts: Filtering on these fields is not supported

### ISSUE THREAD

**Issue by fredmatrack** [picqer/exact-php-client#500]
Hi
I'm trying to fetch some accounts in our division using the BulkAccounts endpoint. When adding a filter on Classification1 or Classification2, I get this error:

`https://start.exactonline.be/api/v1/128433/bulk/CRM/Accounts?%24filter=Classification1+eq+guid%277824a4a0-2d69-483d-a879-304d461e7967%27+and+Classification2+eq+guid%27e0ee36e0-2d5e-4647-84b9-a3fee1e0cbe8%27&%24select=Name%2C+Code%2C+ID%2C+Classification5%2C+AddressLine1%2C+AddressLine2%2C+AddressLine3%2C+BankAccounts%2C+Email` resulted in a `400 Bad Request` response: { "error": { "code": "", "message": { "lang": "", "value": "Filtering on these fields is not supported: Classificatio (truncated...)`

In the Exact API documentation filtering is supported on the Classification1 and 2 fields.

**Comment by remkobrenters** [comment]
Yeah technically this should be possible. Might be an issue in Exact Online (you could try asking them to explain why this is not working). Before you do I would make the request as simple possible (one classification to filter), only ID in select etc. and make sure the GUID etc are 100% correct. If you cannot find any issue / typo and it still returns this error I would ask Exact and would also like to know what the solution was .

**Comment by fredmatrack** [comment]
I've created a ticket in the Exact support portal. But after 7 days they still don't know the answer ;-)

**Comment by fredmatrack** [comment]
The bug is fixed by Exact!
