### ISSUE TITLE
ReceivableList and error 429

### ISSUE THREAD

**Issue by fredmatrack** [picqer/exact-php-client#503]
Hi

I'm trying to get all the unpaid invoices from our students using the ReceivableList(). Since the changes in the API limits, we get errors on large divisions with a lot of unpaid invoices. Is there a workaround we can implement? For example add a kind of sleep() function when fetching multiple pages?

It's a pitty they don't support filtering on the FinancialReceivablesList.

**Comment by alexjeen** [comment]
This is our implementation, extend the Connection class and add the wait() method:

    /**
     * Waits to not trigger 429
     */
    private function wait()
    {
        $minuteRemaining = $this->getMinutelyLimitRemaining();
        $minuteReset = $this->getMinutelyLimitReset();

        if ($minuteRemaining === 0 && $minuteReset) {
            // add a second for rounding differences
            $resetsInSeconds = (($minuteReset / 1000) - time()) + 1;
            sleep($resetsInSeconds);
        }
    }

Overwrite all the functions like get() as an example:

    /**
     * @param string $url
     * @param array $params
     * @param array $headers
     * @return array|mixed
     * @throws ApiException
     */
    public function get($url, array $params = [], array $headers = [])
    {
        // get it
        $this->wait();
        return parent::get($url, $params, $headers);
    }

This way even when the library does skiptoken requests it will honour the rate limits which are now much more strict.

@stephangroen maybe it makes sense to add this code the library anyway to prevent issues

**Comment by alexjeen** [comment]
> @alexjeen I like the simple wait/sleep you've created. I'll add this with a toggle, so people have control over wether to use this or not.
> 
> The token endpoint limit can already be controlled with the access token callbacks. Also if you save the tokens right, you should never hit the 200 a day limit. Am I missing something?

Yes I thought about this as well, as long as you don't refresh the token earlier than the ten minutes (or 9.5 minutes in this case), it works. I've confirmed this. It is an issue on the Exact side which I am talking about with them.

The case goes as follows:

1. Your token expires at 2020-10-20 12:50:59
2. Your app does a call at 2020-10-20 12:50:58, so the token is still valid at that specific point in time
3. The request goes to the load balancer and passes authentication, internally, the bearer token header is however copied to the internal app servers of Exact (I think) which validate the token again, the moment they arrive at the app servers is 12:51:01 (the token is then invalid)
4. You get an invalid token error even though the token was valid when you've started the request

Hence we refresh the token 30 seconds before its expiry time (as the token has to be valid until the end of the request). It gives us better and more consistent results. Then your request can take at most 30 seconds.
