### ISSUE TITLE
Subscription question

### ISSUE THREAD

**Issue by it-can** [picqer/exact-php-client#504]
Hi guys,

maybe some of you know what I am doing "wrong" ?

I create a Subscription, with a Number (like: 682). I save the subscripion and it is visable in Exact Online. Except the Number is now changed to something like 1500...

```
$sub = new Subscription($connection);
$subscription = $sub->find('xxxxxxxxx');
$subscription->Number = 682;
$subscription->save();
```

It seems not to update the Number field... Anyone any ideas?

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SubscriptionSubscriptions

**Comment by remkobrenters** [comment]
Your example is confusing as it looks like you are not creating but updating an existing subscription? What I wonder (have no time to test this) is what happens if a number already exists. Maybe Exact Online automatically changed the number to the next available one because it does not allow duplicates in this field or something?

**Comment by it-can** [comment]
well it happens when creating and or updating subscriptions... Exact seems to generate it's own Number...

**Comment by remkobrenters** [comment]
Must say I personally only worked with the subscriptions fetched from Exact Online and not creating / updating them through the API. Could be that this numbers are part of the subscription logic in Exact Online which is not clearly stated in the documentation or something.

**Comment by it-can** [comment]
Yeah could be, but the Api explicitly allows it.... It seems to work when importing through Excel (I heard from someone)...

**Comment by DannyvdSluijs** [comment]
@it-can This is a typical question to ask the official ExactOnline support. As this library is only a PHP implementation of the API offered by Exact Online. This seems to be something specific they can answer with ease, it might even be related to a setting in your specific account (had some similar behaviour with this in past implementation I did).
They might also be the correct persons to correlate to the Excel behaviour you're referring to.

**Comment by it-can** [comment]
> 

Well this was never intended as "bug" in this library, just a question if more people had this exact same issue.. Ofcourse I contacted Exact Support, as well as an Exact expert....
End of the line, when importing Excel sheets it seems to work, but when using the api, it does not work. From what I understand this is a bug in the Exact api.
