### ISSUE TITLE
Is it possible to save / push multiple objects to Exact in one call?

### ISSUE THREAD

**Issue by olia-bn** [picqer/exact-php-client#512]
I would need to push multiple Sales orders / Accounts .
To save on calls, I'd prefer to do it in bulk.

Help highly appreciated!

**Comment by domin8r** [comment]
AFAIK the bulk APIs are only for fetching, not for pushing.

**Comment by remkobrenters** [comment]
If you go to https://start.exactonline.nl/docs/HlpRestAPIResources.aspx?SourceAction=10 and filter by 'bulk' as service you will see all the endpoints only support GET currently so yes @domin8r is correct.
