### ISSUE TITLE
The financial year cannot be changed.

### ISSUE THREAD

**Issue by nhwebsites** [picqer/exact-php-client#515]
When I add a purchase invoice and save it no problems occur. When I then save the order (first because I wanted to add a document but later I tested it without changing anything) I get the error `Picqer\Financials\Exact\ApiException : Error 500: The financial year cannot be changed.` Hope somebody can give me a hint in what direction to serch. I allready tried not entering the finacial year in the firts save but that also results in the same error. Thanks cheers

**Comment by remkobrenters** [comment]
Seems like an issue with the data you try to store and not with the package. Things that come up to me are: Date and period for the record do not match, date/period does not exists yet in the administration, date/period is closed in the administration, date/period is changed somehow and are no longer in the same year etc.

**Comment by nhwebsites** [comment]
Tnx Remko, that's also what the error tells me so I'll just have to include all the fields I use in the firts save or debug what field is missing there. I'll get back here when I find out. :-)
