### ISSUE TITLE
Class 'GuzzleHttp\Psr7\Message' not found

### ISSUE THREAD

**Issue by irenespares** [picqer/exact-php-client#517]
After updating to the latest release (3.33) we are getting the following error:
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'GuzzleHttp\Psr7\Message' not found in xxxx/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php:602

**Comment by twodiefor** [comment]
Probably it is not automatically installed for you as dependency during `composer require picqer\exact-php-client`. Just add it manually `composer require guzzlehttp/psr7` for the latest version or `composer require guzzlehttp/psr7 "^1"` if you're on an older version of Guzzle.
