### ISSUE TITLE
Getting contact by account

### ISSUE THREAD

**Issue by doitonlinemedia** [picqer/exact-php-client#52]
I'm having a list of account and want to get the contact info that belongs to it.
Currently I'm trying something like:
`$contact = new Contact($connection);`
`$info = $contact->filter('Account eq \''.$account->ID.'\'');`

But this is not working, I'm getting the error: 
**Error 400: Operator 'eq' incompatible with operand types 'System.Nullable`1[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' and 'System.String' at position 8.**

When I output the results of $contact->get() it has a property `Account` that contains the account ID. So I should be able to get the contact info by Account ID right?

**Comment by DaveyGiesen** [comment]
You need to use the "guid" if you insert a GUID in a request.
`$info = $contact->filter("Account eq guid'" .$account->ID. "'");`

**Comment by doitonlinemedia** [comment]
Thanks Davey, it's working now! :+1:
