### ISSUE TITLE
Picqer\Financials\Exact\ApiException Error 429 reasonPhrase: "Too Many Requests"

### ISSUE THREAD

**Issue by hen3b182** [picqer/exact-php-client#520]
Picqer\Financials\Exact\ApiException Error 429 reasonPhrase: "Too Many Requests"

![image](https://user-images.githubusercontent.com/22586660/147684666-13bb3974-9690-449e-af28-555eecd1e7fc.png)

My code:
```
        $connection = app()->make('Exact\Connection');

        $items = new \Picqer\Financials\Exact\SalesItemPrice($connection);
        $items =dd($items->get([
                 '$select'    => 'ID',
             ]));
```

And no issues with:
```
        $connection = app()->make('Exact\Connection');

        $items = new \Picqer\Financials\Exact\Account($connection);
        $items =dd($items->get([
                 '$select'    => 'ID',
             ]));
```

is it because 13.000 items is too big? is it loading too many next requests?

I tried
`$connection->setWaitOnMinutelyRateLimitHit(true)`

but that got me the same error...

When i dd on first response it looks like this:

![image](https://user-images.githubusercontent.com/22586660/147685775-ccbdc3a5-ee8a-4ab3-b360-42bcec5b220a.png)

**Comment by remkobrenters** [comment]
It looks like the `$waitOnMinutelyRateLimitHit` is not applied in your case but it is hard to tell you why based on the provided information. You can try to debug here and there to find out why it is not working in your case. I can state that in general it works well and that 13k items should not be a deal breaker (we work with datasets of > 200k records without rate limit issues).

**Comment by hen3b182** [comment]
\picqer\exact-php-client\src\Picqer\Financials\Exact\Connection.php
```
    protected function waitIfMinutelyRateLimitHit()
    {
        if (! $this->waitOnMinutelyRateLimitHit) {
            return;
        }

        $minutelyReset = $this->getMinutelyLimitReset();

        if ($this->getMinutelyLimitRemaining() === 0 && $minutelyReset) {
            // add a second for rounding differences
            $resetsInSeconds = (($minutelyReset / 1000) - time()) + 1;
            sleep($resetsInSeconds);
        }
    }
```

When i replace `sleep($resetsInSeconds);` with `die($resetsInSeconds)` i get 14 after refresh, i get 6 and refresh again, i got 42 as output. 

when i replace it with `sleep(60);`  it works...

**Comment by remkobrenters** [comment]
I would dump the `$resetsInSeconds` and the current `getMinutelyLimitRemaining` to see if in some weird situation it bumps over the limit briefly (despite the 1 second rounding correction).

**Comment by alexjeen** [comment]
Hi,

Check out: https://github.com/picqer/exact-php-client/issues/521 
During local development, last comment can explain why you can have issues

**Comment by remkobrenters** [comment]
I will close this issue as it is better covered in #521
