### ISSUE TITLE
Webhook service temporarily unavailable

### ISSUE THREAD

**Issue by roland-d** [picqer/exact-php-client#522]
Hello everybody,

Today I was checking to use webhooks instead of the REST API to lessen the load and stay under the 5K calls we can do a day. However I keep getting the following error when trying to register a webhook:
`Error 500: Invalid: Post to callback URL endpoint returns 503 Service Temporarily Unavailable`

Does anybody know if this is a problem with my code or Exact is really temporarily unavailable?

This is the code I am using:
```
$subscription              = new WebhookSubscription($this->connection);
$subscription->CallbackURL = $params->get('exactWebhookUrl');
$subscription->Topic       = 'SalesInvoices';
$subscription->save();
```

The `$this->connection` is an instance of `Picqer\Financials\Exact\Connection` and works fine because the REST API works. My `CallbackURL` is set to the same domain as where the oauth script is located.

Thank you for any feedback.

**Comment by remkobrenters** [comment]
Did not see this myself. Is it still unavailable? And if so: can you create a ticket with Exact and put their response in this issue for others to learn why?

**Comment by roland-d** [comment]
@remkobrenters Thank you for your reply. I just checked and still gives me that message. I will create a ticket with Exact and post the results here.

**Comment by roland-d** [comment]
@remkobrenters Now, that took a while because I wasn't getting anywhere with Exact support but finally figured it out. This customer website is using CloudFlare to digest traffic to their sites and have it block malicious requests. So the requests that Exact Online sends out are tagged as malicious bots by CloudFlare, so CloudFlare blocks the requests result in the 503 error.

A firewall rule to allow traffic to the webhook URL is useless because the bot checking happens before the firewall rules are processed. The solution for now is to create IP Access Rules for the countries Ireland and The Netherlands. Ireland is needed for registering the webhook, then the reply comes from their. Any webhook update is coming out of The Netherlands, so need to allow that as country too. You could also do it based on specific IP addresses but Exact has more than 1 IP and I do not know whenever they change so decided to allow these countries.

In my support ticket I told Exact they may want to do something about their bots :)
