### ISSUE TITLE
waitIfMinutelyRateLimitHit throws error on sleep

### ISSUE THREAD

**Issue by mjrider** [picqer/exact-php-client#527]
waitIfMinutelyRateLimitHit  seems to have a cornercase where it tries to sleep an negative amount of time
triggering the following error: `sleep(): Number of seconds must be greater than or equal to 0 `

a fix for this could be checking if `$minutelyReset > (time()*1000)` or just calling sleep like this `sleep(max(0,$resetsInSeconds));`

i'm not sure under which scenario this would reproduce, i'm still trying to figure that out, i do know that the clock on the server running the code is in sync with ntp.

**Comment by remkobrenters** [comment]
See #521 as this covers the same topic.
