### ISSUE TITLE
Error 429:  when trying to get items

### ISSUE THREAD

**Issue by ArmandHeijder** [picqer/exact-php-client#528]
Hello, I have a simple script to get items out of Exact:

`
try {
    // List items with filter (using a filter always returns a collection)
    $item = new \Picqer\Financials\Exact\Item($connection);
    $result = $item->get(); // Uses filters as described in Exact API docs (odata filters)

    $json = json_encode($result);    
    
    echo "Items zijn bijgewerkt";

} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}
`
But when i execute the script I get the following error:
Picqer\Financials\Exact\ApiException : Error 429: 

I updated to the latest verion of this library

Does anyone know how to fix this?

**Comment by markjongkind** [comment]
Error 429 means "Too Many Requests", you've hit the API limits. There are limits per minute and per day (see [Exact documentation](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits)), so you wait a minute and retry again.

**Comment by ArmandHeijder** [comment]
Unfortunately I got this problem from the gecko.. I already get this error when I run the script once. It never gave me a response. I also tried to use different accounts.
