### ISSUE TITLE
Does this library also work for Exact Globe?

### ISSUE THREAD

**Issue by doitonlinemedia** [picqer/exact-php-client#53]
As the title says, does this library also work for Exact Globe and not only Exact Online?

Thanks.

**Comment by stephangroen** [comment]
Well, it specifically connects to the Exact Online endpoints. I have not experience with Exact Globe and the API availability for Exact Globe. If the API is the same, only the URL differs, it might work with some slight adjustments.

**Comment by doitonlinemedia** [comment]
Alright, thanks for the reply. I'll try some things.
