### ISSUE TITLE
src/Picqer/Financials/Exact/SalesInvoiceLine.php

### ISSUE THREAD

**Issue by PHP-GLOBE** [picqer/exact-php-client#530]
Allthough the API documentation mentions StartTime and EndTime for transitory salesInvoiceLines. It should be StartDate and EndDate.
Exporting SalesInvoice from Exact show those and after altering the code it works as it should

**Comment by PHP-GLOBE** [comment]
Possibly BulkSalesInvoiceSalesInvoiceLines needs to be altered as well. Not tested....

**Comment by remkobrenters** [comment]
If your findings are correct (cannot verify them right now) I think reporting this to Exact to match the documentation with the underlying platform would be better as than @DannyvdSluijs can do his magic to sync the package with the changes in the documentation.

**Comment by PHP-GLOBE** [comment]
I did make a support ticket with Exact about this problem

**Comment by DannyvdSluijs** [comment]
I did a sync and the `startDate` and `endDate` on  `SalesInvoiceLine` dent appear in the documentation.
However the `SupplierItem` did get those properties. Not sure if it is related though.
See https://github.com/picqer/exact-php-client/pull/533 for the found changes.

**Comment by stephangroen** [comment]
Please keep us informed on Exacts response. The docs should be correct, so we can match them (with @DannyvdSluijs great magic :D)

**Comment by PHP-GLOBE** [comment]
The support engineer did escalate it to development team....
