### ISSUE TITLE
Adding Salesentrylines to existsing SalesEntry

### ISSUE THREAD

**Issue by pavoxbv** [picqer/exact-php-client#538]
When adding additional Salesentrylines to an existing  SalesEntry, The update fails... 
I use the same   addItem function like I use for new SalesEntries, which works fine. 
Modifying existing lines works fine also.
Any suggestions ?

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://start.exactonline.nl/api/v1/1821313/salesentry/SalesEntries(guid'3f0956d9-c601-4ffb-9d62-f35966e5692d')` resulted in a `400 Bad Request` response:
{
"error": {
"code": "", "message": {
"lang": "", "value": "Error processing request stream. Binding to new entities  (truncated...)
 in /var/www/html/boeking-whz/cron/exact/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/boeking-whz/cron/exact/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /var/www/html/boeking-whz/cron/exact/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/boeking-whz/cron/exact/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Respon in /var/www/html/boeking-whz/cron/exact/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php on line 771

**Comment by DannyvdSluijs** [comment]
Thanks for reaching out. 

It seems an important part of the details is not in your copied exception. The API has given an response with some details but the majority has been truncated 
> Error processing request stream. Binding to new entities (truncated...)

Could your provide the most inner message with the details? It might be there was an issue on the Exact side or the request you be made has an issue but I feel that message holds the key to making that call. 

And to be clear this is a OSS community powered api client if there is any issue with Exact it is best to reach them through official support channels.
