### ISSUE TITLE
Cant connect to Exact

### ISSUE THREAD

**Issue by Tanktiger** [picqer/exact-php-client#54]
Hello,

i have an application on symfony 2.8 and want to connect to your api. The authorization success and i get the authorizationCode but when i want to get the Journals i am getting this error:

`Could not connect to Exact: Client error: POST https://start.exactonline.de/api/oauth2/token resulted in a '400 Bad Request' response:
Bad Request`

My connect function:

````
public function connect() {
        $em = $this->em;
        //getting exact tokens from DB
        $clientConfig = $this->getConfig();

        $connection = new Connection();
        $connection->setRedirectUrl($this->exactCallbackUrl);
        $connection->setExactClientId($this->exactClientId);
        $connection->setExactClientSecret($this->exactClientSecret);
        $connection->setBaseUrl('https://start.exactonline.de');

        if ($clientConfig->getAuthorizationcode()) {
            $connection->setAuthorizationCode($clientConfig->getAuthorizationcode());
        } // Retrieves authorizationcode from database

        if (null !== $clientConfig->getAccesstoken()) {
            $connection->setAccessToken(unserialize($clientConfig->getAccesstoken()));
        }// Retrieves accesstoken from database

        if (null !== $clientConfig->getRefreshtoken()) {
            $connection->setRefreshToken($clientConfig->getRefreshtoken());
        }// Retrieves refreshtoken from database
        if (null !== $clientConfig->getExpiresIn()) { // Retrieves expires timestamp from database
            $connection->setTokenExpires($clientConfig->getExpiresIn());
        }
        // Make the client connect and exchange tokens
        try {
            $connection->connect();
        } catch (\Exception $e) {
            throw new Exception('Could not connect to Exact: ' . $e->getMessage());
        }
        // Save the new tokens for next connections
        $clientConfig->setAccesstoken(serialize($connection->getAccessToken()));
        $clientConfig->setRefreshtoken($connection->getRefreshToken());
        $clientConfig->setExpiresIn($connection->getTokenExpires());
        $clientConfig->setUpdateDate(new \DateTime());

        $em->persist($clientConfig);
        $em->flush();

        return $connection;
    }
````

An auhtorizationCode from the DB:

`eTWA!IAAAAHCcr0YXhas8XRzqtKBc0xBCZGYUyNUVhcSj1jiX0W0vAQEAAAEyItD_eVi1LRgnj0O0aLN9E2L18zBYgYxZo5nBs4oG6k5aBtSjsP5sP0C-E8SEWVzlr7k_XS_xHHPe7S2Z9v285nYxHI3vhoUWM1wUeHJpCxNYLmmvhhOmZQ8TPFHT3bFr9jaTz45j88tx_tPDBcHJ3mxZt3L3VWZvWL3sBY4RBp09-AqIIgzwpGMJrdcE8CCN-LcXZBxOyc2t6cRSuVSOJZ8q9Ku7RJXjR2tPMSLWbL9qJ_IZr1rHBvXFcS0CAxHtH0xB1vaFCXBPapVsza2p86Ew2bpFas5sdDtbtMw_iOjvbw8_iVLhol-rcsKFZuqJ2hRzBk9H8YQWBC7kAp48`

What i am doing wrong?

**Comment by stephangroen** [comment]
Unfortunately the error could be a number of things. Are you sure the redirectUrl is exactly as you entered it in Exact itself?

**Comment by Tanktiger** [comment]
Yes because when i am authorizing my app i will be directed to exact for logging in and then i will be redirected to my app. Then i get the code from the GET Paramter "code" and save it to the db.
When i now want to get the journals with the following function, i get the error thrown by my connect() function.

```
    /**
     * @return Journal[]|null
     */
    public function getJournals() {
        try {
            $connection = $this->connect();
            $journals = new Journal($connection);
            $result = $journals->get();
            return $result;
        } catch(Exception $e) {
            error_log($e->getMessage());
            $this->log->write('exact exception', $e->getMessage(), $e->getTraceAsString());
            return null;
        }
    }
```

**Comment by Tanktiger** [comment]
So i checked the URL's and yes, they are the same

what the heck i am doing wrong?

**Comment by Tanktiger** [comment]
This is my Connection Object:

```
Picqer\Financials\Exact\Connection Object
(
    [baseUrl:Picqer\Financials\Exact\Connection:private] => https://start.exactonline.de
    [apiUrl:Picqer\Financials\Exact\Connection:private] => /api/v1
    [authUrl:Picqer\Financials\Exact\Connection:private] => /api/oauth2/auth
    [tokenUrl:Picqer\Financials\Exact\Connection:private] => /api/oauth2/token
    [exactClientId:Picqer\Financials\Exact\Connection:private] => 83c023c9-0056-4d15-a924-80fab52fb97f
    [exactClientSecret:Picqer\Financials\Exact\Connection:private] => J6eSsYZjf3VL
    [authorizationCode:Picqer\Financials\Exact\Connection:private] => eTWA!IAAAADEvoLFefA1AXZ3A7nHlyjV5s6oq9BxnhBTmDDbi3cmt8QAAAAHj8-5QhRsRKgS6haDjy-1h1pfjs7MrJHZeL6D3aruYpNRe3BO--Bk4raHF41YCNDo9X-Dzm0q4yu6wWwKGl2G6CjTy5jLvqtDSePq98QrQoSNgHL92xbBnK8kDIX3xbpo659I7HWg07j9__IKQm_KP_BeTp7P5GkAidDFMOdHm8hNcr6YN3tid1Mo5IIeA1ZNH9tTSY4BM80Q1eRLJZOVH5p6U6VrcqkW4qs5xdwkm2ApNLXGCVxDwWktuM2hnLXBYrDaWP5A2kmP5MbJ-33KWfxovjtVc7gYGFgY0EH7i9EtLv2Vd63IfLU1mjXJB4xY
    [accessToken:Picqer\Financials\Exact\Connection:private] => 
    [tokenExpires:Picqer\Financials\Exact\Connection:private] => 
    [refreshToken:Picqer\Financials\Exact\Connection:private] => 
    [redirectUrl:Picqer\Financials\Exact\Connection:private] => http://localhost:9001/app_dev.php/exact/authorize/callback
    [division:Picqer\Financials\Exact\Connection:private] => 
    [client:Picqer\Financials\Exact\Connection:private] => 
    [middleWares:protected] => Array
        (
        )

    [nextUrl] => 
)
```

Why is the devision not set? Do i need to set it by myself? in the tutorials i found nothing :(

**Comment by Tanktiger** [comment]
so i found my problem:

you can only request the access token once with an authorization code. if we dont save the access token we need a new authorization code to get a new access token.

Thx for no Help - this can be closed

**Comment by casperbakker** [comment]
These Github issues are for issues with the code, not a support forum.

But if you do not like this project, you are always free to build your own Exact client from scratch. ;)

**Comment by Tanktiger** [comment]
This is a issue with your API - Bad Request as an error code is really bad for an API wich everyone can access. You should implement error codes or error messages.

Btw. i like the library ;)

**Comment by stephangroen** [comment]
I'll be happy to merge you're PR for the error codes @Tanktiger

**Comment by it-can** [comment]
All of a sudden I get this error:

```
Error - Could not connect to Exact: Client error: `POST https://start.exactonline.nl/api/oauth2/token` resulted in a `400 Bad Request`

and sometimes 

Error - Could not connect to Exact: Could not acquire tokens, json decode failed.
```

**Comment by it-can** [comment]
@Tanktiger how did you fix this?

**Comment by stephangroen** [comment]
@it-can Did you get this in a specific version (after upgrading the package) or did it start while using the same version?

**Comment by ivanovro** [comment]
I get 400 with no obvious reason and status message says nothing meaningful, how could I troubleshoot that?
Yesterday I got access code and tried to get token, no luck, got 400 and same today.

**Comment by it-can** [comment]
This fixed it for me:

```
composer require picqer/exact-php-client
```

**Comment by alinazerguine** [comment]
Hello Tanktiger
I see you did fix that problem, can you be able to help me to fix same issue?
I can pay for it.

**Comment by ivanovro** [comment]
It is probably a mistake.

Best Wishes,
Roman Ivanov
