### ISSUE TITLE
turnover

### ISSUE THREAD

**Issue by svansteenkiste** [picqer/exact-php-client#541]
Hi,  

Is there an easy way to retreive the total turnover of an account?

thx

**Comment by DannyvdSluijs** [comment]
Hi @svansteenkiste 

This sounds like a typical question to ask Exact Online. As this is a community powered OSS project you might get the answer you’re looking for but it might take some time. The [official channels](https://support.exactonline.com/community/s/?language=en_GB) of Exact should be able to answer you quicker.

**Comment by svansteenkiste** [comment]
> Hi @svansteenkiste
> 
> This sounds like a typical question to ask Exact Online. As this is a community powered OSS project you might get the answer you’re looking for but it might take some time. The [official channels](https://support.exactonline.com/community/s/?language=en_GB) of Exact should be able to answer you quicker.

Received answer from Exact, this is not possible !

**Comment by remkobrenters** [comment]
Okay thanks for following this up.
