### ISSUE TITLE
Multiple conditions

### ISSUE THREAD

**Issue by svansteenkiste** [picqer/exact-php-client#543]
Hi,

I supposed we can get records based on multiple conditions like :

```
$item = new \Picqer\Financials\Exact\SalesEntry($connection);
$items = $item->get([
    'Customer' => "guid'" . $guid . "'",
    'Status' => '50',
    '$select' => "Status, Customer, EntryID"
]);

```
unfortunately, this is not working....

Hope someone can assist me what am i overlooking ?

**Comment by svansteenkiste** [comment]
ok, 

maybe i was too quick to post this issue, sorry about this

$items = $item->filter("Customer eq guid'" & $guid & "' and Status eq 20", null, 'Status, Customer, EntryID');
did the trick, unless this syntax is also possible:

$items = $item->get([
    'Customer' => "guid'" . $guid . "'",
    'Status' => '50',
    '$select' => "Status, Customer, EntryID"
]);

**Comment by remkobrenters** [comment]
Yes you should use the filter for this.
