### ISSUE TITLE
manufacturing/TimeTransactions resource missing in library

### ISSUE THREAD

**Issue by Eligioo** [picqer/exact-php-client#554]
I could be mistaken on this one but in the library I can only find a TimeTransaction class for project/TimeTransactions but not for manufacturing/TimeTransactions. If this happens to be the case I can create a PR.

**Comment by DannyvdSluijs** [comment]
Typically these comes along with the automated pr’s I can create. Could you point to the online docs where these can be found?

**Comment by remkobrenters** [comment]
@DannyvdSluijs was just typing a message for you but you are lightning fast here.

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingTimeTransactions
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ProjectTimeTransactions

**Comment by Eligioo** [comment]
@DannyvdSluijs https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ManufacturingTimeTransactions which is different then https://github.com/picqer/exact-php-client/blob/main/src/Picqer/Financials/Exact/TimeTransaction.php

**Comment by DannyvdSluijs** [comment]
I’ll try to see if I can resolve it tonight.

**Comment by Eligioo** [comment]
Does your generator takes resources with equal names from different services into account?

**Comment by DannyvdSluijs** [comment]
What it actually does is scape the html and build generic data model (should have been an OpenApi spec in hindsight). That model is being generated into code for this repo. It might be that I have to add a line or three to make sure that all goes okay. I’ll take a look later.

**Comment by DannyvdSluijs** [comment]
Thanks @Eligioo as you highlighted something was going wrong in the toolchain. There is a PR which is the update based on the docs as of today. Which also includes adding the ManufacturingTimeTransactions
