### ISSUE TITLE
Error 400, trying to get all direct debit mandates

### ISSUE THREAD

**Issue by wout85nl** [picqer/exact-php-client#556]
Hi,

I'm using Picqer/exact-php-client to retrieve Account information from Accounts, BankAccounts and Direct Debit Mandates.

The first 2 are working just fine, I get all Accounts and all BankAccounts, but when I'm trying to retrieve all Direct Debit Mandates I get:

`Error 400: Please add a $select or a $top=1 statement to the query string.`

Using ['top' => 1] works, but returns only one direct debit mandate. I can't use top 1 because accounts can have multiple mandates.

Part of the code:
```
    public function syncExactBankAccount() {
        $exactConnect = new DirectDebitMandate($this->connectExact());
        $DirectDebitMandates = $exactConnect->filter("Account ne guid'10619c30-ea7e-49b0-9aeb-8ced03761bce'");
        //filter excluding own company account.
        dd($DirectDebitMandates);
    }
```

What's causing this?

**Comment by remkobrenters** [comment]
Various endpoints require you to either cap the amount of records (`$top=1`) or define the selected fields (`$select=Code,Description`). So if you want more than one please use the `$select` to choose the fields you want. 

See https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-query-string-options for more instructions.

**Comment by wout85nl** [comment]
Thanks Remko, works! Newby at work here :)
