### ISSUE TITLE
Laravel Octane

### ISSUE THREAD

**Issue by brunogoossens** [picqer/exact-php-client#557]
When using laravel octane, using exit is a problem

```php    
public function redirectForAuthorization()
    {
        $authUrl = $this->getAuthUrl();
        header('Location: ' . $authUrl);
        exit;
    }
```

**Comment by remkobrenters** [comment]
'is a problem' is not very specific or helpful. Can you explain what you think to conclude and how this should be improved in a way that it still works in both Octane as plain PHP implementations?

**Comment by brunogoossens** [comment]
Using exits stops the process for webservers that keep alive like RoadRunner or Swoole. The result is that there is no redirect response. I don't have a good solution for this problem. You can avoid this function by implementing some extra logic inside your app and make a redirect the way your framework wants it to.

**Comment by remkobrenters** [comment]
Yeah the package is very extendable so using the related public functions you should be able to make it work in a way that works for your application. We mainly develop backend application that have no browser/user interaction so when a new consent is required we send a notification to the user or something like that. I think the way the package is setup right now is good but if you want feel free to submit a pr to improve it so it can be reviewed.
