### ISSUE TITLE
StandardSalesPrice of an item

### ISSUE THREAD

**Issue by MarkKobes** [picqer/exact-php-client#558]
Is it possible to send the value 'StandardSalesPrice' with creating a new item?
In ExactAPI scheme 'Item' it is defined, but isn't working in piquer exact php client...

**Comment by remkobrenters** [comment]
This field cannot be set when creating an Item. See https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=LogisticsItems and then switch to POST or PUT to see the field is not there. This field is determined by Exact based on other entities.

**Comment by MarkKobes** [comment]
Hmmm... Yeah, now I see it in the docs... What is the best scheme? Using SalesItemPrice after creating the item? After thatbI get two records... One at 0 euro (created by new item) and a now price on the day of today... How can I fix this with just one line?

**Comment by remkobrenters** [comment]
I am not sure what the best approach is without trying some things out (for which I don't have time now) to this one as I do not recall creating new Items with a default price before.
