### ISSUE TITLE
Access token expires sometimes, cronjob in place to keep tokens alive

### ISSUE THREAD

**Issue by arkoe** [picqer/exact-php-client#559]
For a web app I created to automate certain tasks within multiple Exact Online administrations, I have added a cronjob that refreshes the tokens every 30 minutes when there are no other tasks to perform. This works like a charm, updating the tokens and keeping them alive for later use.

However, every once in a while (mostly on monday, there are no orders being processed in the weekends, so its only the refresh token cronjob running), the access tokens will (probably) expire, and therefore be deleted from the database so the user has to authenticate with Exact again in order for the app to start working again.

Is there anything else I can do to assure that the access tokens will work, so that the user doesn't have to login again in order for the app to work?

**Comment by skilip** [comment]
We experience the same behavior. Could is be that the Refresh token gets expired or invalidated after exceeding rate limits?

**Comment by remkobrenters** [comment]
@skilip no but please be aware that you get a new refresh token back if the request 'fails' due to a rate limit issue.

**Comment by remkobrenters** [comment]
@arkoe we have similar flows (applications that run on a weekly/monthly base) but have no issues with keeping the tokens alive there.
