### ISSUE TITLE
Sync model inheritance broken in v3.40.0

### ISSUE THREAD

**Issue by timothydc** [picqer/exact-php-client#561]
Hi

In previous versions the sync models extended from their base class. For example the `SyncItem` class would extend from the `Item` class.

This was useful for example when you are handling an Item from EOL, but you don't know (or care) if the item was received via the sync api, via the bulk api or via a normal API call. You could just type your parameter with `Item` and it would accept a normal `Item` a bulk item `BulkItem` and a sync item `SyncItem`.

```
// example API call
$item = (new SyncItem($connection))->get();

// previously this would work
function import(Item $item) {}

// now we need to use
function import(Item|SyncItem $item) {}
```

Now we need to check all our code and either switch to the generic `Model` or add multiple types `Item|SyncItem`. Also the `Account` and `SyncAccount` classes have this issue.

`SyncItem` example: [https://github.com/picqer/exact-php-client/compare/v3.39.0...v3.40.0](https://github.com/picqer/exact-php-client/compare/v3.39.0...v3.40.0#diff-974829653c37f7abb2b012eacc8924269004863845d9198d9d2439475fa31e48L111)

This seems like a breaking change which should not have happened in a minor version.

Was this intentional or an issue with the automated API script from DannyvdSluijs?

**Comment by DannyvdSluijs** [comment]
I’m guessing this is the result of the automated updates as that makes every class extend Model. 

We can go about in many ways making sure extended classes are kept as is or have no inheritance. 

One thing to consider perhaps is you projecting both Items to share the same basic set of attributes which might not be the opinion of the Exact Online developers making it more difficult for ourselves in the future. 

But that is only my opinion. I guess the core contributors might have an opinion on this. 

P.s. I’m in the process of moving houses so my time for OSS is limited at this point. Am willing to accept PR’s on https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator. Might be challenging as it is more an automated script than it being a fully fledged app with testing and other QA measures.

**Comment by remkobrenters** [comment]
Tough one. I understand the issue @timothydc has but on the other hand it could be nice to exactly know which model you are dealing with (even though the differences are very small currently). I personally would not change the way the models are setup right now.

**Comment by timothydc** [comment]
I don't mind how it turns out either way. It was just painful that this change was made in a minor version.
For the moment, I am just locking our dependencies to v3.39.0, until I have the time to refactor our code.

The automated upgrade script of @DannyvdSluijs is just fantastic! But in the future, we should be really mindful of these kind of changes in minor versions.
