### ISSUE TITLE
Issue with StockCountLines

### ISSUE THREAD

**Issue by KC031** [picqer/exact-php-client#566]
I want to import StockCounts automatically, but whenever I do, I get the Error 500 that the StorageLocation is mandatory. According to the documentation, this is not the case.

It's also not easy (unless I'm missing something) to extract the storage location id's from Exact, as you can't request them in bulk. Extra difficulty for this is that there's always the chance that storage locations get changed.

To be complete, you can find my code below:

`$stock_count_lines[] = [
    'Item' => 'd7074370-4885-41e8-b281-08afb0ea3365',
	'QuantityDifference' => -5.49,
  ];

  $stock_count = new \Picqer\Financials\Exact\StockCount($connection);
  $stock_count->StockCountLines = $stock_count_lines;
  $stock_count->Description('test 31/5');
  $stock_count->Warehouse($warehouse_id);
  $stock_count->StockCountDate(date('Y-m-d'));
  $stock_count->save();`

Does anyone use the StockCount? How do you handle this?

Thanks in advance for your help!

**Comment by remkobrenters** [comment]
I think the field is sometimes mandatory (depending on the version of Exact and configuration) and that they try to explain that with "This property is package specific (Stock count can have multiple lines for the same item only if it is for multiple storage locations)." but that is a guess. Simple conclusion is: Yes in your case the field must be filled. 

There is no bulk endpoint but using https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=InventoryStorageLocations with some selects would give you all you need fairly quick.

**Comment by KC031** [comment]
Thank you for your help, Remko! I think I will be able to figure something out.
