### ISSUE TITLE
LeadSource and LeadPurpose classes missing

### ISSUE THREAD

**Issue by Eligioo** [picqer/exact-php-client#567]
Both LeadSource (https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMLeadSources) and LeadPurpose (https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMLeadPurposes) are missing as classes.

@DannyvdSluijs It's best to ask you to rerun your generator?

**Comment by DannyvdSluijs** [comment]
I've created https://github.com/picqer/exact-php-client/pull/568 for this

**Comment by Eligioo** [comment]
@DannyvdSluijs thanks for the PR and good luck with moving between houses.
