### ISSUE TITLE
Consider the argseparator for http_build_query.

### ISSUE THREAD

**Issue by rogiervandongen** [picqer/exact-php-client#571]
This has taken me a full day and a half to investigate and finally come to an answer.
The problem arises when using Exact Online in Moodle.

Moodle wrongfully overrides the arg_separator.output to '&amp;' in their initialisation process.
This has been done 14 years ago and has yet to be resolved.
It's already mentioned in their issue system several times and ultimately, nearly all SDK's and API implementations I wrote _had_ to call http_build_query with the third parameter hardcoded to '&'.

Our problems became clear when:
- results didnt comply with expectations.
- the order of $filter and $top (or $select for all that matters) would make a difference between a result and an error message/bad request notification.

I'd love to see a way to override/force/set the separator used in http_build_query; which is used in 2 locations only (Connection class).
By default; the default PHP setting should always be taken (because it should always be '&').
When explicitly needed, it could be overridden.

If any help might be needed; I'm willing to make the changes and file a PR.
Cheers :)

**Comment by rogiervandongen** [comment]
Normally, I'm absolutely tempted to agree with your point of view.
However, it's an option that can be modified in PHP using ini_set().
Apparantly there are systems actually overriding it (granted: with all the extra fixes to "undo" the wrong that the overridden setting caused to begin with! Moodle really is a prime example here).

I wouldn't mind *not* having this implemented/fixed, but in that case I do actually vote for a FAQ section explicitly noting this might cause an issue and validation of the correct arg_separator setting is critical for this SDK to work.

a FAQ or common pitfalls section in the readme somewhere would already be sufficient.
(over the years I've had to write several of these sections/documents just because of similar issues).

**Comment by Eligioo** [comment]
@rogiervandongen why don't you create a patch out of the PR you are planning and create a composer patch to give yourself temporary the ability to override third parameter of `http_build_query` until Moodle has fixed their `arg_separator.output`?

Personally to me this functionality sounds very niche and like @remkobrenters said, is caused by a third-party.
