### ISSUE TITLE
Error Token is not allowed, because of invalid or empty chainId

### ISSUE THREAD

**Issue by PeterVoskuilen** [picqer/exact-php-client#573]
Having issues connecting to Exact API.

Using picqer/exact-php-client in laravel an error is thrown by the Exact API.
I can not see what is going wrong here. error is received when Exact redirects to url after entering credentials.

Error 400: { "error":"invalid_grant","error_description":"Token is not allowed, because of invalid or empty chainId" } (Reason: Unknown: Token is not allowed, because of invalid or empty chainId)

Any one has experienced this behavour before?

**Comment by Eligioo** [comment]
If I remember correctly, you can get this message when using an old refresh token or an authorization token that is expired.

**Comment by PeterVoskuilen** [comment]
The problem seems that in Laravel the tokenUpdateCallback is not working as it should.
I added the tokenUpdateCallback function to a Helper in Laravel and i'm using 
`$connection->setTokenUpdateCallback('\App\Helpers\ExactOnlineHelper::tokenUpdateCallback');`

As far as i can see the function in the is not called from the piqker vendor Connection.php
How to make a function in Laravel that is callable from the vendor map?

**Comment by DannyvdSluijs** [comment]
Maybe the logger middleware trick might give some insights? See https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-response
