### ISSUE TITLE
How can you fetch (a lot of) SalesOrderLines where some are __deferred?

### ISSUE THREAD

**Issue by KC031** [picqer/exact-php-client#574]
I have a script that I want to run a lot of times per day. This script fetches all pending SalesOrderLines. However, when I fetch these, some of them come back deferred.

I thought to add the code below, but then I think I'll hit a lot of limits.

`if(array_key_exists('__deferred', $po->SalesOrderLines)) {

  $salesorderline = new \Picqer\Financials\Exact\SalesOrder($connection);
  $po->SalesOrderLines = $salesorderline->filter("OrderID eq guid'{$po->OrderID}'");

}`

Edit: formatting

**Comment by remkobrenters** [comment]
Never had this issue. Are you sure this is not due to an implementation issue? And if not: did you solve it and do you want to share your solution with other people running into the same issue?

**Comment by KC031** [comment]
Hi Remko, thanks for your reaction. It could well be due to an implementation issue. I haven't yet found a workaround. Please find below the code I use to fetch the SalesOrderLines.

`
$salesorders = new \Picqer\Financials\Exact\SalesOrder($connection);
$pending_orders = $salesorders->filter('DeliveryStatus ne 21 and Status ne 45', '', 'SalesOrderLines, OrderNumber, OrderedBy');
`

Unfortunately, I need both the quantity & quantity delivered, so I can't use the bulk salesorderlines.

**Comment by remkobrenters** [comment]
Thanks. Does not look like the problem is in there. Not sure what happens in this case (did not run into this problem myself). Maybe someone else ran into something similar and figured out how or why?

**Comment by KC031** [comment]
After contacting Exact, they recommended to use the endpoint "Sync SalesOrderLines".

I now fetch all of the SalesOrderLines through this endpoint, filter on the ones pending and finally I also fetch the SalesOrderHeaders (through the Sync endpoint as well). 

The only thing that bothers me is that it's hard to filter the Sync SalesOrderLines endpoint. The only way you can filter the Sync endpoint is with the timestamp.
