### ISSUE TITLE
`waitIfMinutelyRateLimitHit` throws exception

### ISSUE THREAD

**Issue by Eligioo** [picqer/exact-php-client#575]
In some rare occasions I've encountered that the `waitIfMinutelyRateLimitHit` method throws an exception due to the following:

`sleep(): Number of seconds must be greater than or equal to 0 Line: 907`

I haven't been able to log what the outcome is of `$resetsInSeconds` but as the message implies it is probably lower than 0.

**Comment by remkobrenters** [comment]
I was checking the PR but I do not recall seeing this scenario anywhere. Are you sure it is not caused by something in your setup?

**Comment by Eligioo** [comment]
@remkobrenters there isn't much to break while using this package. I'm using all the getters and setters exposed through the package and the server time is correct. `minutelyLimitReset` is only used internally by `extractRateLimits`. So I no way I am using the package incorrectly.

But like I said it happens rarely as we process a lot of Exact Online related API calls.
