### ISSUE TITLE
SalesEntryLine missing AmountFC

### ISSUE THREAD

**Issue by Slijkhuis** [picqer/exact-php-client#58]
AmountFC is required by the Exact API for creating SalesEntryLines. However, in the $fillable property of the SalesEntryLine class it lists AmountDC instead of AmountFC.

**Comment by arendvw** [comment]
Not sure which branch you're looking at but https://github.com/picqer/exact-php-client/blob/master/src/Picqer/Financials/Exact/SalesInvoiceLine.php has both AmountDC and AmountFC listed in the $fillable property.

**Comment by Slijkhuis** [comment]
I'm looking at the master branch. There's a Sales**Invoice**Line and a Sales**Entry**Line. The latter has the problem, the first one is probably ok (I think, I'm not using it myself).

Maybe related, for these API endpoints:

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=GeneralJournalEntryGeneralJournalEntries

and

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=GeneralJournalEntryGeneralJournalEntryLines

you'd expect the PHP classes 'GeneralJournalEntry' and 'GeneralJournalEntryLine', but they are not available in this repo.

These issues are easily solved by making the classes yourself and adding the fields to the $fillable property, but I thought it might have been helpful for other developers to them out.

**Comment by Slijkhuis** [comment]
I see you added the GeneralJournalEntry in pull request #59 , thanks!

**Comment by stephangroen** [comment]
Thanks! Fixed in 8ac7cd38c539446c4caa67b8a3647bf8a67c9766 and v2.13.0
