### ISSUE TITLE
We got thia error Picqer\Financials\Exact\ApiException : Error 403: Forbidden

### ISSUE THREAD

**Issue by jpillai88** [picqer/exact-php-client#581]
We are trying to create purchase invoice with type =8034 Purchase invoice (Credit) through this plugin we got this error.
Please help us ASAP

**Comment by remkobrenters** [comment]
This is a community managed package, can you please put more effort in asking a question. Some example code, what did you try, what are you sending etc. So people can think with you.

**Comment by jpillai88** [comment]
We are trying to create purchase invoice with this package(/api/v1/3285515/purchase/PurchaseInvoices) with Type as 8034 Purchase invoice (Credit).We got Picqer\Financials\Exact\ApiException : Error 403: Forbidden as response.

**Comment by remkobrenters** [comment]
Still not a valid question but see https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-respcodeserrorhandling for what a 403 implies.

**Comment by jpillai88** [comment]
@remkobrenters 
That i found document and error also show forbidden.
We need to know what is issue for this forbidden,we created supplier using API.But Purchase Invoice creation API return this error.Is there any permission issue in our application or any other thing.
We are using this code
 $purchase_order_lines[] = [
            'Amount'      => 10,
            'Quantity'  => 1,
            'UnitPrice' => 5
        ];
       $purchase_invoice = new \Picqer\Financials\Exact\PurchaseInvoice($conn);
       $purchase_invoice->PurchaseInvoiceLines =  $purchase_order_lines;
       $purchase_invoice->Journal = 60;
       $purchase_invoice->Type  = 8033;
       $purchase_invoice->Supplier = '517e7a61-69f3-4ea2-9e85-1101e8be2d05';
       $response =  $purchase_invoice->save();

**Comment by remkobrenters** [comment]
That is a bit more (thank you) but 403 is an Exact Online API error and is related to some permission you are not having. Are you sure all permissions required to do what you want to do are there in Exact Online? If so the only thing you can do is contact Exact and ask their support to help you understand why, even though you have all the permissions, you still get a 403. The package is not the issue here.

**Comment by Eligioo** [comment]
@jpillai88 Permissions are bound to the users that performs the initial OAuth flow. If the user can't create/update an entity through the interface (https://start.exactonline.nl), it's not allowed through the API either. You have to login in Exact Online, go to the user permissions and add the checkboxes accordingly.

**Comment by jpillai88** [comment]
@Eligioo 
![exact-permissions](https://user-images.githubusercontent.com/30799690/184351927-027dc346-aae0-4121-a6c0-bf6d26220829.png)
This is our permission screen all checkbox are checked .Is there any other permission for API?

**Comment by Eligioo** [comment]
@jpillai88 you have to tick the `Administration` option above the `General`, `Financial`. If this won't resolve your issue please contact Exact support since this project isn't meant for this purpose ;-)
