### ISSUE TITLE
Open up for Hacktoberfest

### ISSUE THREAD

**Issue by DannyvdSluijs** [picqer/exact-php-client#585]
As a quick question, would you be willing to consider opening up this repo for hacktoberfest?
From their [site](https://hacktoberfest.com/participation/#pr-mr-details):
> YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR BE LABELED “HACKTOBERFEST-ACCEPTED.”
>Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.
Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).

**Comment by stephangroen** [comment]
@DannyvdSluijs Sure. Just took a quick look at the site. Added the topic to the repo. I'll watch for PR's and make sure to check them within October :) I'll be out of the country and unavailable in the last week, but maybe @remkobrenters can help in that week.

If you need anything more, let me know!

**Comment by DannyvdSluijs** [comment]
All seems okay now.
