### ISSUE TITLE
Missing classes around Documents and attachments

### ISSUE THREAD

**Issue by Eligioo** [picqer/exact-php-client#588]
Exact Online has an `Documents/Documents` entity: `documents/Documents` which points to the `Document.php` class in the library. But there is also a `CRM/Documents` entity: `read/crm/Documents`. The library is missing a class for this entity.

The same is happening for `DocumentsAttachments` which share the same name but live in different namespaces.

@DannyvdSluijs do you want to look into this or should I create a PR?

**Comment by DannyvdSluijs** [comment]
Hi @Eligioo 

I can take a look later this week. Ideally I would like this to be fixed in the repo I’m using for generating the changes. So that we have a future proof fix.  If you’re really keen on getting it fixed asap you can also do the PR on https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator
If not I’ll take care of it all.

**Comment by DannyvdSluijs** [comment]
For the sake of context there is
- https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=DocumentsDocuments
- https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadCRMDocuments

And also:
- https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkDocumentsDocumentAttachments
- https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadCRMDocumentsAttachments

**Comment by DannyvdSluijs** [comment]
@Eligioo I completely lost track of this and will see if I can find some time next week.

**Comment by DannyvdSluijs** [comment]
@stephangroen I believe this was fixed when #589 was merged.

**Comment by stephangroen** [comment]
Hmm, I think so too. It contains the CrmDocument and CrmAttachment classes referred here. 

@Eligioo If this isn't fixed, please reopen :)
