### ISSUE TITLE
Error 400: This endpoint has mandatory filtering applied. A GET request for this endpoint must have a $filter parameter with one of the following fields

### ISSUE THREAD

**Issue by artifex-media** [picqer/exact-php-client#591]
Hi,

Since last week (at least starting tuesday, I think) I am getting a new 400 error:
`Error 400: This endpoint has mandatory filtering applied. A GET request for this endpoint must have a $filter parameter with one of the following fields in the url:Accountant,AccountManager,AddressLine1,AddressLine2,AddressLine3,Blocked,BRIN,BSN,ChamberOfCommerce,City,Classification1,Classification2,Classification3,Classification4,Classification5,Classification6,Classification7,Classification8,Classification,Code,CodeAtSupplier,Country,Created,Email,EndDate,Fax,ID,InvoiceAccount,IsAccountant,IsReseller,IsSales,IsSupplier,MainContact,Modified,Name,Parent,Phone,Postcode,PriceList,Reseller,RSIN,SearchCode,StartDate,Status,Type,VATNumber.`

Coming from the Account model.

The same happens with Item model:
`Error 400: This endpoint has mandatory filtering applied. A GET request for this endpoint must have a $filter parameter with one of the following fields in the url:Barcode,Class_01,Class_02,Class_03,Class_04,Class_05,Class_06,Class_07,Class_08,Class_09,Class_10,Code,CostPriceNew,Created,Description,EndDate,ExtraDescription,FreeBoolField_01,FreeBoolField_02,FreeBoolField_03,FreeBoolField_04,FreeBoolField_05,FreeDateField_01,FreeDateField_02,FreeDateField_03,FreeDateField_04,FreeDateField_05,FreeNumberField_01,FreeNumberField_02,FreeNumberField_03,FreeNumberField_04,FreeNumberField_05,FreeNumberField_06,FreeNumberField_07,FreeNumberField_08,FreeTextField_01,FreeTextField_02,FreeTextField_03,FreeTextField_04,FreeTextField_05,FreeTextField_06,FreeTextField_07,FreeTextField_08,FreeTextField_09,FreeTextField_10,GLCosts,GLRevenue,GLStock,ID,IsBatchItem,IsFractionAllowedItem,IsMakeItem,IsPurchaseItem,IsSalesItem,IsSerialItem,IsStockItem,IsSubcontractedItem,IsTime,IsWebshopItem,ItemGroup,ItemGroupCode,Modified,NetWeightUnit,SalesVatCode,SearchCode,StartDate,Unit.`

And so on with probably more models.

I am seeing a pull request regarding a docs change from 25-10, is there a change for above error in this as well, I'm not seeing anything related for the Account and Item model or Model model - so either probably this still has to be done or I might be doing something wrong, however, we had a smooth running process untill past week so I hope it's a docs change.

--

**Edit:** I think I _do_ see the change related to Account model, but I think there's no change related to Item model, is that correct?

Thanks a lot!

**Comment by erikkraijenoord** [comment]
Same issue on our end with the Item model, any solution available?

**Comment by remkobrenters** [comment]
I must say I have not encountered issued myself yet but I think this relates to the longer running update on the side of Exact where they try to reduce the load on the API by making filtering mandatory and deploying more sync endpoints to steer users in that direction. 

Only thing I would expect to see (but do not see directly) is any indicator in the documentation that the endpoints have changed and that filters are now mandatory. Only mention I found is in [this post in the knowledge base](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2107-rn-appcenter-mandatoryfiltering) from last year.

Not sure if someone else sees something I am overlooking in the API documentation about this?

**Comment by artifex-media** [comment]
> Not sure if someone else sees something I am overlooking in the API documentation about this?

I think it might be this $filter attribute? See this reference, first link for example and then the Example usage:
https://github.com/picqer/exact-php-client/issues/588#issuecomment-1274191324

Example usage:
api/v1/{division}/documents/Documents?$filter=ID eq guid'00000000-0000-0000-0000-000000000000'&$select=Account

I assume this is new since 25-10 docs and should be on base Model or multiple models? But this is what I spot quickly

**Comment by remkobrenters** [comment]
These filter references were there on multiple endpoints before. The post in the knowledge base states "In the reference documentation, you can see where filtering is mandatory for each specific property in the new Filter column" but the label above the filter column states "Check mark in this column indicates that this field can be used in a filter. If no check mark in this field it indicates you cannot filter on this field." so it is not very clear to me when the filter is mandatory.

**Comment by erikkraijenoord** [comment]
In my case it helped using the code below, don't know why this works and filter() with combination select() doesn't.

```php
// Current date
$date     = date("Y-m-d");

// Collect items created today
$getItems = new \Picqer\Financials\Exact\Item($connection);
$products = $getItems->get([
    '$filter' => "Created ge datetime'{$date}'", 
    '$select' => "ID,Code,Barcode,Description,ExtraDescription"
]);

**Comment by artifex-media** [comment]
> These filter references were there on multiple endpoints before. The post in the knowledge base states "In the reference documentation, you can see where filtering is mandatory for each specific property in the new Filter column" but the label above the filter column states "Check mark in this column indicates that this field can be used in a filter. If no check mark in this field it indicates you cannot filter on this field." so it is not very clear to me when the filter is mandatory.

Now that I am looking on a computer, I see, but maybe they made any change regarding it's required state, perhaps it wasn't actually required at all before and now it actually it is, hence - errors?

@erikkraijenoord Nice, will play with that also

**Comment by artifex-media** [comment]
> In my case it helped using the code below, don't know why this works and filter() with combination select() doesn't.
> 
> ```
> // Current date
> $date     = date("Y-m-d");
> 
> // Collect items created today
> $getItems = new \Picqer\Financials\Exact\Item($connection);
> $products = $getItems->get([
>     '$filter' => "Created ge datetime'{$date}'", 
>     '$select' => "ID,Code,Barcode,Description,ExtraDescription"
> ]);
> ```

For me this was fine (same on Item model):
```
$accounts = new \Picqer\Financials\Exact\Account($connection);
$result = $accounts->get([
    '$filter' => "Created ge datetime'{$date}'"
]);
```
($select to be added once fields are known)

Where {$date} is 1970-01-01 as I need *all* Accounts/Items for importing in some scenarios. 
@remkobrenters maybe you have a better solution for this (since ^ is not a great solution)? And is there anything known on why we now need $filter and we didn't before? Security measure to prevent DB overloading?

**Comment by DannyvdSluijs** [comment]
So I believe the changes are on the API side which made filtering required but it doesn’t show in the documentation. If that is the case it would be difficult to automatically add this during the code generation. 

However the code generation does keep custom bits of code untouched (if I recall correctly) so if we can think of an improvement in this codebase I’m confident I can manage during the code generation phase.

**Comment by remkobrenters** [comment]
@DannyvdSluijs yes looks like it. I tried to get an answer from Exact regarding the changes made without reflecting it in the documentation but beside a link to the post in the knowledge base I did not get a real answer.

**Comment by DannyvdSluijs** [comment]
I just checked the docs once again but it doesn’t show anything about filtering being mandatory.

**Comment by remkobrenters** [comment]
No it does not. Basically we have to guess which filters are mandatory. I asked Exact Online about this in November last year and got no sensible answer:

> In de release notes [https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2107-rn-appcenter-mandatoryfiltering] staat op welke endpoints er verplicht gefilterd moet worden.
> 
> Vervolgens kun je bij iedere endpoint in de documentatie vinden waarop gefilterd kan worden.
> 
> Er staat een Kolom Filter met hierin vinkjes waarop gefilterd kan worden.

**Comment by artifex-media** [comment]
We had a similar answer as well. For now only the error exceptions will tell you what's mandatory, makes no sense.

**Comment by remkobrenters** [comment]
Will close this issue as it is a sad implementation choice made by Exact that for now is not something we (the package people) can do anything about.
