### ISSUE TITLE
Not getting any of the FreeTextFields/FreeNumberFields in Picqer\Financials\Exact\BulkItem

### ISSUE THREAD

**Issue by RynaldSW** [picqer/exact-php-client#592]
Hello everybody,

I try to get all products with Picqer\Financials\Exact\BulkItem and get all the data.
This is succesfull except for the FreeTextFields/FreeNumberFields am I doing something wrong?

Here are my extra fields im trying to get:
![image](https://user-images.githubusercontent.com/113664371/199673378-704be7ea-50b2-4ad9-82fc-c6585d5e85dc.png)
![image](https://user-images.githubusercontent.com/113664371/199673476-e600c4fb-52b3-4aca-af36-d6bd1729ffe5.png)
Here is the Product im testing it on where you can see the extra fields that are used.
![image](https://user-images.githubusercontent.com/113664371/199673665-f1d963c4-d580-4bae-b8db-f27d4b3ef30d.png)

Here is the code i'm executing:
```csharp
public function GetBulkItems()
    {
        try {
            $stockItems = new \Picqer\Financials\Exact\BulkItem($this->ConnectionExact);
            $result = $stockItems->filter('', '', 'ID,Code,Description,ExtraDescription,UnitDescription,CostPriceCurrency,CostPriceStandard,CostPriceNew,StandardSalesPrice,ItemGroup,PictureUrl,PictureName,Stock,Created,Modified,FreeTextField_01,FreeNumberField_01');
            return $result;
        } catch (\Exception $e) {
            return get_class($e) . ' : ' . $e->getMessage();
        }
}
```

```json
{
  "ID": "1598853b-38f7-4dfe-9ffc-001b0b89d2f6",
  "StandardSalesPrice": 0,
  "Code": "230842315",
  "CostPriceCurrency": "EUR",
  "CostPriceNew": null,
  "CostPriceStandard": 2.6,
  "Created": "/Date(1488281307800)/",
  "Description": "Quad Laagspannings Op Amptest",
  "ExtraDescription": null,
  "FreeNumberField_01": null,
  "FreeTextField_01": null,
  "ItemGroup": "7b71311b-0c48-4c6a-8444-ba8a0a81a2c6",
  "Modified": "/Date(1667466873357)/",
  "PictureName": "250 x 250 opamp.jpg",
  "PictureUrl": "https://start.exactonline.nl/docs/SysImage.aspx?Table=Items&ID=1598853b-38f7-4dfe-9ffc-001b0b89d2f6&ThumbSize=500&NoCache=1&OptimizeForWeb=1&_Division_=3268394",
  "Stock": 100,
  "UnitDescription": "stuk"
}
```
Thanks in advance!

**Comment by DannyvdSluijs** [comment]
My first approach to find the cause would be to debug the data that is being sent by ExactOnline. 

You can check https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-response on how to log the request and response from the http point of view.

**Comment by remkobrenters** [comment]
@RynaldSW can you follow up if you resolved this or found out something worth sharing?
