### ISSUE TITLE
Exceptions without errors

### ISSUE THREAD

**Issue by vanderlee** [picqer/exact-php-client#596]
Since a few months, I'm getting Guzzle exceptions while using this package to communicate with Exact. The Guzzle exceptions shows no error reason (reason: null) and "200 OK" HTTP returns. Any idea what might be happening? I'm on version 3.40.0 but can't find anything in the changelog that indicates something like this being fixed.

**Comment by vanderlee** [comment]
The Guzzle exceptions contain the full request and response messages; they all seem valid as far as I can see. Could this be some JSON parsing issue perhaps (even though JSON response seems valid as well)?

**Comment by DannyvdSluijs** [comment]
I'm afraid without any details people can help you out on your issue.
I've been helping out for some time now and haven't seen any of these related issues.
For now I can only recommend to do a step-by-step debug using something like [XDebug](https://xdebug.org) or just by adding `var_dump()` statements to see where stuff breaks.

**Comment by remkobrenters** [comment]
@vanderlee do you have more information for @DannyvdSluijs or are you not ably to elaborate further and can we close the issue?

**Comment by vanderlee** [comment]
Don't have any further information right now. This integration might be dropped altogether, so it's been re-(de-?)prioritized.
