### ISSUE TITLE
Old refresh token used in loop

### ISSUE THREAD

**Issue by dvdhoek** [picqer/exact-php-client#598]
I'm currently experiencing issues with old refresh tokens being used. I think it has to do with the time it takes to get all the pages. I'm using the following code: 

```$generalLedgerTransactions = new Exact\SyncTransactionLine($connection);

$generalLedgerTransactions = $generalLedgerTransactions->getResultSet([
            '$filter' => 'Timestamp gt 0L',
            '$select' => 'Timestamp, AmountDC, AmountFC, ExchangeRate, Date, FinancialPeriod, FinancialYear, Currency, Division, Description,
            EntryID, GLAccount, GLAccountCode, ID, Type, Account, Document, CostCenter, CostUnit, EntryNumber', ]);

        while ($generalLedgerTransactions->hasMore()) {
            $transactions = $generalLedgerTransactions->next();
            $exactUser->update([
                'auth_data' => [
                    'access_token' => $connection->getAccessToken(),
                    'refresh_token' => $connection->getRefreshToken(),
                    'access_token_expires_at' => $connection->getTokenExpires(),
                ],
            ]);
          // store the transaction 
}
```

What I think is happening is that the token expires while the loop is running. Is there a way to make `$generalLedgerTransactions->next()` use the newly acquired refreshToken?

**Comment by DannyvdSluijs** [comment]
As far as I can see in code this is already being done. The `next()` method on the ResultSet use the `get()` method on the Connection which calls `createRequest()` internally. Which calls the `checkOrAcquireAccessToken()` method.

Maybe worth checking other pieces of your code is helpful. Or adding logging to your setup can help, see https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-response.
Actually reading up on our own tips I realised there is the token update callback, for this see https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#persisting-new-access--refresh-token-when-newly-acquired

**Comment by dvdhoek** [comment]
Thanks for your pointers, I'll check this out and get back here if I find a solution.
