### ISSUE TITLE
Issue with updating salesInvoice (PUT)

### ISSUE THREAD

**Issue by onokje** [picqer/exact-php-client#600]
I have an issue with updating existing sales invoices. The error from exact: 
"A problem has occurred. The cause of this issue will be investigated as soon as possible."
I traced the problem to the following fields:

```
  "IncotermAddress": null,
  "IncotermCode": null,
```

If I manually do a request to the Exact online API with these fields removed, the problem goes away. I contacted Exact online support about this issue. They stated that we should not include all fields when doing PUT requests, but only the ones that you want to update. I already reported my findings to them as stated above.
Anyone familiar with this issue?

Regardless of this issue, the library does indeed send many fields with PUT requests that are not valid. The documentation lists all valid fields for all HTTP methods. This is something that can break the library in the future.

**Comment by DannyvdSluijs** [comment]
Based on https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesInvoiceSalesInvoices both of the fields you've listed seemed to be allowed in the PUT method.

Besides the above I guess there might be issues with sending some unsupported fields when doing a put request. My generating library (see https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator) has knowledge about the different HTTP methods. If there is a fix available I can make automation apply it to all the entities from the API. So no need to update all 407 entities.
