### ISSUE TITLE
Cannot find GLAccount associated with Financial/TransactionLines

### ISSUE THREAD

**Issue by philiphoek** [picqer/exact-php-client#603]
During the `GET /api/v1/{division}/sync/Financial/TransactionLines` request, we sometimes receive a TransactionLine with a GLAccount that is not returned by `GET /api/v1/{division}/financial/GLAccounts`.

Here is an example.

The GLAccount with remote_id `########-####-####-####-############` has 2 entries which we retrieved on
- 2023-01-30 14:06:47
- 2023-03-20 15:01:34

The GLAccount associated with these entries was only retrieved on
- 2023-03-20 12:01:56

The job that tried to find GLAccount failed at
- 2023-03-20 12:01:49

Which is almost two months after the first entry was added to our database.

I am not sure if this example is helpful, but we are a little bit lost as to why this is happening.

**Comment by DannyvdSluijs** [comment]
Hi Philipe, 

this is an open source package of the Exact Online API. This is not however part of official Exact Online channels. 

Looking at your question and the details it seems your trying to reach out to Exact Online support.
