### ISSUE TITLE
Switch to the new APIs before 1 June, 2023

### ISSUE THREAD

**Issue by bigbase-nl** [picqer/exact-php-client#604]
Any plans for implementing these changes?

API endpoints that will be phased out:
- Sync/CRM/Quotations
- Sync/SalesOrder/SalesOrders
- GET PriceLists
- GET SalesPriceListDetails

New APIs
- Quotation headers (Sync)
- Quotation lines (Sync)
- Sales Order headers (Sync)
- Sales Order lines (Sync)
- SalesPriceLists (GET)
- SalesPriceListPeriods (GET)
- SalesPriceLIstLinkedAccounts (GET)
- SalesPriceListVolumeDiscounts (GET)
- SalesPriceListVolumeDiscounts (Sync)

More info: [https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2209-rn-appcenter-newsyncapi](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-ReleaseNote-rn-2209-rn-appcenter-newsyncapi)

**Comment by bigbase-nl** [comment]
Awesome, when would you think a new version with this update could be available for download? Somewhere this month :)

**Comment by remkobrenters** [comment]
> As far as I can see all new API's are already in here since 11/08/22 (see [68e4e3a](https://github.com/picqer/exact-php-client/commit/68e4e3a1e280b7d417bbd4b97ee533615f80f444)).

Correct. They have been there for a while. So all that is 'missing' is the mention of deprecation but think this is nothing more than a nice to have.

**Comment by DannyvdSluijs** [comment]
Had some fun with this one. Added (a biased form of) deprecation detection support in the meta data tool ([17e6de61](https://github.com/DannyvdSluijs/exact-online-meta-data-tool/commit/17e6de61ddd4da7a080b4878f6d266f3f846ea68) and [16305049](https://github.com/DannyvdSluijs/exact-online-meta-data-tool/commit/163050493962a5fab6c8bdaf4dad414b8ccf9d96)) and created an update for the [generator](https://github.com/DannyvdSluijs/PicqerExactPhpClientGenerator/commit/c2f06adacd15e6dcc6858f1a8cf930f89af4f573)

And ultimately pushed an update to #605 adding the `@deprecated` annotation to the sources

**Comment by bigbase-nl** [comment]
My bad, I see now everything, was looking in the wrong place. The deprication detection was an unneeded but amazingly nice addition in such short time, my compliments ;)
