### ISSUE TITLE
SalesOrderOrderChargeLines not available in bulk

### ISSUE THREAD

**Issue by bigbase-nl** [picqer/exact-php-client#607]
It seems that the new "SalesOrderOrderChargeLines" is included in the SalesOrder, but not (yet) in the bulk SalesOrder. Seems to be the only difference currently...

_Error 400: Type 'Exact.Web.Api.Models.Bulk.SalesOrder' does not have a property named 'SalesOrderOrderChargeLines'_

Can be easily fixed by setting the "protected $fillable" of the "BulkSalesOrder" I guess...?

Or for quick fix outside of library use:
_$select = $BulkSalesOrder->getFillable();_
_if (($key = array_search('SalesOrderOrderChargeLines', $select)) !== false) unset($select[$key]);_

**Comment by remkobrenters** [comment]
Can you elaborate more what you try to achieve as setting the fillables for the bulk endpoint does not directly makes sense to me as it is a readonly (GET) endpoint so technically there are no fillables.

**Comment by bigbase-nl** [comment]
Of course the name fillables is indeed confusing here. We use this array to GET all fields with a "$select" from https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkSalesOrderSalesOrders, since it is mandatory to provide the $select query option with a selection of one or more of the resource properties. 

In this case we would want all data so we use all "fillables" in the $select, but the "SalesOrderOrderChargeLines" is than not available.

**Comment by remkobrenters** [comment]
Got it and also understand the issue you are dealing with. Must be something more people bump into with the mandatory selects but not sure what would be a good way to resolve this. A direction could be to add a new property for `$selectable` or something but this has a broader impact than just this endpoint.

**Comment by DannyvdSluijs** [comment]
I think might be related to the inheritance that is in the [BulkSalesOrder](https://github.com/picqer/exact-php-client/blob/4669343bf2fc2cc7009fd3e2b5e239d384dfc841/src/Picqer/Financials/Exact/BulkSalesOrder.php#L10)

Removing the inheritance and making `BulkSalesOrder` a separate entity of its own feels like the right way as this issue shows that `BulkSalesOrder` isn't a extension of the `SalesOrder`

**Comment by remkobrenters** [comment]
Yeah that is a start but I can imagine having a way of looking up the allowed selectable fields would be nice or do you think there is no need?

**Comment by bigbase-nl** [comment]
That would be nice sometimes indeed, but those are two different subjects.
Theoretically it is true that it should be a different entity, although currently it is very convenient like this. I also assume the "SalesOrderOrderChargeLines" will be added to the bulk later (since this is now new), so maybe there is no need to split it at all...
