### ISSUE TITLE
Requesting AccountItem results in 400 Bad Request - Error in query syntax

### ISSUE THREAD

**Issue by martijn-coolminds** [picqer/exact-php-client#609]
Hey, I'm trying to request AccountItem, but this results in an error.
This is my first time working with Exact, so I might just be doing something wrong. 

The request is done as followed:
`
$item= new \Picqer\Financials\Exact\AccountItem($connection);
$itemList= $item->getAsGenerator();
`

The debug log from Monolog just prints out the request:
`
[2023-05-12T11:01:56.109089+02:00] Exact.INFO: CM-NB14 GuzzleHttp/7 - [12/May/2023:11:01:56 +0200] "POST /api/oauth2/token HTTP/1.1" 200 1798 [] []
[2023-05-12T11:01:56.374762+02:00] Exact.INFO: CM-NB14 GuzzleHttp/7 - [12/May/2023:11:01:56 +0200] "GET /api/v1/current/Me HTTP/1.1" 200 1354 [] []
[2023-05-12T11:01:56.508537+02:00] Exact.INFO: CM-NB14 GuzzleHttp/7 - [12/May/2023:11:01:56 +0200] "GET /api/v1/snip/read/logistics/AccountItems HTTP/1.1" 400 109 [] []
`

I've anonymized some properties with the word "snip" but these are the full logs/traceback.
`
object(Picqer\Financials\Exact\ApiException)#63 (7) {
  ["message":protected]=>
  string(47) "Error 400: Bad Request - Error in query syntax."
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(400)
  ["file":protected]=>
  string(110) "/mnt/snip/public_html/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php"
  ["line":protected]=>
  int(819)
  ["trace":"Exception":private]=>
  array(8) {
    [0]=>
    array(5) {
      ["file"]=>
      string(110) "/mnt/snip/public_html/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php"
      ["line"]=>
      int(287)
      ["function"]=>
      string(30) "parseExceptionForErrorMessages"
      ["class"]=>
      string(34) "Picqer\Financials\Exact\Connection"
      ["type"]=>
      string(2) "->"
    }
    [1]=>
    array(5) {
      ["file"]=>
      string(114) "/mnt/snip/public_html/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php"
      ["line"]=>
      int(164)
      ["function"]=>
      string(3) "get"
      ["class"]=>
      string(34) "Picqer\Financials\Exact\Connection"
      ["type"]=>
      string(2) "->"
    }
    [2]=>
    array(5) {
      ["file"]=>
      string(88) "/mnt/snip/public_html/apps/www/src/activities/cron/SyncProducts.class.php"
      ["line"]=>
      int(63)
      ["function"]=>
      string(14) "getAsGenerator"
      ["class"]=>
      string(35) "Picqer\Financials\Exact\AccountItem"
      ["type"]=>
      string(2) "->"
    }
  }
  ["previous":"Exception":private]=>
  object(GuzzleHttp\Exception\ClientException)#69 (10) {
    ["request":"GuzzleHttp\Exception\RequestException":private]=>
    object(GuzzleHttp\Psr7\Request)#62 (7) {
      ["method":"GuzzleHttp\Psr7\Request":private]=>
      string(3) "GET"
      ["requestTarget":"GuzzleHttp\Psr7\Request":private]=>
      NULL
      ["uri":"GuzzleHttp\Psr7\Request":private]=>
      object(GuzzleHttp\Psr7\Uri)#71 (8) {
        ["scheme":"GuzzleHttp\Psr7\Uri":private]=>
        string(5) "https"
        ["userInfo":"GuzzleHttp\Psr7\Uri":private]=>
        string(0) ""
        ["host":"GuzzleHttp\Psr7\Uri":private]=>
        string(20) "start.exactonline.nl"
        ["port":"GuzzleHttp\Psr7\Uri":private]=>
        NULL
        ["path":"GuzzleHttp\Psr7\Uri":private]=>
        string(42) "/api/v1/snip/read/logistics/AccountItems"
        ["query":"GuzzleHttp\Psr7\Uri":private]=>
        string(0) ""
        ["fragment":"GuzzleHttp\Psr7\Uri":private]=>
        string(0) ""
        ["composedComponents":"GuzzleHttp\Psr7\Uri":private]=>
        string(70) "https://start.exactonline.nl/api/v1/snip/read/logistics/AccountItems"
      }
      ["headers":"GuzzleHttp\Psr7\Request":private]=>
      array(6) {
        ["User-Agent"]=>
        array(1) {
          [0]=>
          string(12) "GuzzleHttp/7"
        }
        ["Host"]=>
        array(1) {
          [0]=>
          string(20) "start.exactonline.nl"
        }
        ["Accept"]=>
        array(1) {
          [0]=>
          string(16) "application/json"
        }
        ["Content-Type"]=>
        array(1) {
          [0]=>
          string(16) "application/json"
        }
        ["Prefer"]=>
        array(1) {
          [0]=>
          string(21) "return=representation"
        }
        ["Authorization"]=>
        array(1) {
          [0]=>
          string(994) "Bearer snip"
        }
      }
      ["headerNames":"GuzzleHttp\Psr7\Request":private]=>
      array(6) {
        ["user-agent"]=>
        string(10) "User-Agent"
        ["host"]=>
        string(4) "Host"
        ["accept"]=>
        string(6) "Accept"
        ["content-type"]=>
        string(12) "Content-Type"
        ["prefer"]=>
        string(6) "Prefer"
        ["authorization"]=>
        string(13) "Authorization"
      }
      ["protocol":"GuzzleHttp\Psr7\Request":private]=>
      string(3) "1.1"
      ["stream":"GuzzleHttp\Psr7\Request":private]=>
      object(GuzzleHttp\Psr7\Stream)#59 (7) {
        ["stream":"GuzzleHttp\Psr7\Stream":private]=>
        resource(44) of type (stream)
        ["size":"GuzzleHttp\Psr7\Stream":private]=>
        int(0)
        ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["readable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["writable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["uri":"GuzzleHttp\Psr7\Stream":private]=>
        string(10) "php://temp"
        ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
        array(0) {
        }
      }
    }
    ["response":"GuzzleHttp\Exception\RequestException":private]=>
    object(GuzzleHttp\Psr7\Response)#76 (6) {
      ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=>
      string(11) "Bad Request"
      ["statusCode":"GuzzleHttp\Psr7\Response":private]=>
      int(400)
      ["headers":"GuzzleHttp\Psr7\Response":private]=>
      array(19) {
        ["Content-Type"]=>
        array(1) {
          [0]=>
          string(16) "application/json"
        }
        ["Content-Length"]=>
        array(1) {
          [0]=>
          string(3) "109"
        }
        ["Cache-Control"]=>
        array(1) {
          [0]=>
          string(18) "no-cache, no-store"
        }
        ["Pragma"]=>
        array(1) {
          [0]=>
          string(8) "no-cache"
        }
        ["Expires"]=>
        array(1) {
          [0]=>
          string(2) "-1"
        }
        ["DataServiceVersion"]=>
        array(1) {
          [0]=>
          string(4) "1.0;"
        }
        ["X-Xss-Protection"]=>
        array(1) {
          [0]=>
          string(13) "1; mode=block"
        }
        ["X-Content-Type-Options"]=>
        array(1) {
          [0]=>
          string(7) "nosniff"
        }
        ["Referrer-Policy"]=>
        array(1) {
          [0]=>
          string(31) "strict-origin-when-cross-origin"
        }
        ["X-RateLimit-Minutely-Limit"]=>
        array(1) {
          [0]=>
          string(2) "60"
        }
        ["X-RateLimit-Minutely-Remaining"]=>
        array(1) {
          [0]=>
          string(2) "58"
        }
        ["X-RateLimit-Minutely-Reset"]=>
        array(1) {
          [0]=>
          string(13) "1683879540000"
        }
        ["X-RateLimit-Limit"]=>
        array(1) {
          [0]=>
          string(4) "5000"
        }
        ["X-RateLimit-Remaining"]=>
        array(1) {
          [0]=>
          string(4) "4766"
        }
        ["X-RateLimit-Reset"]=>
        array(1) {
          [0]=>
          string(13) "1683936000000"
        }
        ["Date"]=>
        array(1) {
          [0]=>
          string(29) "Fri, 12 May 2023 08:18:25 GMT"
        }
        ["Connection"]=>
        array(1) {
          [0]=>
          string(10) "keep-alive"
        }
        ["Set-Cookie"]=>
        array(3) {
          [0]=>
          string(96) "ASP.NET_SessionId=snip; SameSite=lax; path=/; secure; HttpOnly; SameSite=Lax"
          [1]=>
          string(105) "ExactServer{snip}=Division=snip; SameSite=lax; path=/; secure; HttpOnly"
          [2]=>
          string(269) "ExactOnlineClient=R/snip; SameSite=lax; expires=Mon, 31-Dec-2198 23:00:00 GMT; path=/; secure; HttpOnly"
        }
        ["Strict-Transport-Security"]=>
        array(1) {
          [0]=>
          string(46) "max-age=31536000 ; includeSubDomains ; preload"
        }
      }
      ["headerNames":"GuzzleHttp\Psr7\Response":private]=>
      array(19) {
        ["content-type"]=>
        string(12) "Content-Type"
        ["content-length"]=>
        string(14) "Content-Length"
        ["cache-control"]=>
        string(13) "Cache-Control"
        ["pragma"]=>
        string(6) "Pragma"
        ["expires"]=>
        string(7) "Expires"
        ["dataserviceversion"]=>
        string(18) "DataServiceVersion"
        ["x-xss-protection"]=>
        string(16) "X-Xss-Protection"
        ["x-content-type-options"]=>
        string(22) "X-Content-Type-Options"
        ["referrer-policy"]=>
        string(15) "Referrer-Policy"
        ["x-ratelimit-minutely-limit"]=>
        string(26) "X-RateLimit-Minutely-Limit"
        ["x-ratelimit-minutely-remaining"]=>
        string(30) "X-RateLimit-Minutely-Remaining"
        ["x-ratelimit-minutely-reset"]=>
        string(26) "X-RateLimit-Minutely-Reset"
        ["x-ratelimit-limit"]=>
        string(17) "X-RateLimit-Limit"
        ["x-ratelimit-remaining"]=>
        string(21) "X-RateLimit-Remaining"
        ["x-ratelimit-reset"]=>
        string(17) "X-RateLimit-Reset"
        ["date"]=>
        string(4) "Date"
        ["connection"]=>
        string(10) "Connection"
        ["set-cookie"]=>
        string(10) "Set-Cookie"
        ["strict-transport-security"]=>
        string(25) "Strict-Transport-Security"
      }
      ["protocol":"GuzzleHttp\Psr7\Response":private]=>
      string(3) "1.1"
      ["stream":"GuzzleHttp\Psr7\Response":private]=>
      object(GuzzleHttp\Psr7\Stream)#60 (7) {
        ["stream":"GuzzleHttp\Psr7\Stream":private]=>
        resource(46) of type (stream)
        ["size":"GuzzleHttp\Psr7\Stream":private]=>
        int(109)
        ["seekable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["readable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["writable":"GuzzleHttp\Psr7\Stream":private]=>
        bool(true)
        ["uri":"GuzzleHttp\Psr7\Stream":private]=>
        string(10) "php://temp"
        ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=>
        array(0) {
        }
      }
    }
    ["handlerContext":"GuzzleHttp\Exception\RequestException":private]=>
    array(0) {
    }
    ["message":protected]=>
    string(243) "Client error: `GET https://start.exactonline.nl/api/v1/snip/read/logistics/AccountItems` resulted in a `400 Bad Request` response:
{
"error": {
"code": "", "message": {
"lang": "", "value": "Bad Request - Error in query syntax."
}
}
}
"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(400)
    ["file":protected]=>
    string(96) "/mnt/snip/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php"
    ["line":protected]=>
    int(113)
    ["trace":"Exception":private]=>
    array(18) {
      [0]=>
      array(5) {
        ["file"]=>
        string(80) "/mnt/snip/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php"
        ["line"]=>
        int(69)
        ["function"]=>
        string(6) "create"
        ["class"]=>
        string(37) "GuzzleHttp\Exception\RequestException"
        ["type"]=>
        string(2) "::"
      }
      [1]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(204)
        ["function"]=>
        string(20) "GuzzleHttp\{closure}"
        ["class"]=>
        string(21) "GuzzleHttp\Middleware"
        ["type"]=>
        string(2) "::"
      }
      [2]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(153)
        ["function"]=>
        string(11) "callHandler"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "::"
      }
      [3]=>
      array(5) {
        ["file"]=>
        string(81) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php"
        ["line"]=>
        int(48)
        ["function"]=>
        string(28) "GuzzleHttp\Promise\{closure}"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "::"
      }
      [4]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(248)
        ["function"]=>
        string(3) "run"
        ["class"]=>
        string(28) "GuzzleHttp\Promise\TaskQueue"
        ["type"]=>
        string(2) "->"
      }
      [5]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(224)
        ["function"]=>
        string(12) "invokeWaitFn"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "->"
      }
      [6]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(269)
        ["function"]=>
        string(13) "waitIfPending"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "->"
      }
      [7]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(226)
        ["function"]=>
        string(14) "invokeWaitList"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "->"
      }
      [8]=>
      array(5) {
        ["file"]=>
        string(79) "/mnt/snip/public_html/vendor/guzzlehttp/promises/src/Promise.php"
        ["line"]=>
        int(62)
        ["function"]=>
        string(13) "waitIfPending"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "->"
      }
      [9]=>
      array(5) {
        ["file"]=>
        string(76) "/mnt/snip/public_html/vendor/guzzlehttp/guzzle/src/Client.php"
        ["line"]=>
        int(123)
        ["function"]=>
        string(4) "wait"
        ["class"]=>
        string(26) "GuzzleHttp\Promise\Promise"
        ["type"]=>
        string(2) "->"
      }
      [10]=>
      array(5) {
        ["file"]=>
        string(110) "/mnt/snip/public_html/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Connection.php"
        ["line"]=>
        int(283)
        ["function"]=>
        string(4) "send"
        ["class"]=>
        string(17) "GuzzleHttp\Client"
        ["type"]=>
        string(2) "->"
      }
      [11]=>
      array(5) {
        ["file"]=>
        string(114) "/mnt/snip/public_html/vendor/picqer/exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php"
        ["line"]=>
        int(164)
        ["function"]=>
        string(3) "get"
        ["class"]=>
        string(34) "Picqer\Financials\Exact\Connection"
        ["type"]=>
        string(2) "->"
      }
      [12]=>
      array(5) {
        ["file"]=>
        string(88) "/mnt/snip/public_html/apps/www/src/activities/cron/SyncProducts.class.php"
        ["line"]=>
        int(63)
        ["function"]=>
        string(14) "getAsGenerator"
        ["class"]=>
        string(35) "Picqer\Financials\Exact\AccountItem"
        ["type"]=>
        string(2) "->"
      }
      [13]=>
      array(5) {
        ["file"]=>
        string(76) "/mnt/snip/public_html/sys/core/controllers/Activity.class.php"
        ["line"]=>
        int(87)
        ["function"]=>
        string(8) "onCreate"
        ["class"]=>
        string(12) "SyncProducts"
        ["type"]=>
        string(2) "->"
      }
      [14]=>
      array(5) {
        ["file"]=>
        string(71) "/mnt/snip/public_html/sys/core/context/Context.class.php"
        ["line"]=>
        int(423)
        ["function"]=>
        string(6) "create"
        ["class"]=>
        string(8) "Activity"
        ["type"]=>
        string(2) "->"
      }
      [15]=>
      array(5) {
        ["file"]=>
        string(58) "/mnt/snip/public_html/apps/www/etc/init.php"
        ["line"]=>
        int(66)
        ["function"]=>
        string(5) "build"
        ["class"]=>
        string(7) "Context"
        ["type"]=>
        string(2) "->"
      }
      [16]=>
      array(4) {
        ["file"]=>
        string(53) "/mnt/snip/public_html/sys/bin/boot.php"
        ["line"]=>
        int(139)
        ["args"]=>
        array(1) {
          [0]=>
          string(58) "/mnt/snip/public_html/apps/www/etc/init.php"
        }
        ["function"]=>
        string(12) "require_once"
      }
      [17]=>
      array(4) {
        ["file"]=>
        string(55) "/mnt/snip/public_html/apps/www/index.php"
        ["line"]=>
        int(16)
        ["args"]=>
        array(1) {
          [0]=>
          string(53) "/mnt/snip/public_html/sys/bin/boot.php"
        }
        ["function"]=>
        string(12) "require_once"
      }
    }
    ["previous":"Exception":private]=>
    NULL
  }
}
`

**Comment by DannyvdSluijs** [comment]
@martijn-coolminds After some debugging it seems the `accountId` is required as a query parameter. The following scratch returns a `HTTP 200` for me.

```php
<?php

use GuzzleHttp\MessageFormatter;
use GuzzleHttp\Middleware;
use Monolog\Level;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;
use Picqer\Financials\Exact\AccountItem;
use Picqer\Financials\Exact\Connection;

include '/Users/dannyvandersluijs/Projects/OSS/ExactOnline/exact-php-client/vendor/autoload.php';

$log = new Logger('name');
$log->pushHandler(new StreamHandler('/Users/dannyvandersluijs/Projects/OSS/ExactOnline/exact-php-client/debug.log', Level::Debug));

$connection = new Connection();
// Setup you connection specifics here.
$connection->insertMiddleWare(Middleware::log($log, new MessageFormatter(MessageFormatter::DEBUG)));

$item= new AccountItem($connection);
$itemList= $item->getAsGenerator(['accountId' => "guid'DA5C323A-9E33-4859-A764-52254D662BD6'"]);
```

When I leave the `['accountId' => "guid'DA5C323A-9E33-4859-A764-52254D662BD6'"]` out from the function call I get the same error as you describe above.
