### ISSUE TITLE
Client with identifier 'xxx-yyy-zzz' not found.

### ISSUE THREAD

**Issue by freshface** [picqer/exact-php-client#617]
Hi

I am using the example.
Registered a test-app on exact.
But when i try to get a token i always get this error after login` Client with identifier 'xxx-yyy-zzz' not found.`

**Comment by remkobrenters** [comment]
So the client identifier provided is not correct. Assuming you already double-checked your identifier for typo's or other issues. Can it be you are not connecting to the right country? If the client is for example using France you should also use the .fr domain for the connection. 

List of Exact Online domains:
https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-exactonline-sites

Method of connecting to other country (default is NL):
https://github.com/picqer/exact-php-client#connect-to-other-exact-country-than-nl

**Comment by freshface** [comment]
Hi Remco

My clientId and secret are correct.
Also my country is correct.
Also found this, https://forums.invantive.com/t/foutmelding-bij-inlog-exact-online-client-with-identifier-07-not-found/3078

**Comment by remkobrenters** [comment]
Interesting. Not seen or heard of this issue in our implementations so far.

**Comment by freshface** [comment]
I needed to set ```$connection->setBaseUrl('https://start.exactonline.be');```
Now i retrieve an **authorizationcode** that gets stored in the storage.json file but it throws this error

`Could not connect to Exact: Error 400: {"error":"invalid_request","error_description":"Signed data extraction has failed"}`

Any thoughts?
