### ISSUE TITLE
SalesEntry payments

### ISSUE THREAD

**Issue by Mahoke** [picqer/exact-php-client#618]
How do I find out if a SalesEntry has been fully paid?
Is TransactionLine the right model to use? If so how do you filter TransactionLines for a SalesEntry?

**Comment by remkobrenters** [comment]
In most bookkeeping software the payment state of an invoice is not like a boolean but more a conclusion of facts. For example it could also be paid by matching it against an open credit invoice, part cash and part bank payments or even part paid and part written off as irrecoverable. I suggest fetching the [Cashflow/Receivables](https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=BulkCashflowReceivables) to verify it is still (or again) to check if the invoice is there and the full amount has been accounted for. I also advise to allow your code to mark it as open again if things change. For example a incorrect match with a payment could mark the wrong invoice as paid so after correcting it in Exact Online it will appear again.
