### ISSUE TITLE
cURL error 77

### ISSUE THREAD

**Issue by KC031** [picqer/exact-php-client#624]
Dear all,

Since Saturday morning, I can no longer get orders in Exact Online through our platform (which is connected with EOL through the exact-php-client). With every single order, we get the error "cURL error 77". 

This happened for every single order our customers tried to place.

Anyone who has got the same issue?

I have contacted the EOL support as well.

**Comment by remkobrenters** [comment]
Think it is a problem in the configuration of your server (SSL related).

**Comment by KC031** [comment]
Thanks for the prompt feedback. I'm going to keep on checking and update here as well once the problem is located.

FYI: when retrieving information from Exact (the system is getting the stock levels out of Exact every 15 min), I have no trouble at all.

**Comment by KC031** [comment]
I just wanted to update that it was indeed a server issue at our side.
Thanks again for the prompt reply @remkobrenters!

**Comment by remkobrenters** [comment]
You're welcome. Happy you got it working.
