### ISSUE TITLE
Picqer\Financials\Exact\Connection::upload() is missing optional parameters.

### ISSUE THREAD

**Issue by RemcoA4r** [picqer/exact-php-client#628]
You can upload XMLs to Exact with additional parameters in the url.

For example to add Params_Journal for the GLTransactions topic - see "Upload data" on https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Content-xmlsamplecode

The Picqer\Financials\Exact\Connection::upload() method doesn't have a way to do this yet.

**Comment by remkobrenters** [comment]
I will close this issue as formally Exact is phasing out the XML endpoints and adding new endpoints to the REST API to replace them.
