### ISSUE TITLE
SalesOrder / SalesOrderLine API

### ISSUE THREAD

**Issue by klaaskox** [picqer/exact-php-client#64]
I want to add SalesOrders to Exact Online. Will this be supported in the future?

I already tried adding SalesOrder.php and SalesOrderLine.php, based on the code from the SalesEntry files, but I can't get it to work yet. Adding a SalesOrder without SalesOrderLines returns an error telling me I need to add SalesOrderLines (so that's a good sign, ExactOnline seems to understand what I'm trying to do), but when I do add a SalesOrderLine before saving the SalesOrder it returns a 400 error. 

Anybody have any suggestions on how to fix this?

**Comment by stephangroen** [comment]
Can you paste your code for these entities and how your are adding them?

**Comment by klaaskox** [comment]
Fixed it this morning. I added SalesOrder.php and SalesOrderLine.php. Maybe the fillable property lists need to be extended, I only added what I needed.


[SalesOrder.zip](https://github.com/picqer/exact-php-client/files/366154/SalesOrder.zip)

This is how I create a new SalesOrder.:

```
$salesOrder = new \Picqer\Financials\Exact\SalesOrder($EOConnection);
$salesOrder->OrderedBy = '0df3ccec-0cd8-4de1-ac3c-020d73874f93';
$salesOrder->Created = $order->date;
$salesOrder->Currency = 'EUR';
$salesOrder->Description = 'Order description';

$soLines = array();
foreach ($items as $item) {
	
	$soLines[] = array(
		'Item' => '9e4be39b-6f3d-491f-9836-5cebe74a4d1d',
		'Description' => $item->sku,
		'Quantity' => $item->number,
		'UnitPrice' => $item->price,
		'CostCenter' => $costCenter
	);
}

$salesOrder->SalesOrderLines = $soLines;

$salesOrder->save();
```

**Comment by stephangroen** [comment]
Ok, cool. I'll see if I can add them sometime soon.

**Comment by ericappcomm** [comment]
How can I the OrderID  after $salesOrder->save();

**Comment by ericappcomm** [comment]
Go it.

$ID = $salesOrder->OrderID();
$NR = $salesOrder->OrderNumber();

**Comment by 888ba8** [comment]
@erik-picqer @stephangroen @ericappcomm @klaaskox  This looks like a very useful tool! Is someone willing to have a call with me, such that I can ask some questions about this tool please? Would be much appreciated! I would be really happy to learn more about it. Please contact me via 888ba8@gmail.com
