### ISSUE TITLE
how to do an orderby

### ISSUE THREAD

**Issue by WierdApiWizard** [picqer/exact-php-client#645]
i tried to make a function to dynamicly get ordelines(this function works) but i would like to order them ascending or descending by linenumber and i looked thru your examples and other files but i couldnt figure it out yet my question then is how would i add that in my function down below
```
public function syncOrderLine(string $orderNumber):array{
        $Orderline = new \Picqer\Financials\Exact\SalesOrderLine($this->connection);
        $Orderlines = $Orderline->filter("OrderNumber eq $orderNumber",
        '',
            "ID,OrderNumber,LineNumber,Item,ItemCode,ItemDescription,Quantity"
        );
        return $Orderlines;
    }
```

**Comment by WierdApiWizard** [comment]
I wrote a function to combat this issue meybe that somone else finds this usefull

`
    /**
     * Sort a picqer model. This is an object gotten from exact
     * @param \Picqer\Financials\Exact\Model[] $picqerModels array of the data fetched from exact
     * @param array<string, int> $orderBys columns in your object to order and in what order
     * @return array Returns a sorted array of picqer objects
     * @example SortPiqcerArray($OrderLineArray, array('LineNumber' => SORT_ASC))
     */
    function SortPiqcerArray(array $picqerModels, array $orderBys): array
    {

        // Rotate array to have the values to sort by in columns
        // only include the columns that are sorted
        $columnArray = array();
        foreach ($orderBys as $columnName => $sortOrder) {
            $columnArray[$columnName] = array();
            // obtain list of columns in lowercase
            foreach ($picqerModels as $key => $row) {
                $columnArray[$columnName]['_' . $key] = strtolower($row->$columnName);
            }
        }

        $eval = 'array_multisort(';
        foreach ($orderBys as $columnName => $order) {
            $eval .= '$columnArray[\'' . $columnName . '\'],' . $order . ',';
        }

        $eval = substr($eval, 0, -1) . ');'; // replace final comma with closing bracket
        eval($eval);

        // Reconstruct the original array to be in the order of the $columnArray
        $return = array();
        foreach ($columnArray as $columnName => $arr) {
            foreach ($arr as $key => $value) {
                $key = substr($key, 1); // strip initial underscore from key
                if (!isset($return[$key])) {
                    $return[$key] = $picqerModels[$key];
                }
                $return[$key]->$columnName = $picqerModels[$key]->$columnName;
            }
        }
        return $return;
    }
`

**Comment by remkobrenters** [comment]
Thanks for adding it. Two thoughts: Why name it SortPiqcerArray as Picqer is the creator of this package but has nothing to do with the data you are sorting. Plus: It looks overly complicated. If it works and you are happy with it than do not change it but I would suggest taking some time to bring it down to a fraction of this to make it more maintainable.
