### ISSUE TITLE
429 errors

### ISSUE THREAD

**Issue by ameenross** [picqer/exact-php-client#646]
This is not a problem with the library, but I want to share this problem with the community at large.

We programmed a function which is called after instantiating the Exact connection, the only purpose of which is to retrieve the current status of Exact's rate limits. This is so that the `setWaitOnMinutelyRateLimitHit` feature works as intended under all circumstances. This function works, with the only problem being that Exact omits the daily limit information when they return a `429` due to minutely limits and vice versa. However, this is usually of no practical concern as the daily limit is sufficiently high.

Exact still serves us a `429` sometimes (quite often, actually). So we researched the matter, added some debug code and we now see this in our logs:

```log
[2024-05-13 02:01:49] local.WARNING: Rate limits as reported by Exact at the start of the process: {"dailyLimit":5000,"dailyLimitRemaining":4980,"dailyLimitReset":"2024-05-14 02:00:00","minutelyLimit":60,"minutelyLimitRemaining":49,"minutelyLimitReset":"2024-05-13 02:02:00"}
[2024-05-13 02:01:49] local.ERROR: Exact unexpectedly reported a 429 (rate limit) error. {"dailyLimit":0,"dailyLimitRemaining":0,"dailyLimitReset":"1970-01-01 01:00:00","minutelyLimit":60,"minutelyLimitRemaining":0,"minutelyLimitReset":"2024-05-13 02:02:00"} 
```

It is possible, even likely, that we already performed 60 requests in this minute. However, the Exact API reports that we still have room for 49 requests in this minute! It seems the numbers being reported are simply incorrect. We're still awaiting a clarification from Exact's side as to why this is the case. For now, we're treating the headers with some level of distrust by retrying failed jobs more often...

**Comment by ameenross** [comment]
It's worth noting that the number for `daily limit remaining` is far from correct too, as by that time we already performed well over a hundred requests.

**Comment by meijdenmedia** [comment]
If I remember correctly, their servers are not running in the Dutch timezone. The daily limit seems to reset at 02:00 Dutch time. At least a few months ago. In winter time. ❄️

**Comment by ameenross** [comment]
I was always under the impression that their daily reset was at 0:00 UTC. However, this has nothing to do with the daily reset, as everything happened after 2:00.

**Comment by ameenross** [comment]
Alright. I went over this together with someone from Exact support and we finally found the problem. This is one of those cases where Murphy's law applies: "anything that can go wrong, will go wrong".

- when our process starts we first check rate limits
- since the rate limits aren't known yet, a request will be performed (we perform it on the `hrm/Division` endpoint)
- we didn't set the division id yet at this point (which conceptually doesn't seem necessary because we're requesting the *list of divisions*
- in my meeting with the Exact representative he found out that this request had a completely different division id in the URL, a number not known to me at all (we're only working with a single Division id)
- it didn't become very clear from the [documentation](https://support.exactonline.com/community/s/knowledge-base#All-All-DNO-Simulation-gen-apilimits), but apparently the rate limits are specific to the *combination* of OAuth client id and the Division id in the request URL
- that means that we are looking at rate limits numbers for the wrong Division

So after checking what the library does, I found out the cause:
1. the entire request path is constructed in `Connection::get` and `Connection::formatUrl`
2. that adds the Division id to the URL if the return value of `requiresDivisionInRequestUrl` is `true` (which is the case for every endpoint except `system/Users` and `current/Me`)
3. the Division number is retrieved in `Connection::getCurrentDivisionNumber`, which, when the division is not set, will perform a request to `current/Me` and get the current Division id of the user
4. turns out the user account we were given has access to 2 Divisions (which we don't need as we're only using a single one) and
5. the *wrong* division is the currently chosen one

So there you go, mystery solved. I'm happy to say that this appears to mean that there's nothing wrong with Exact's rate limits. Although care has to be taken that the *currently selected division* by the user used for the integration does not affect your logic.

**Comment by remkobrenters** [comment]
Interesting. Thank you for sharing your gained insights.
