### ISSUE TITLE
GLAccount sync no longer provides DeductibilityPercentages

### ISSUE THREAD

**Issue by olia-bn** [picqer/exact-php-client#652]
It seems that the sync endpoint to GLAccounts no longer provides DeductibilityPercentages

https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SyncFinancialGLAccounts

Requesting the endpoint with this property will result in an exception:

Error 400: Type 'Exact.Web.Api.Models.GLAccountSync' does not have a property named 'DeductibilityPercentages'

**Comment by DannyvdSluijs** [comment]
I can confirm that Exact Online has removed the `DeductibilityPercentages` from the documentation for the Sync GLAccounts. See https://github.com/DannyvdSluijs/ExactOnlineRestApiReference/pull/161/files.

**Comment by olia-bn** [comment]
I've received the following confirmation / explanation from Exact support

> Thank you for your question.
> 
> The DeductibilityPercentages is no longer available in the sync API, because if you used this correctly you should do an expand for this field. The expand would give an error. The error is because the timestamp for the GLAccounts might be different from the timestamp for the DeductibilityPercentages.
> 
> I have asked the developers to create a releasenote for this. So sorry they didn't create a releasenote upfront for this change.

**Comment by DannyvdSluijs** [comment]
See https://github.com/picqer/exact-php-client/pull/656 for a fix.
