### ISSUE TITLE
Save() function doesn't handle update function 

### ISSUE THREAD

**Issue by sadiqk2** [picqer/exact-php-client#653]
I am using save function for updating relationship and saving new relationship but it doesn't update rather insert new relationship always
Similarly it doesn't save bank account collection with account model.

**Comment by remkobrenters** [comment]
If I understand you correctly this is how Exact Online works. On creation it saves new entities and from that point on you have to update them through their own endpoints (and not through an update of the parent record). See for example https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=PurchasePurchaseInvoices and than the fields for POST and PUT. You see that the invoice lines are not there for the PUT request.

**Comment by sadiqk2** [comment]
i am trying to save bankAccounts in account model ,its doesnt get save 
anything i am missing

**Comment by remkobrenters** [comment]
Bank accounts cannot be saved as collection (look here https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMAccounts) and filter it by POST. You will see there are no bank accounts. They need to be added separately after creating the account.

**Comment by sadiqk2** [comment]
![Uploading image.png…]()
i followed account model ,check this is it bug then ?

**Comment by remkobrenters** [comment]
Correct. The models are generated based on the Exact Online API documentation. It shows the definition of the entire model that is available and does not specify the differences between the different states (for example the ID is also not available as long as it is not created etc).

You should use the Exact Online API documentation to pinpoint what is available and allowed for POST, PUT etc.

**Comment by sadiqk2** [comment]
shouldnt we remove it ,i can submit the pr then

**Comment by remkobrenters** [comment]
Not really as it is representing the model and it's properties (value, type and description). It helps when using the fields. To make sure your fields work the way you want the Exact Online API documentation should be used. As they constantly change things there one of the community members (@DannyvdSluijs ) created a awesome solution that parses the Exact Online API documentation and generates a PR for all changes in these properties. An example of these changes can be seen here https://github.com/picqer/exact-php-client/pull/635

So manually removing or changing the property definitions is not a viable solution.

**Comment by sadiqk2** [comment]
ah i see ,that's cool 
i am trying to send **findId** by contact name and contact name in exact is already saved as(testing O'husbson)
whenever we try to url encode it doesnt find the correct name rather makes it return null means it doesnt exists.
now if i dont urlencode it does break the request with syntax error ,
what we can do to fix this type of issue here

**Comment by DannyvdSluijs** [comment]
> Not really as it is representing the model and it's properties (value, type and description). It helps when using the fields. To make sure your fields work the way you want the Exact Online API documentation should be used. As they constantly change things there one of the community members (@DannyvdSluijs ) created a awesome solution that parses the Exact Online API documentation and generates a PR for all changes in these properties. An example of these changes can be seen here #635
> 
> So manually removing or changing the property definitions is not a viable solution.

Thanks for the gentle ping, here is once again a PR based on the latests documentation, https://github.com/picqer/exact-php-client/pull/656
