### ISSUE TITLE
Add support for contacts and Addresses collection like for salesentrylines for salesentry

### ISSUE THREAD

**Issue by sadiqk2** [picqer/exact-php-client#654]
It would nice to have collection support for account with contacts and address so that it can taken single model rather different models the same way bank account

**Comment by remkobrenters** [comment]
I think you want to fetch an account with all its addresses and contacts? This is not how the Exact Online API works. For your example of sales entries the lines are there as collection (https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesEntrySalesEntries):
![image](https://github.com/user-attachments/assets/817c33ca-a0e4-4c4f-9421-61cb089cd867)

For accounts there are no such collections for contacts and addressess (https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=CRMAccounts).

**Comment by sadiqk2** [comment]
i want save addresses and contact same way like the bank collections

**Comment by remkobrenters** [comment]
I cannot help you.  I'll need a clearer and more detailed explanation of the functionality you're looking to achieve. Please ensure that the request aligns with what’s possible using the Exact Online API. If you’ve already identified the changes needed, you’re welcome to submit a pull request with your proposed improvements.

**Comment by sadiqk2** [comment]
> I cannot help you. I'll need a clearer and more detailed explanation of the functionality you're looking to achieve. Please ensure that the request aligns with what’s possible using the Exact Online API. If you’ve already identified the changes needed, you’re welcome to submit a pull request with your proposed improvements.

$contact = new Contact($connection);
$contact->FirstName =  'John'; // Dummy value: John
$contact->Account =  '12345'; // Dummy value: 12345
$contact->Phone = 123-456-7890'; // Dummy value: 123-456-7890
$contact->Initials = 'J.D.'; // Dummy value: J.D.
$contact->BusinessFax = '123-456-7891'; // Dummy value: 123-456-7891
$contact->Mobile =  '098-765-4321'; // Dummy value: 098-765-4321
$contact->Email = 'john.doe@example.com'; // Dummy value: john.doe@example.com
$contact->JobTitleDescription ='Manager'; // Dummy value: Manager
$contact->save();

When i try to save or update existing contact it doesn't detect the its existing contact rather tries to insert as new one 
note i have to save seperately from the account.

**Comment by remkobrenters** [comment]
To update an existing contact you need to provide the id of the entity you want to update.

If you look at the logic at https://github.com/picqer/exact-php-client/blob/5ec0ae330436f773407b580cbcaaafe1faea3a2e/src/Picqer/Financials/Exact/Persistance/Storable.php#L35 and https://github.com/picqer/exact-php-client/blob/5ec0ae330436f773407b580cbcaaafe1faea3a2e/src/Picqer/Financials/Exact/Model.php#L210

 you basically see it checks the array of provided data if the id (as specified in the entity as they vary in their naming in Exact Online) exists. If it does not exists it performs an insert request. If it exists it performs an update request.

**Comment by sadiqk2** [comment]
> To update an existing contact you need to provide the id of the entity you want to update.
> 
> If you look at the logic at
> 
> https://github.com/picqer/exact-php-client/blob/5ec0ae330436f773407b580cbcaaafe1faea3a2e/src/Picqer/Financials/Exact/Persistance/Storable.php#L35
> 
> and
> https://github.com/picqer/exact-php-client/blob/5ec0ae330436f773407b580cbcaaafe1faea3a2e/src/Picqer/Financials/Exact/Model.php#L210
> 
> you basically see it checks the array of provided data if the id (as specified in the entity as they vary in their naming in Exact Online) exists. If it does not exists it performs an insert request. If it exists it performs an update request.

Great that helps
