### ISSUE TITLE
Retrieving custom fields of SalesOrders

### ISSUE THREAD

**Issue by Camielluijpen** [picqer/exact-php-client#657]
I need to retrieve the CustomFields of a SalesOrder. We do use Exact Online Premium and I know the fields are added to the SalesOrder. I see the CustomFields property on many models, like SalesOrderLines and Contact, but not on the SalesOrder.

When I customize the SalesOrder class and add it as a fillable, I do get the corresponding URL:
![image](https://github.com/user-attachments/assets/dc313246-31b5-4ce4-8cca-65b8faab9ec9)

However, that's how far as I can get. Can't find a way to then retrieve the custom fields of the SalesOrder. I've also tried to use the CustomField/CustomFields endpoint, but the UUID needed for the 'linkId' filter I get from the URL in the screenshot above is nowhere to be found in the SalesOrder, so that doesn't seem to work.

I'm using the REST SalesOrders/SalesOrder endpoint. If you look at the Exact Online REST documentation, the CustomField property is also there on the SalesOrder endpoint:
https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=SalesOrderSalesOrders
![image](https://github.com/user-attachments/assets/19e6609a-b9c1-42ce-8977-0f7f04682d6c)

Please let me know if there are any more questions or if I'm missing something.

**Comment by remkobrenters** [comment]
The field was added a bit ago by Exact Online and it will be added in the next update (https://github.com/picqer/exact-php-client/pull/656/files#diff-dba0bc035533d6ca8ee3274e0a86b5700494c9973dfc293979295e8748447b47R106).

The linkId and bcName name you get in this field are the ones you need to get the customfields for this resource. What do you mean with "is nowhere to be found in the SalesOrder, so that doesn't seem to work."?

**Comment by Camielluijpen** [comment]
Hey Remko,

Thanks, good to hear that it's already handled!

> The linkId and bcName name you get in this field are the ones you need to get the customfields for this resource. What do you mean with "is nowhere to be found in the SalesOrder, so that doesn't seem to work."?

With this I meant that I expected the linkId to be the same as the SalesOrder guid, since I believe it's meant to be used to retrieve the CustomFields of that same SalesOrder, but the linkId is different than the SalesOrder guid.

**Comment by remkobrenters** [comment]
But did you verify the data returned when you used the provided linkId and bcName does not belong to the sales order?

**Comment by Camielluijpen** [comment]
Hey Remko,

I've been able to make it work, thanks though! Do you have an indication of when the release of this update will be?

**Comment by remkobrenters** [comment]
Cool. Regarding the update. Not sure but Stephan is often very fast. Maybe he is busy or on vacation.
