### ISSUE TITLE
OrderBy

### ISSUE THREAD

**Issue by DaveyGiesen** [picqer/exact-php-client#69]
How can use the OrderBy ODATA function in a filter() request?

**Comment by DaveyGiesen** [comment]
Ah fixed it. For other users. You need to create a array in the in the filter() request.
Example:
`$lines->filter('OrderID eq guid\'' . $salesorder['OrderID'] .'\'', '', '', array('$orderby' => 'LineNumber'));`
One note. You need to change this in Findable.php at the filter function.
`array_merge($system_query_options, $request);` to
`array_merge($request, $system_query_options);`
OrderBy needs to be after the request and not before.

**Comment by vengo071** [comment]
Tried everything, beside that. Thanks!
