### ISSUE TITLE
Creating a new class

### ISSUE THREAD

**Issue by Vartapep** [picqer/exact-php-client#72]
I have created a new class 'ReportingBalance.php' using the code below. However, creating an instance of this class does not work. 

Im trying to create the new instance using:
`$RepBal = new \Picqer\Financials\Exact\ReportingBalance($connection);`

And I have created the new class using:
```
<?php namespace Picqer\Financials\Exact;

class ReportingBalance extends Model
{    
    
    use Query\Findable;
    use Persistance\Storable;
    
    protected $fillable = [
        'ID',
        'Amount',
        'AmountCredit',
        'AmountDebit',
        'BalanceType',
        'CostCentercode',
        'CostCenterDescription',
        'CostUnitCode',
        'CostUnitDescription',
        'Count',
        'Division',
        'GLAccount',
        'GLAccountCode',
        'GLAccountDescription',
        'ReportingPeriod',
        'ReportingYear',
        'Status',
        'Type'        
    ];
    
    protected $url = 'financial/ReportingBalance';
}
```

Am I missing something in the creation of the class?

**Comment by yohancreemers** [comment]
What do you mean by 'creating an instance of this class does not work'. Do you get an error message? All code looks fine to me, I had no problem running it. 

Does the file-path match the name of the Namespace/Class (Picqer/Financials/Exact/ReportingBalance.php)? Otherwise the autoload function can't find the file.

**Comment by Vartapep** [comment]
Yes the file-path is correct. 
I do not get an error message. I have added some echo's for debugging purposes (See below). The '1' obviously is echoed, but the '2' does not echo. Also var_dump($RepBal) does not show anything.

```
try {
    echo '1';
    $RepBal = new \Picqer\Financials\Exact\ReportingBalance($connection);
    echo '2';        
}
```

**Comment by yohancreemers** [comment]
Try removing the try statement (no pun intended). You cannot use 'try' without 'catch' or 'finally'.

**Comment by Vartapep** [comment]
I know, I have a catch statement in place, this is just part of my code. So that is not the problem.

**Comment by Vartapep** [comment]
I started using this SDK today, I have successfully retrieved my userID. But trying the same tactic for the ReportingBalance does not work. This is both try statements:

```
//Get UserID
try {
    $UserInfo = new \Picqer\Financials\Exact\Me($connection);
    $UserID = $UserInfo->find()->UserID;
    echo $UserID;
} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}


try {
    echo '1';
    $RepBal = new \Picqer\Financials\Exact\ReportingBalance($connection);
    var_dump($RepBal);
    
    
} catch (\Exception $e) {
    echo get_class($e) . ' : ' . $e->getMessage();
}
```

**Comment by yohancreemers** [comment]
Hmm, strange. When I copy/paste your code into my project, it just works fine. Have no clue what goes wrong in your project.

**Comment by stephangroen** [comment]
If you can see the '1' and not the '2' there has to be some kind of error that's happening. I also c/p your code into the client and it works fine :)

```php
    $reportingBalance = new \Picqer\Financials\Exact\ReportingBalance($connection);
    $balances = $reportingBalance->filter('', '', '', ['$top' => 1]);

    var_dump($balances);
```

**Comment by Vartapep** [comment]
I forgot to enable error reporting, I get the following error:
`Fatal error: Class 'Picqer\Financials\Exact\ReportingBalance' not found in /XXXX/index.php on line 103.`
Line 103 is `$RepBal = new \Picqer\Financials\Exact\ReportingBalance($connection);`
(/XXXX/ before index.php represents multiple folders, have deleted these names because of privacy)

Which is strange because the naming of paths etc. is exactly the same as for the 'Me' class. Any ideas what causes this?
