### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by Vartapep** [picqer/exact-php-client#76]
Hi,

I've had my application running on my live environment. This worked perfectly fine.
Now I want to do some development locally (due to several reasons i can not use my live environment for this). However, when I transfered my application to my local environment and tested it I get the following error:
`start.exactonline.nl redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS`

Can anyone help me with figuring out what causes this? I can not find the problem. 

I have of course changed the redirect urls to match with my local environment.

Kind regards

**Comment by yohancreemers** [comment]
Can the Exact webservice reach your local environment? Maybe your firewall blocks or redirects the redirect url?

**Comment by Vartapep** [comment]
I do get to the authorisation part. So I can login, after logging in i get redirected to localhost again and get :
`The localhost page isn’t working
localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS`

If i then browse to the local url again I get the same error but with 'start.exactonline.nl' instead of 'localhost'. So I think that the webservice can reach my local environment. Or am I misunderstanding

**Comment by stephangroen** [comment]
Do you have localhost in the return URL? Exact is probably trying to return you to something and then somewhere get's in a loop, perhaps if auth code is not saved properly.

**Comment by Vartapep** [comment]
Sorry I forgot to get back to this issue, turns out I had no writing permissions set. This meant the storage.json file was not writeable.
