### ISSUE TITLE
Transaction lines

### ISSUE THREAD

**Issue by Pirabarlen-Cheenaramen** [picqer/exact-php-client#84]
Question, how do we get transaction lines again? 

```
//(where getTransactions is a wrapper to new Transactions($connection)
 $transactions = $this->exactClient->getTransactions()->filter('','','EntryNumber, ClosingBalanceFC, Description, Date, TransactionLines');

 foreach ($transactions as $transaction) {
var_dump($transaction->TransactionLines);
}

```

> array(1) {
  ["__deferred"]=>
  array(1) {
    ["uri"]=>
    string(136) "https://start.exactonline.de/api/v1/31816/financialtransaction/Transactions(guid'2081821f-337f-45a1-ab62-fca677467846')/TransactionLines"
  }
}

> 

that URI leads me to an XML doc...  (if i used $connection->get($the_above_url) , I get a '<h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>', which doesn't make sense as the client is able to ) any idea ?

**Comment by Pirabarlen-Cheenaramen** [comment]
nevermind figured it out,

adding a class TransactionLines extends Model  does the trick.

**Comment by stephangroen** [comment]
Yep, that entity did not exist yet.

**Comment by mpietraszneurosys** [comment]
@Pirabarlen-Cheenaramen can you explain bit more what did you do ?. I also need to get TransactionLine. Did you create this TransactionLine class by yourself. If so why it doen't exists here ?

**Comment by Pirabarlen-Cheenaramen** [comment]
@mpietraszneurosys, i just created a TransactionLines class, following the same way Transaction was written. You can get the different properties from the api doc, and then you can use it like the rest. I unfortunately do not have the said class with me right now, i'll check and revert back to you
