### ISSUE TITLE
Attributes bug

### ISSUE THREAD

**Issue by ghuisman19** [picqer/exact-php-client#87]
Im trying to send a request like:

$StockPosition = new apis\ExactOnline\Exact\StockPosition($connection, array('ItemId' => '3a6700ce-fb14-477d-8ea9-fd73a2f8d858'));
$result = $StockPosition->get();

But it is not working, first of all, the attributes are not included.
Changed this in Query\Findable.php:

public function get()
    {        
        $result = $this->connection()->get($this->url);
        return $this->collectionFromResult($result);
    }

to this:

public function get()
    {        
        $result = $this->connection()->get($this->url, **$this->attributes**);
        return $this->collectionFromResult($result);
    }

And after that, i changed in Picqer\Financials\Exact\StockPosition the url to: read/logistics/StockPosition

**Comment by stephangroen** [comment]
You should be able to just create a new `StockPosition` object and then use the find on that. Something like:

```php
            $item = new StockPosition($connection);
            $item = $item->filter("ItemId eq '3a6700ce-fb14-477d-8ea9-fd73a2f8d858'");
```
