### ISSUE TITLE
Find doesn't work for stockposition

### ISSUE THREAD

**Issue by silvant** [picqer/exact-php-client#89]
The API docs for stockPosition (https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadLogisticsStockPosition) states that the url to retrieve stock positions is like:
/api/v1/{division}/read/logistics/StockPosition?itemId=guid'00000000-0000-0000-0000-000000000000'

Currently this url is used:
/api/v1/{division}/read/logistics/StockPosition?%24filter=ItemId+eq+guid%2700000000-0000-0000-0000-000000000000%27
This results in a 400 error.

Probably exact-php-client/src/Picqer/Financials/Exact/Query/Findable.php should be edited on line 8-10 to account for this deviation, or StockPosition should not use the Findable mixin and define it's own method. (As StockPosition can also not be listed using get(), maybe this last method is best).

Currently I use: 
$positions = $stock->filter([], '', '', ['itemId' => "guid'{$id}'"]);
$position = $positions[0];
which works.

**Comment by stephangroen** [comment]
Do you know if this is the only deviation?

**Comment by silvant** [comment]
It is the only one I found thusfar like that which is implemented in this php client. It is fully according to documentation though https://start.exactonline.nl/docs/HlpRestAPIResources.aspx
Generally all endpoints with a resource uri that is a link with a name containing the words ' Function Details' (instead of an uri) in the reference documentation list acts like this.
