### ISSUE TITLE
Webhook register

### ISSUE THREAD

**Issue by hajcu** [picqer/exact-php-client#91]
It's not possible to register webhook, i recivee this error,
`Error 500: A problem has occurred. The cause of this issue will be investigated as soon as possible.`

I try to fix that, changing in trait Storable.php 

`return $this->connection()->post($this->url, $this->json(0 TRUE));`
into
`return $this->connection()->post($this->url, $this->json(JSON_UNESCAPED_SLASHES, TRUE));`

but still without result. Doeas anyoun try to register webhook thrue this library ?

**Comment by stephangroen** [comment]
Haven't used that myself yet..

**Comment by silvant** [comment]
I managed to set a webhook like this:
$webhook = new \Picqer\Financials\Exact\WebhookSubscription($exact, array(
		'CallbackURL' => EXACT_WEBHOOK_URL,
		'Topic' => $topic));
$result   = $webhook->insert();

Topics can be found in the exact documentation, examples are: StockPositions, SalesInvoices, SalesOrders, FinancialTransactions, Items

**Comment by egbertwietses** [comment]
Our experiences with webhooks:
[https://pionect.nl/using-webhooks-from-exact/](https://pionect.nl/using-webhooks-from-exact/)

`class SubscribeExact
{
    // See: https://www.linkedin.com/pulse/webhooks-support-9-exact-online-rest-api-resources-added-mijwaart?articleId=7251337886417921254
    protected $topics = [
        'FinancialTransactions',
        'SalesOrders',
        'SalesInvoices',
        'PurchaseOrders',
        'GoodsDeliveries',
        'CostTransactions',
        'TimeTransactions',
        'Documents',
        'Quotations',
        'BankAccounts'
    ];

    /**
     * @param Authentication $exactAuth
     * @internal param Connection $connection
     */
    public function handle(Authentication $exactAuth)
    {
        // First remove all existing subscriptions
        $this->deleteSubscriptions($exactAuth);

        foreach ($this->topics as $topic) {
            $subscription = new WebhookSubscription($exactAuth->getConnection());
            $subscription->CallbackURL = $this->replaceUserPlaceholder(config('pertwo.notify-exact-url'));
            $subscription->Topic = $topic;
            $subscription->save();
        }
    }

    /**
     * @param Authentication $exactAuth
     * @internal param Connection $connection
     */
    private function deleteSubscriptions(Authentication $exactAuth)
    {
        $subscription = new WebhookSubscription($exactAuth->getConnection());
        $subscriptions = $subscription->get();

        foreach($subscriptions as $subscription){
            $subscription->delete();
        }
    }

    /**
     * @param $value
     * @return mixed
     */
    private function replaceUserPlaceholder($value){
        return str_replace('{user}', Auth::user()->id, $value);
    }
}`

**Comment by tomcoonen** [comment]
Using it in production sort of the same way @egbertwietses does, didn't have any issues so far.

**Comment by hajcu** [comment]
Helo,
The problem was json encode in insert function, json encode add extra shlashes into url
`
public function insert()
    {
        return $this->connection()->post($this->url, $this->json(0, TRUE));
    }
    public function update()
    {
        $key = $this->primaryKey;
        $primarykey = $this->$key;
        return $this->connection()->put($this->url . "(guid'$primarykey')", $this->json());
    }
`
i fix, by change to this
`
public function insert()
    {
        return $this->connection()->post($this->url, $this->json(JSON_UNESCAPED_SLASHES, TRUE));
    }

    public function update()
    {
        $key = $this->primaryKey;
        $primarykey = $this->$key;

        return $this->connection()->put($this->url . "(guid'$primarykey')", $this->json(JSON_UNESCAPED_SLASHES, TRUE));
    }
`

**Comment by stephangroen** [comment]
@egbertwietses and @tomcoonen did you need any changes to this library to get webhooks working in production? Any changes we could include here?

**Comment by tomcoonen** [comment]
@stephangroen works fine here, didn't run into any issues.

**Comment by egbertwietses** [comment]
@stephangroen we changed it a bit so it returns object directly, as the call returns an endpoint (and some other info).
Subscribing to the webhooks works fine.

**Comment by stephangroen** [comment]
Thanks for the feedback!

**Comment by mahamood** [comment]
I subscribed using below request:
    $subscription = new \Picqer\Financials\Exact\WebhookSubscription($connection);
    $subscription->deleteSubscriptions();
    $subscription->CallbackURL = $callback;
    $subscription->Topic = "Documents";
    $subscription->save();
Webhook Registered and Notifications are coming to webhook CallbackURL with empty response.
 Please give me suggestion how to authenticate webhook response.
**Thanks & Regards,**
Mahamood ali

**Comment by bouwhuis** [comment]
When i try to create a webhook subscription I receive this error: "Error 500: A problem has occurred. The cause of this issue will be investigated as soon as possible." 

I use this code:
`try {
            $this->connect();

            $webhook = new Exact\WebhookSubscription($this->connection);
            $webhook->CallbackURL = $callbackUrl;
            $webhook->Topic = $topic;

            return $webhook->insert();
        } catch (Exception $exception) {
            dd($exception);
        }`

Is anybody known with this problem? I checked the (old) messages above but they didn`t help.

**Comment by DannyvdSluijs** [comment]
@bouwhuis I would suggest you apply the logging tip from our [wiki](https://github.com/picqer/exact-php-client/wiki/Exact-php-client-tips#log-api-request-and-response) If the message is coming from the Exact Online server it might be best to contact Exact Online support. This repo is an open source community powered API Client and doesn't (and cannot) offer support with your Exact Online specifics.

If they can help you further it might be helpful for others to update here wat the issue is/was.

Hope this helps you in the right direction.
