### ISSUE TITLE
Chicken-egg issue when trying to create SalesEntry

### ISSUE THREAD

**Issue by annejan** [picqer/exact-php-client#93]
When adding a SalesEntry with addItem array item added I get an error  Undefined index: ID  
When trying to save a SalesEntryLine I need an EntryID
When trying to dave a SalesEntry without items I get "No sales entry lines. Sales entry lines must be supplied to create a new sales entry."

How do I solve this chicken-egg conundrum?

**Comment by annejan** [comment]
This was a PEBKAC 
I needed EntryID not ID

**Comment by Rikgeffen** [comment]
I get a other error but it looks like yours :

try {
$Mes = new \Picqer\Financials\Exact\Me($connection);
$result1 = $Mes->get();
foreach ($result as $Mes) {
echo 'Me: ' . $Mes->UserID. '
';
}
} catch (\Exception $e1) {
echo get_class($e1) . ' : ' . $e1->getMessage();
}

for only see my userID and i get this ERROR;

Notice: Undefined index: get in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

Notice: Undefined index: UserID in C:\xampp\htdocs\CM\picqer\exact-php-client\src\Picqer\Financials\Exact\Model.php on line 138
Me:

how can i fix this?

**Comment by casperbakker** [comment]
Nope, has nothing to do with this issue.
