### ISSUE TITLE
Division in formatUrl() defaults to CurrentDivision of Me

### ISSUE THREAD

**Issue by mplus-software** [picqer/exact-php-client#99]
The following code ([found here](https://github.com/picqer/exact-php-client/blob/62e18a9ba2e11a48c2c786200918527cc4b1760a/src/Picqer/Financials/Exact/Connection.php#L382)):
```
/**
     * @return mixed
     */
    private function getCurrentDivisionNumber()
    {
        if (empty($this->division)) {
            $me             = new Me($this);
            $this->division = $me->find()->CurrentDivision;
        }
        return $this->division;
    }
```
causes the URL that is created through `formatUrl()` ([found here](https://github.com/picqer/exact-php-client/blob/62e18a9ba2e11a48c2c786200918527cc4b1760a/src/Picqer/Financials/Exact/Connection.php#L489)) to default to the CurrentDivision of the user that provided access to the API. When a user has access to multiple Divisions, and switches Divisions within the Exact Online webapp, the URL changes accordingly. 

Wouldn't it be better to throw an Exception when `$this->division` is not explicitly set, to prevent accidental communication with the wrong Division?

**Comment by alexjeen** [comment]
Documentation is updated, can you check this and close this issue?

**Comment by mplus-software** [comment]
I don't know if the change in documentation sufficiently addresses the issue.

I don't see the usecase for having the Division default to the currently selected Division of the user at all. I think it would be preferable to prevent any API call unless a Division has been explicitly selected.

**Comment by alexjeen** [comment]
I understand, however the usecase for this library will be very different for every user. It will mean a breaking change if this would be changed.

**Comment by mplus-software** [comment]
Alright.
